### ISSUE TITLE
Need ability to soft delete core entities

### ISSUE THREAD

**Issue by fileman** [oqtane/oqtane.framework#105] opened 2019-09-30 15:39 UTC
In addition to User, Roles and Permissions, are these the other core entities?
- [ ] Sites
- [x] Pages
- [x] PageModules
- [ ] Modules
- [ ] Users

Something to add or something to remove?

**Comment by sbwalker** [comment] 2019-10-01 03:57
Sites, Pages, PageModules, Modules, Users

**Comment by fileman** [comment] 2019-10-08 08:04
For Users, you prefer `[Required]` attribute in Model or `if(string.IsNullOrWhiteSpace(user.DisplayName))
{
user.DisplayName = user.Username;
            }`

**Comment by fileman** [comment] 2019-10-08 09:27
#114 I've opted for handle in the pages, it looks more aligned to other properties in oqtane

**Comment by sbwalker** [comment] 2019-10-17 13:25
Moving this comment from a PR to this issue so that it does not get lost:

Perhaps it would help if I explained the expected behavior ;)

Pages

View Pages - should only display pages which are not deleted.
Delete Page - when a user is in this component and they select the Delete option, the system should set the IsDeleted property to True. It should not modify or delete any dependent objects such as permissions, page modules, settings, etc...
Edit Page - there is no way to edit a deleted page, so there is no need to display the Deleted? field in this view. Which means you do not need to deal with delete/undelete logic in this component.
Recycle Bin - there should be a list ( it could be a pageable grid as you likely want to display the Name, DeletedOn, and DeletedBy columns ) which displays only the deleted pages. There should be an option to Restore a page or Delete a page. Restore would set the IsDeleted property to False. Delete would actually hard delete the object and would need to also remove any dependent objects.
Modules

View Page - should only display modules for the page which are not deleted.
Delete Module - when a user selects the Delete Module option from the Action menu when viewing the page in Edit Mode, the system should set the IsDeleted property on the PageModule to True. It should not modify or delete any dependent objects.
Recycle Bin - there should be a list ( it could be a pageable grid as you likely want to display the Page Name, Module Title, DeletedOn, and DeletedBy columns ) which displays only the deleted modules. There should be an option to Restore a module or Delete a module. Restore would set the IsDeleted property to False for the PageModule. Delete would actually hard delete the PageModule object and would need to also remove any dependent objects - Note - due to the many-to-many relationship between Pages and Modules via the PageModule table, there are a few additional scenarios to consider. When deleting a module in the Recycle Bin you need to check if there are any remaining pages which are associated to the ModuleId. If there are none then it is safe to hard delete the module from the Module table ( and all dependent objects ). If it is linked to other pages then the only record you can hard delete is the PageModule record which was selected - leaving the Module record untouched.

**Comment by hishamco** [comment] 2020-02-25 21:44
Is there anything missing here?

**Comment by sbwalker** [comment] 2020-03-04 18:25
Closing as complete

**Closed by sbwalker** 2020-03-04 18:25 UTC
