### ISSUE TITLE
Expand oqtane extensions management to support extensions without UI

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#1099] opened 2021-02-11 05:59 UTC
Oqtane has very flexible way to install 3rd party oqtane modules (or themes) in run-time.

Using oqtane Module Creator we created external oqtane module https://github.com/2sic/oqtane-imageflow/ so we can deploy it as [ToSic.Imageflow.Oqtane](https://www.nuget.org/packages/ToSic.Imageflow.Oqtane) nuget package and install in run-time [Imageflow.NET](https://github.com/imazen/imageflow-dotnet-server) server image processing and optimizing middleware.

Because Imageflow middleware does not need UI we feel that it is not right to offer Imageflow as Admin module so we removed Client and Shared projects and other code that was not necessary (and ModuleInfo.cs was removed).

Unfortunate side effect is that after installation it is not visible to end user on Admin Dashboards that Imageflow is already installed.

Our suggestion is to expand oqtane to support oqtane extensions without UI.

**Comment by hishamco** [comment] 2021-02-11 16:12
Make sense, not all the module should have UI, @sbwalker if we could add an option to include CRUD UI operation or not

**Comment by hishamco** [comment] 2021-02-11 16:12
Make sense, not all the module should have UI, @sbwalker if we could add an option to include CRUD UI operation or not

**Comment by hishamco** [comment] 2021-02-11 16:13
Make sense, not all the module should have UI, @sbwalker if we could add an option to include CRUD UI operation or not

**Comment by sbwalker** [comment] 2021-03-12 01:20
Closing as this is by design

**Closed by sbwalker** 2021-03-12 01:20 UTC
