### ISSUE TITLE
Removing all permissions from a module should not be allowed.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2036] opened 2022-03-03 12:16 UTC
If you remove all the permissions in module settings for a module and save the module becomes a orphan in the system because it will never render.   To remove the module instance you need to delete the pagemodule record and the module record.  It would be better that the module can never save without a Host permission at least.

**Comment by sbwalker** [comment] 2022-03-03 14:09
there is logic in the PermissionGrid to perform validation and originally it did not allow the Administrator permissions to be removed. However the logic was modified recently in order to support modules which are only available to Host users (an edge case). I am guessing the scenario you reported is only happening when you are logged in as a host user - as in this scenario the permission grid is now allowing you to toggle the permissions for the Administrators role. Is this the case?

**Comment by leigh-pointer** [comment] 2022-03-03 15:27
@sbwalker yes this happens when logged in as host user.

**Comment by sbwalker** [comment] 2022-03-07 17:57
@leigh-pointer there is validation logic in the Permission Grid which says that if you are a host user and no host or admin permissions are specified, then add admin permissions:

```
				if (!ids.Contains(RoleNames.Host) && !ids.Contains(RoleNames.Admin))
				{
					// add administrators role if host user role is not assigned
					ids.Add(RoleNames.Admin);				
				}
```

When I try to remove all of the permissions for a module:

![image](https://user-images.githubusercontent.com/4840590/157090589-6a0cfaa5-517c-4fa5-bf75-7598e53d10f6.png)

And save the module... and then open the settings to see the permissions I see:

![image](https://user-images.githubusercontent.com/4840590/157090717-672f00a6-bbfc-4cbf-91f7-da3d02b4cf8b.png)

So I am unable to reproduce. What version were you using when you logged this issue?

**Comment by leigh-pointer** [comment] 2022-03-07 18:57
It was with the 3.0.3 code base.   I think also I had some custom permissions as well.  I will see if I am able to reproduce on a fresh 3.0.3 code base.

**Comment by sbwalker** [comment] 2022-03-19 13:33
@leigh-pointer were you able to reproduce this issue or should I close it?

**Comment by leigh-pointer** [comment] 2022-03-19 13:52
Need some more time as im currently out from my desk. I will investigate monday and let you know

**Comment by leigh-pointer** [comment] 2022-03-23 06:53
@sbwalker this can be closed.  Thanks

**Closed** 2022-03-23 19:05 UTC
