### ISSUE TITLE
Enh: HTML/Text Editor Auto-Synchronize Content When Switching Between Rich Text and Raw HTML Editors

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3990] opened 2024-03-14 16:03 UTC
# Enhancement Request

## Description

Enhance the HTML/Text Editor to auto-synchronize content when switching between the `Rich Text Editor` and `Raw HTML Editor`.

## Solution Proposed

When a user clicks a tab for the different editors, the synchronize content action takes place if content has changed.

## Screenshots

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/6fa855d6-f75b-4c01-b045-136a6fb8a0ef)

#### Additional Info

It is nice to at least have the button to be able to ensure changes are displayed.  I was just curious if we can make this automatic when switching tabs, synchronize content.

**Comment by sbwalker** [comment] 2024-03-15 12:05
Currently the tab component is simply a wrapper around the Bootstrap tab capability which is rendered client-side and does not include support for intercepting click events.

**Comment by sbwalker** [comment] 2024-03-16 00:45
@thabaum although this seems like a good practical enhancement, it will actually not behave as intended due to the technical limitations of the Quill editor. 

The Quill editor "sanitizes" HTML content, which means that it actually removes HTML elements and changes the format of HTML. This is the reason why the Raw editor was added - so that there is a way to enter HTML markup without it being modified. I use this capability a lot so let me describe the scenario. 

You enter HTML into the Raw editor and save the content. You then reopen the editor and the Quill editor is the default tab and it will be blank (because it sanitized the HTML). Then I switch to the Raw editor and my HTML content is displayed and I can edit it and save again. 

If the editor auto synchronized when switching tabs, it would actually erase the content because it would try to populate the Raw text with the contents of the Quill editor (which has been sanitized). 

Obviously this could be resolved by including a Reset button - but then you are just replacing a Synchronize button with a Reset button - the user experience would be no better. 

I actually believe that the Synchronize button should be removed altogether - partly because it is confusing to users and partly because it does not work as intended due to the behavior of the Quill editor. The Quill editor and Raw editor should be treated as independent elements with no synchronization between them.

**Comment by thabaum** [comment] 2024-03-16 14:27
@sbwalker I totally understand your concerns, this is why I was hoping some things would get resolved in version 2 of Quill.  I am going to spend some time researching it today more to review other possible solutions.  Pretty much for using any editor we need to deal with the anomalies that come with them from what I have reviewed.  In fact it looks like Quill v2 RC3 is out this week...

So from past experience then 2 edit buttons, maybe a create a drop down select button, one for the raw editor and one for rich editor modes, can be used to launch the editor of choice and not be tempted to "sync" content as it will be bugged data being shared potentially?  Seems like the raw one will be the go to one if you want to copy and paste things in a decent editor designed to help format and review.  Maybe it can save in the cleansed of white space, but format itself when displayed to the user even or not...?

As for the rich text editor maybe add the feature to `quill.clipboard.dangerouslyPasteHTML( )` to paste raw HTML into that editor?

Quill does rewrite a lot of HTML for example changes `<br>` to `<p><br></p>` from what I have seen, and read.

I like the rich editor for some tasks, however the raw html editor is more precise for advanced scenarios Quill cannot handle and maybe there can be an on/off option this way for HTML module for administrators and give each editor their own modal.

I think working with this editor like any you really need to get to know it so things work as expected.

I am all for a solution we can discuss here more before proceeding.  I was liking the enhancement to the tab panel itself from the previous PR attempt from @zyhfish.  This would be an example use case even if we do not use it as a solution for the Oqtane Quill HTML Text Editor component module.

Again from the feedback provided using one of our two current solutions of a sync button or auto-sync between the two tab panels I believe 2 editor windows identical and a carrot icon next to the edit button for the two editor type options would be ideal.  This would as suggested remove the need for any sync features.

**Comment by thabaum** [comment] 2024-03-16 14:51
12 hours ago [Quill 2.0 RC 3](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.3) was released.

Here is a list of features compiled from all the [beta to RC3 releases](https://github.com/quilljs/quill/releases) included in the upcoming 2.0 release:
- Fix Quill#getSemanticHTML() for list items
- Remove unnecessary Firefox workaround
- Clipboard Fix redundant newlines when pasting from external sources
- Add formats option for specifying allowed formats
- Fix toolbar button state not updated in some cases
- Narrower BubbleTheme.tooltip type
- Fix Selection#getBounds() when starting range at end of text node
- Improve compatibility with esbuild
- Remove unnecessary lodash usages
- Clipboard Convert newlines between inline elements to a space
- Clipboard Avoid generating unsupported formats on paste
- Clipboard Improve support for pasting from Google Docs and Microsoft Word
- Clipboard Ignore whitespace between pasted empty paragraphs
- Syntax Support highlight.js v10 and v11
- Fix IME not working correctly in Safari
- Clipboard Support paste as plain text
- Fix Quill.getText() not respecting length parameter
- History Fix redo shortcut not working on Linux and Windows
- Keep cursor unlinked to avoid elements being pushed down inside
- Fix combineFormats with multiple values repeated
- Fix selection-change not firing on DOM mutations
- Improve Tab handling in code block
- Add SMS to link protocol whitelist
- Fix embed inherits formats unexpectedly
- Fix HTML and Delta not matching
- Fix inline embed insertions with applyDelta()
- Fix inserting newlines into formatted text
- History: Pass source for history actions
- History: Handle native undo/redo
- Fix block embed attributor errors
- Clipboard: getHTML() should include outer tag when range is entire line

We should review these for things that may help while discussing.

**Comment by sbwalker** [comment] 2024-03-16 20:01
@thabaum I am open to upgrading to 2.0 but I believe it would be best to wait until the 2.0 release is official ie. the philosophy in general is to avoid 3rd party dependencies however where the framework must utilize a dependency it should depend on official release versions. So perhaps we can close this issue and file a new issue "Upgrade to Quill 2.0" and indicate that it should be considered when 2.0 graduates from RC releases to an official release.

**Comment by thabaum** [comment] 2024-03-17 15:31
@sbwalker I believe that by leveraging the features of Quill 2.0 and implementing tab synchronization and a reset button, we can significantly enhance the usability of our editor integration. 

I suggest exploring any lingering issues or improvements with Quill, both resolved and unresolved, to ensure a smooth transition to the new version. This may involve digging into the Quill source code to identify and address any major issues before the 2.0 release. As the Quill editor is integral to our CMS and module creation processes, it's crucial to ensure its functionality meets our standards.

Furthermore, I propose offering a raw editor option alongside the rich HTML editor (which does both with synchronization) for users who prefer working exclusively with HTML. This can be implemented as a secondary option accessible through the current edit button, providing users with flexibility in their editing preferences.

I am currently in the process of building the 2.0 RC3 and testing it with Oqtane. While I've encountered an error regarding the root in the Quill js interop file, I'm actively working to resolve it and proceed with testing.  I have thought of using the CDN but curious so working with source of this project.

In order to ensure a comprehensive testing process, I would appreciate any guidance on specific annoyances or issues you've encountered with Quill that detract from your productivity. By addressing these concerns, we can strive to deliver the best possible experience for all users.

I look forward to your feedback and collaboration on this initiative.

Thank you for your attention to this matter.

**Comment by sbwalker** [comment] 2024-03-17 16:41
@thabaum fundamentally Quill is designed to be an editor used by end users who do not know HTML but need a way to express some basic rich text capabilities. By default it sanitizes HTML to only enable a subset of functionality which are safe to use in most web environments. This is one of the reasons why Quill is popular - because it is NOT an HTML editor and it provides assurances to site administrators that their users cannot inject markup or script which can compromise the site. Version 2.0 will continue to follow this approach as this is the foundation which Quill was built upon.

However, some users are more trusted and experienced with HTML and need a FULL raw HTML experience with no sanitization or abstraction. This is what the Raw HTML editor is designed for in Oqtane.

It was a mistake to include a Synchronize option in the Rich Text Editor, as these 2 experiences are fundamentally different and serve different audiences. From a technical perspective it is simply not possible to expect that a user can transition between the Quill editor and HTML editor and expect that the markup will flow smoothly, as these editors have completely different approaches to content.

**Comment by thabaum** [comment] 2024-03-17 23:10
@sbwalker Sounds like Quill 2.0 has much better clipboard support.  Make 2 editors, one raw html, the other rich text and add import feature for them both.  Convert all current to the Quill 2.0 Rich Text Editor version and move the raw HTML to another component, so you choose and use it and dont have Quill bugging up your work, and your not bugging up quill...

Sounds like something to put on our roadmap if you think this would be the solution?

**Comment by sbwalker** [comment] 2024-03-17 23:25
@thabaum I do not want 2 editors. As a developer I want to be able to easily integrate a single rich text component into my module. I want that rich text component to support both end users and power users, so it needs to have the ability to enable both scenarios. I also want the ability to allow an Administrator to enable or disable specific editor experiences based on their requirements (ie. if they want to prevent entry of HTML for all users). The current RichTextEditor component supports ALL of these requirements. The only thing it does not do well is synchronize content between the Rich Text and Raw HTML editors - which can be resolved by removing the Synchronize buttons and making it clear that the editors are independent elements. This does not prevent us from upgrading to Quill to 2.0 when it is officially released to improve the Rich Text experience.

**Comment by sbwalker** [comment] 2024-03-17 23:31
Synchronize option removed in PR #4009. Closing this issue.

**Closed by sbwalker** 2024-03-17 23:31 UTC

**Comment by thabaum** [comment] 2024-03-22 16:30
@sbwalker a couple UX ideas I had related to this issue with the HTML Editor Raw/Rich tab panels as I can see some confusion at first.

1. Put an Action Dialog component on the first time you click on the "Raw HTML Editor" tab panel to let a user understand switching between modes is not supported and it is best to edit HTML strictly in one or the other... or something of this nature?
2. A user setting can be saved to never show this again type of parameter option for the Action Dialog.  
3. A message in the Raw HTML Editor tab panel at the top?

Not a big deal, just thought I would share some feedback I had thought of recently relating.

Cheers!
