### ISSUE TITLE
Localization not working when using ResourceKey

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1811] opened 2021-11-15 21:44 UTC
In the page edit component we have
`<TabPanel Name="Settings" ResourceKey="Settings">`

in the Resx we have 
Settings.Heading =	SettingsX	

The ResourceKey does not set the Heading property of the TabPanel

Changing the TabPanel to 
`<TabPanel Name="Settings" ResourceKey="Settings" Heading ="change me">`

The heading when renders reads "change me" and not "SettingsX"

Adding Heading=@Localizer["Settings.Heading"] works fine.

Currently there must be a quite few TabPanel Headings that are not getting translated.

**Comment by hishamco** [comment] 2021-11-16 12:41
Let me check this one ...

**Comment by sbwalker** [comment] 2021-11-17 20:49
@leigh-pointer this was broken by #1690 - the issue is that the Name parameter must be treated as immutable ( ie. its value should not be changed ) however the component still needs to support localization. A developer must provide a Name parameter however they can also provide a Heading parameter. If no Heading is provided then the Name should be used as the Heading. I think the logic should be:

```
        if (string.IsNullOrEmpty(Heading))
        {
            Heading = Name;
        }
        Heading = Localize(nameof(Heading), Heading);
```

So the resx file would contain an entry for {ResourceKey}.{Heading} ie. "Appearance.Appearance". However is not clear to me why ResourceKey is used in this component at all as this is really only required for components where there are multiple properties which can be localized ( ie. Label has both Text and HelpText ). In the case of a TabPanel there is only one property which can be localized - Heading.

**Comment by hishamco** [comment] 2021-11-18 11:02
https://github.com/oqtane/oqtane.framework/blob/838d918451f5816f26d87bcc2d3183a19d177764/Oqtane.Client/Modules/Controls/TabPanel.razor#L39-L42

I will push a PR

**Comment by hishamco** [comment] 2021-11-18 11:06
> <TabPanel Name="Settings" ResourceKey="Settings">

The `Name` key should present instead of `Heading`, coz if we supply `Heading` instead it will be confusing. In case of both properties are present `Heading` should win

**Comment by sbwalker** [comment] 2021-11-18 13:52
I think there is some misunderstanding about the expected behavior of this component. The Name property is intended to be immutable and its main purpose is to provide an internal identifier so that a user is able to click on the various tabs in the strip to view them. This functionality was accidentally broken in the past when localization was introduced because the code was changing the value of the Name property - which broke the tab strip functionality. A PR was merged to fix this breakage in functionality but in the process it broken localization.

From a users perspective there is only 1 aspect of this component which is visible - the heading of the tab. Therefore there is only 1 aspect of this component which needs to be localized - the heading of the tab. The expected usage of the component is that a developer provides a Name for internal use and a Heading for external display to the user. However there is fallback logic that if a Heading is not provided the component should use the Name value. However from a localization perspective the only item which needs to be localized is the Heading. I am honestly not sure why we are using ResourceKey in this component at all as ResourceKey is designed for scenarios where there are multiple attributes which need to be localized. That is not the case in this component. However since it was already implemented in this way, it would be best to continue to include ResourceKey so as not to introduce a breaking change. However the only localizable property is Heading.

**Comment by hishamco** [comment] 2021-11-18 13:56
> From a users perspective there is only 1 aspect of this component which is visible - the heading of the tab.

Totally, agree

**Closed** 2021-11-22 21:03 UTC
