### ISSUE TITLE
Issue - Site Access:  Unable to access sites other than default alias

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2793] opened 2023-05-04 19:24 UTC
Issue:  Sites are NOT accessible using an alias other than default site default alias.  This goes for all sub sites as well.  The initial setup site alias seems to work as expected, but any alias added to the default site, or added sites that of coarse have an alias resolve to HTTPS (except if domain is LOCALHOST) even though I do not have an environment configured to do so and even if I did it should just give me an SSL certificate error which I would be able to continue the site still.

I am guessing it has something to do with handling site aliases and security.  As you can see by screenshots and info provided below there are a series of tests I conducted.

Notes:

Not sure if this is an environment issue (VS/OS) or Oqtane Framework.  Since it worked before I am guessing something in the framework changed.

I tested with running VS via Oqtane.Server and IISExpress same results

![image](https://user-images.githubusercontent.com/13577556/236326464-2446a9b1-cc42-44ac-aa3d-a0f7f7d3aadb.png)

![image](https://user-images.githubusercontent.com/13577556/236326545-57a7895a-3588-4b92-9641-64b4e3176b9f.png)

![image](https://user-images.githubusercontent.com/13577556/236327063-62260aa1-eed4-4d9c-8c29-a551b6c73e8e.png)
Notes:

![image](https://user-images.githubusercontent.com/13577556/236302449-3c17587b-b38f-4a7c-9e67-d7a9da5b1eab.png)

For example here I wanted to update the alias for the site so it uses the same port to see if I can navigate to that second site created without modifications.

Question here is why can't I access this site created on second port?  I am navigating to it but I am not able to browse/edit the site.

I made more sites and it seems to be issue since in development where the navigation is set to HTTPS instead of HTTP which is causing an error.

I also noticed maybe some form of validation needs to be present in creating domain alias's since you are allowed to put "http://oqtane.dev" and it creates the following alias:  "https://http//oqtane.dev" which would make it inaccessible making an enhancement like this a necessity so you dont have to edit the DB directly to resolve the navigation error.

Since this is navigating all sites to HTTPS, the default site should do this as well.

Since this is dictated by hosting environment, something is making sites navigate to HTTPS although my environment is HTTP, correct?

This is using latest version of Oqtane dev as of today, I don't believe we had this issue before latest release as I could navigate to other sites created.  Maybe something in my VS settings or ?

I was going to try to reproduce another bug/issue to resolve on secondary site with a Host accessing profile from other sites but I cant get one fired up to do it for some reason.

![image](https://user-images.githubusercontent.com/13577556/236309173-4a990400-7ce5-46fd-9b38-a3cdfc9c07a4.png)

couple examples:
![image](https://user-images.githubusercontent.com/13577556/236309234-79d50734-2fdd-408b-ab00-e909527c7098.png)
![image](https://user-images.githubusercontent.com/13577556/236309317-77b73de1-b5ae-4ca2-8604-2249fcf7db8b.png)
![image](https://user-images.githubusercontent.com/13577556/236309382-80ed95c0-1d23-42d9-845d-b1f317e00fd9.png)

`localhost` sites seem to be HTTP while others are HTTPS if I am reading the browser navigation correctly

![image](https://user-images.githubusercontent.com/13577556/236309716-3a2d72d4-979f-4d24-8e89-9da5f47d26ea.png)

This is how my current HOSTS file resolves to show this is not a problem:
```

127.0.0.1   oqtane.dev
127.0.0.1   sub.oqtane.dev
127.0.0.1   sub.sub.oqtane.dev

```

Hopefully I am only one experiencing this, or coffee on me :)

**Comment by thabaum** [comment] 2023-05-04 22:09
I changed #2793 from enhancement to an issue as the enhancement did not fit the site management page functionality since it is managed in the Site Settings.  

Not sure if anyone else is having this issue yet but I am unable to access sites other than the default alias when created in latest release.

The issue seems to be related to this file:

`http://localhost:44357/_framework/aspnetcore-browser-refresh.js`

error in browser console:

`Firefox can’t establish a connection to the server at wss://localhost:44399/Oqtane.Server/.  -  aspnetcore-browser-refresh.js:234:24 http://localhost:44357/_framework/aspnetcore-browser-refresh.js`

 // dotnet-watch browser reload script

` const webSocketUrls = 'wss://localhost:44399/Oqtane.Server/,ws://localhost:53490/Oqtane.Server/'.split(',');`

`const webSocket = new WebSocket(url, protocol);`

**Comment by sbwalker** [comment] 2023-05-07 02:06
Please provide clear and simple instructions on how to reproduce this problem.

**Comment by thabaum** [comment] 2023-05-08 04:06
reproduce by:

download the latest source and visual studio, fire up Oqtane.Server in visual studio and start the site with either IISExpress or Server debug mode and create a site.

Add a second alias to the site and try to resolve the second alias.

Make the second alias the site primary and lose access to the site.

It always resolved HTTP when i ran a localhost, now it resolves HTTPS no matter what if I recall.  This is all within Visual Studio with Hot Reload and not a release site pushed to an IIS server.

Don't need to add another site, only the first alias setup resolves, the others try to open the site when you click browse and site settings for the site if you try with a second site, but this issue happens with just 1 site 2 alias's I noticed as well. 

I need to try 3.4.2 see if I can reproduce.  I didnt have an issue in the past.

**Comment by sbwalker** [comment] 2023-05-08 13:45
I am unable to reproduce the problem you are describing - however this might be because your repro steps are missing the specific configuration options you are using in your environment (ie. the information entered on the Add Site page in Site Management). 

In my local environment on 3.4.3 I did a clean install and then created sites using a standard domain, an IP address, a different port#, a sub-site (ie. localhost:44357/site1) - using both the Shared Tenancy (using Master database) and Isolated Tenancy (creating a new database) models... and they all work as expected.

So I believe this not an Oqtane issue but rather a local development environment issue with your network configuration.

**Comment by sbwalker** [comment] 2023-05-25 20:21
Closing as unable to reproduce

**Closed by sbwalker** 2023-05-25 20:21 UTC
