### ISSUE TITLE
[BUG] HTML Text QuillJS Editor - Uncaught TypeError: this.emitter is undefined

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4491] opened 2024-08-07 17:44 UTC
### Oqtane Info

Version - 5.2.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
error 

```
Uncaught TypeError: this.emitter is undefined
    value quill.min.js:10278
    observer editor.js:158
    e editor.js:157
    e quill.min.js:10130
    r registry.ts:73
    r op.js:99
    update selection.js:35
    update selection.js:30
    update index.js:114
    value quill.min.js:10280
    observer editor.js:158
    e editor.js:157
    e quill.min.js:10130
    r registry.ts:73
    t quill.js:201
    createQuill quill-interop.js:21
    i blazor.web.js:1
    beginInvokeJSFromDotNet blazor.web.js:1
    _invokeClientMethod blazor.web.js:1
    _processIncomingData blazor.web.js:1
    onreceive blazor.web.js:1
    onmessage blazor.web.js:1
    connect blazor.web.js:1
    connect blazor.web.js:1
    _startTransport blazor.web.js:1
    _createTransport blazor.web.js:1
    _startInternal blazor.web.js:1
    start blazor.web.js:1
    _startInternal blazor.web.js:1
    _startWithStateTransitions blazor.web.js:1
    start blazor.web.js:1
    startConnection blazor.web.js:1
    startCore blazor.web.js:1
    start blazor.web.js:1
    or blazor.web.js:1
    nr blazor.web.js:1
    startCircutIfNotStarted blazor.web.js:1
    resolveRendererIdForDescriptor blazor.web.js:1
    determinePendingOperation blazor.web.js:1
    refreshRootComponents blazor.web.js:1
    rootComponentsMayRequireRefresh blazor.web.js:1
    setTimeout handler*rootComponentsMayRequireRefresh blazor.web.js:1
    onDocumentUpdated blazor.web.js:1
    Ki blazor.web.js:1
    Ji blazor.web.js:1
    <anonymous> blazor.web.js:1
    <anonymous> blazor.web.js:1
```

### Expected Behavior
no errors

### Steps To Reproduce

Edit HTML/Text using the editor and open developer tools (F12)

### Anything else?
![image](https://github.com/user-attachments/assets/dd20131c-d302-4c66-9b53-965e06979e95)

**Comment by sbwalker** [comment] 2024-08-09 17:36
I am unable to reproduce this problem. Is it possible you have an older JavaScript file cached in your browser? What browser are you using?

**Comment by thabaum** [comment] 2024-08-10 20:50
I was using firefox I believe, or edge.  I will review with more details when I have time as maybe it was a browser caching issue as you described.

**Comment by sbwalker** [comment] 2024-08-13 15:49
@thabaum please provide details on how to reproduce, so that I can either investigate this further or close this issue

**Comment by sbwalker** [comment] 2024-08-20 12:15
closing as unable to reproduce

**Closed by sbwalker** 2024-08-20 12:15 UTC
