### ISSUE TITLE
Can't place link to sub-site in menu - results in 404

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2577] opened 2023-02-01 15:25 UTC
I have this setup:

Main site: https://blazor-cms.org/
Sub Site: https://blazor-cms.org/oqtane-tutorials

Going to either one directly works.

On the main site I want to create a link to these tutorials like this:

![image](https://user-images.githubusercontent.com/5321186/216084894-26895465-bfa8-45a7-975a-7a76190c039b.png)

But when I click on the page - which should go to the URL - I get a 404.

The url `oqtane-tutorials` is then also listed in the table `dbo.UrlMappings` and each hit is counted.

It appears that a link in the main menu fails if it points to another site in the same installation. 
My guess is that Blazor or Oqtane intercepts it to do a soft-reload AJAX style, which results in it trying to find the page (without really going to the URL) and then fails. 

Bug?
Any Workaround till this works?

**Comment by iJungleboy** [comment] 2023-02-01 15:27
BTW: I found a workaround by adding `?reload` so I can continue. 
But I do think it's a bug that should be addressed.

**Comment by sbwalker** [comment] 2023-02-15 18:25
I am not able to reproduce this problem locally. I have an installation with 2 sites and I created a page on one site which has a redirect to the other site and it works fine:

![image](https://user-images.githubusercontent.com/4840590/219119098-34f80064-f688-4245-9d98-7d597536e4d1.png)

![image](https://user-images.githubusercontent.com/4840590/219119140-cb60ab41-4a23-4a0a-ae2b-c2077f7913a2.png)

There must be some other configuration or environmental differences which are affecting the behavior in your install

**Comment by sbwalker** [comment] 2023-05-02 13:11
Closing as unable to reproduce

**Closed by sbwalker** 2023-05-02 13:11 UTC
