### ISSUE TITLE
Feat: Linking to language specific content - probably based on url-alias

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1731] opened 2021-10-25 06:14 UTC
At the moment the language is only in the session, so links to anything are always language neutral. 

I believe that both for websites as well as for support and other functionality it's often important to link to a specific language. I like the way Dnn does it, where you can determine that oqtane.me and oqtane.me/en is English, oqtane.me/de is German etc. 

Any chance we can implement this in Oqtane as well? or in another way that would serve the same purpose?

I'm convinced that whatever functionality we implement, it must "just work" - so an optional `?language=en-us` wouldn't work, as that would make it hard to discover for any user wanting to send "the current page" to someone. 

To me there are various viable scenarios, with different priorities.

## Most common: Same Modules, Different Language

In this scenario the modules on a page are the same across languages, they just render a different language. IMHO this covers ca. 95% of all scenarios. 

### Examples

1. In an application this could be a dashboard which is multi-language or any other UI. 
2. In a web site this would be a content-page with is fully or partially translated - when the translation is partial, it will typically fall back to show the untranslated content in the default language

For this I would also want my admins and users to "just send the link as they see it" and have the recipient see the same thing. It would also be crucial for culture-specific links which google would categorize differently. 

## Less Common: Different Page for each Language

This is a much rarer scenario: A page has different "stuff" (so probably different modules or different module order) on it in each language. This is not seen too often, but is common when certain languages just have minimal information, usually telling the user that this content isn't available in a specific language, or when the content is very different per culture. 

I believe this scenario isn't too important ATM, but whatever we do to implement the first scenario should keep this in mind.

**Comment by hishamco** [comment] 2022-02-21 18:08
@sbwalker could you please assign this to me and describe the work needed here. According to my understanding it's related to content localization, but if the intend is to capture the language from the route segment, `RouteDataRequestCultureProvider` is the suitable option

**Comment by sbwalker** [comment] 2022-02-21 18:21
Content localization is not on the current roadmap

**Comment by hishamco** [comment] 2022-02-21 18:23
Exactly but that's what the issue is all about, coz I saw it in the roadmap for `3.1.0`

**Comment by hishamco** [comment] 2022-05-22 20:25
@sbwalker I didn't hear from you since 3 months, is the intend of this to capture the language from route segment?

**Closed** 2023-08-24 14:32 UTC
