### ISSUE TITLE
always have an error message in the page source

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#3734] opened 2024-02-03 09:40 UTC
when check the source code of a page, no matter whether login, there is an error message in the source code:
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/a2386dd0-9911-4827-87ff-8e0c9624be55)

**Comment by sbwalker** [comment] 2024-02-03 13:54
That is the standard Blazor markup for an unhandled exception - it relies on CSS and is not visible by default. It will only become visible if an exception occurs. I will close this issue as it is by design.

**Closed** 2024-02-03 13:54 UTC

**Comment by zyhfish** [comment] 2024-02-03 14:39
This is a bit weird that has exception message in the page source, and it should also not friendly to SEO: https://iloveseo.com/seo/even-if-text-is-hidden-on-the-page-google-will-pick-it-up-if-its-visible-in-the-source-code/
