### ISSUE TITLE
An error occurred when there were multiple language packs

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#1237] opened 2021-04-12 05:20 UTC
**The error:**
System.ArgumentException: An item with the same key has already been added. Key: Oqtane.Client.resources.dll
at Oqtane.Client.Program.LoadClientAssemblies(HttpClient http) in ..\oqtane.framework\Oqtane.Client\Program.cs:line 141

The reason is that the resource file name (Oqtane.Client.resources.dll) is duplicated in the language folders

![image](https://user-images.githubusercontent.com/6874322/114343835-ee409700-9b88-11eb-8ee1-1a5c3707caf9.png)

**Comment by sbwalker** [comment] 2021-04-13 16:23
This appears to only be an issue when running on WebAssembly?

**Comment by sbwalker** [comment] 2021-04-15 01:34
The issue is that the Dictionary needs to use the folder + filename as the key rather than just the filename

**Comment by hishamco** [comment] 2021-04-15 19:52
> The reason is that the resource file name (Oqtane.Client.resources.dll) is duplicated in the language folders

How the `Oqtane.Client.resources.dll` is duplicate?!! I presume something goes wrong, each language should have its own folder that cotains the stallite assemblies

**Comment by hishamco** [comment] 2021-04-17 22:06
@lthoa could you please answer my earlier question, or mention the steps to reproduce the issue

**Comment by sbwalker** [comment] 2021-04-17 23:22
this bug was fixed in #1244

**Closed** 2021-04-17 23:22 UTC
