### ISSUE TITLE
[BUG] Custom module loading problem

### ISSUE THREAD

**Issue by dvdobrovolskiy** [oqtane/oqtane.framework#4581] opened 2024-08-31 22:41 UTC
### Oqtane Info

Version - 5.2.1 (5.2.0, 5.1.2 same story)
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Steps To Reproduce
1.  Create custom module. Restart app
2. Add custom module to any page

Page rendered blank

Really donno the case. 5.2.1, 5.2.0, 5.1.2 same behaviour
Any attemp to create a new module and add it to page - blank page is rendered

Event log gives some clue
Feature - ExceptionMiddleware
Type name - Oqtane.Infrastructure.ExceptionMiddleware, Oqtane.Server, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null
Url - http://localhost:44357/admin/modules/test
Template - Unhandled Exception: {Error} For Endpoint: {Endpoint}

Message - 
Unhandled Exception: Cannot provide a value for property 'TestService' on type 'Testowner.Module.Test.Index'. There is no registered service of type 'Testowner.Module.Test.Services.ITestService'. For Endpoint: Fallback {*path:nonfile}

Exception - 
System.InvalidOperationException: Cannot provide a value for property 'TestService' on type 'Testowner.Module.Test.Index'. There is no registered service of type 'Testowner.Module.Test.Services.ITestService'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Oqtane.UI.Routes.ChangeState(PageState pageState) in C:\Users\dima\source\repos\Olimpium\oqtane.framework-5.2.1\Oqtane.Client\UI\Routes.razor:line 102
   at Oqtane.UI.SiteRouter.Refresh() in C:\Users\dima\source\repos\Olimpium\oqtane.framework-5.2.1\Oqtane.Client\UI\SiteRouter.razor:line 320
   at Oqtane.UI.SiteRouter.OnParametersSetAsync() in C:\Users\dima\source\repos\Olimpium\oqtane.framework-5.2.1\Oqtane.Client\UI\SiteRouter.razor:line 74
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.<WaitForNonStreamingPendingTasks>g__Execute|38_0()
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WaitForResultReady(Boolean waitForQuiescence, PrerenderedComponentHtmlContent result)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Oqtane.Infrastructure.JwtMiddleware.Invoke(HttpContext context) in C:\Users\dima\source\repos\Olimpium\oqtane.framework-5.2.1\Oqtane.Server\Infrastructure\Middleware\JwtMiddleware.cs:line 90
   at Oqtane.Infrastructure.TenantMiddleware.Invoke(HttpContext context) in C:\Users\dima\source\repos\Olimpium\oqtane.framework-5.2.1\Oqtane.Server\Infrastructure\Middleware\TenantMiddleware.cs:line 87
   at Oqtane.Infrastructure.ExceptionMiddleware.Invoke(HttpContext context, IServiceProvider provider) in C:\Users\dima\source\repos\Olimpium\oqtane.framework-5.2.1\Oqtane.Server\Infrastructure\Middleware\ExceptionMiddleware.cs:line 25

Properties - 
{"Error":"Cannot provide a value for property \u0027TestService\u0027 on type \u0027Testowner.Module.Test.Index\u0027. There is no registered service of type \u0027Testowner.Module.Test.Services.ITestService\u0027.","Endpoint":"Fallback {*path:nonfile}"}

**Comment by zyhfish** [comment] 2024-09-01 02:12
I tried with 5.2.1 but can't reproduce, have you open the custom module solution in visual studio and build the solution before restart the application?

**Comment by dvdobrovolskiy** [comment] 2024-09-01 08:45
1. Module created via http://localhost:44357/admin/modules/*/20/Create
2. Solution was opened and compiled
3. Also I did exported it as nuget package - same
4. I installed fresh package on new installation (not source) of oqtane 5.2.1 also 5.2.0 also 5.1.2 same

**Comment by dvdobrovolskiy** [comment] 2024-09-01 08:46
Here is module. Can you try it in your environment? 
[Dobrovolskiy.Module.Publications.1.0.0.zip](https://github.com/user-attachments/files/16828117/Dobrovolskiy.Module.Publications.1.0.0.zip)

**Comment by dvdobrovolskiy** [comment] 2024-09-01 11:02
Actual exception found in 
Oqtane.Client\UI\SiteRouter.razor line 320

OnStateChange?.Invoke(_pagestate);

_pagestate
![image](https://github.com/user-attachments/assets/ceac57b0-b2ed-4c2e-ac6b-5e688717f151)


Innter exception found in Renderer.cs line 678 of namespace Microsoft.AspNetCore.Components.RenderTree
value for property 'TestService' on type 'Dobrovolskiy.Module.Test.Index'. There is no registered service of type 'Dobrovolskiy.Module.Test.Services.ITestService'.'

in ProcessRenderQueue()

Innder exception in RenderInExistingBatch line 782 of Renderer.cs
componentState.RenderIntoBatch(_batchBuilder, renderQueueEntry.RenderFragment, out Exception renderFragmentException);

**Comment by dvdobrovolskiy** [comment] 2024-09-01 12:41
Damn, found it,

New module under 5.2.1 framework is create without Startup section
No ModuleNameServerStartup.cs is created so no ConfigureServices called for module. 

Checked couple a time. 5.2.1 framework generates no Startup section. 5.2.0 and lower does

**Comment by sbwalker** [comment] 2024-09-01 12:53
This was already reported in #4562 and was resolved in the Dev branch (5.2.1). Are you using the latest Dev branch code?

**Closed** 2024-09-03 12:45 UTC
