### ISSUE TITLE
cannot logon after a fresh start

### ISSUE THREAD

**Issue by bpaquin** [oqtane/oqtane.framework#441] opened 2020-05-05 14:28 UTC
i received a _tenant was null as soon has I try login into a new database.

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Oqtane.Server
  StackTrace:
   at Oqtane.Repository.DBContextBase.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Projects\GitHub\bpaquin\oqtane.framework\Oqtane.Server\Repository\Context\DBContextBase.cs:line 24
`

**Comment by jimspillane** [comment] 2020-05-05 16:32
I am getting the same error when trying to login on a fresh install. The following lines were removed from TenantResolver.cs in https://github.com/oqtane/oqtane.framework/pull/439 that might be the issue.

https://github.com/oqtane/oqtane.framework/blob/34538dd945fa4bb02f789a0f71f4131d19d6c40d/Oqtane.Server/Repository/TenantResolver.cs#L58-L61

**Comment by sbwalker** [comment] 2020-05-05 18:02
Can you please provide the steps to reproduce

**Comment by bpaquin** [comment] 2020-05-05 18:36
Clone Master, build and run. 
Leave the database configuration part as is. 
Enter a password and an email for host
Click the  Install now button.

in the Welcome To Oqtane page, click login
enter host as Username
enter the password

click Login

**Comment by jimspillane** [comment] 2020-05-05 18:39
On a new install, _Login_ using the _host_ user.  The following error is thrown in DBContextBase.cs because __tenant_ is null.

![image](https://user-images.githubusercontent.com/15007083/81101799-a3c88c00-8edc-11ea-9f08-fb4e3b7b4d1c.png)

Stepping in the TenantResolver.cs code, it looks like __alias_ is null when the _accessor.HttpContext.Request.Path_ is _/pages/login/_  and then __tenant_ is not assigned.

**Comment by sbwalker** [comment] 2020-05-05 18:56
thank you. I merged a major refactoring of the alias area yesterday and must have missed a use case

**Comment by sbwalker** [comment] 2020-05-05 20:28
fixed in #445

**Closed by sbwalker** 2020-05-05 20:28 UTC
