### ISSUE TITLE
2.0.1 not able to install on Azure using automated Azure Deploy button

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#1145] opened 2021-02-27 18:42 UTC
I can't install https://github.com/oqtane/oqtane.framework/releases/tag/v2.0.1 on Azure

1) Create Azure website
2) Deploy Oqtane.Framework.2.0.1.Install.zip
3) Install wizard comes up, enter information (including Host information)
4) Database is created
5) When I try to go to site the install wizard comes up (again)
6) no errors in [oqtane-blazor].[dbo].[Log] (it is empty)
7) There are no users in [AspNetUsers] or [User] tables (**this appears to be the problem**?)

**Comment by sbwalker** [comment] 2021-02-27 20:31
Were you able to install 2.0.0 on Azure?

**Comment by ADefWebserver** [comment] 2021-02-27 20:34
This was the last version I tried yesterday: (it was the latest version in prod); https://github.com/oqtane/oqtane.framework/issues/1140

**Comment by sbwalker** [comment] 2021-02-27 21:06
I have installed the 2.0.1 release package successfully on IIS locally - so this must be specifically an Azure deployment issue.

**Comment by sbwalker** [comment] 2021-02-27 21:12
I am wondering if it might be related to an Azure environment behavior issue similar to https://github.com/oqtane/oqtane.framework/issues/545

**Comment by ADefWebserver** [comment] 2021-02-27 22:11
> I am wondering if it might be related to an Azure environment behavior issue similar to #545

Note I am trying the manual.zip install so I can use my existing azure app.

1) it fully installs and updates the appsetings.Json

2) I cleared the settings and installed again. Everything installs (tables are created) but no host user is created.

**Comment by sbwalker** [comment] 2021-02-28 02:40
Do the Tenant, Alias, and Site tables have records in them after install?

**Comment by ADefWebserver** [comment] 2021-02-28 04:04
> Do the Tenant, Alias, and Site tables have records in them after install?

![image](https://user-images.githubusercontent.com/1857799/109407595-eb6e4780-7936-11eb-9fa9-3bc13e317907.png)

**Comment by sbwalker** [comment] 2021-02-28 14:31
You are certain this is a clean install of 2.0.1 - without any other module assemblies, site templates, or customizations to the appsettings.json? It appears that the CreateSite() method in DatabaseManager.cs is not executing or is throwing an error during your installation - but I do not know why.

**Comment by sbwalker** [comment] 2021-02-28 14:35
Can you also share the contents of your SchemaVersions table?

**Comment by ADefWebserver** [comment] 2021-02-28 15:47
> You are certain this is a clean install of 2.0.1 - without any other module assemblies, site templates, or customizations to the appsettings.json? It appears that the CreateSite() method in DatabaseManager.cs is not executing or is throwing an error during your installation - but I do not know why. - Can you also share the contents of your SchemaVersions table?

I am away from home, let me do this when I get back. I also want to see if the Azure wizard is putting in values in the Config settings for the App Service that the manual method doesn't. Thanks!

**Comment by ADefWebserver** [comment] 2021-02-28 17:32
> Can you also share the contents of your SchemaVersions table?

![image](https://user-images.githubusercontent.com/1857799/109427574-dd0c4400-79a7-11eb-8cdc-813e423396b8.png)

**Comment by ADefWebserver** [comment] 2021-02-28 17:55
A manual install works!

A)	In a new Azure App service (*not* the one created by the “Deploy To Azure” wizard), I deleted all the tables from the database
B)	I deleted all the contents of the wwwroot folder
C)	I ensure there is *not* a DefaultConnection setting in the Configuration for the Azure App Service (I think there was one from before when I re-used one created by the “Deploy To Azure” wizard
D)	I ensure the Azure app service is using .NET Core 5
E)	I deployed Oqtane.Framework.2.0.1.Install.zip
F)	The Oqtane install wizard comes up
G)     The site installs!

![image](https://user-images.githubusercontent.com/1857799/109428222-f793ec80-79aa-11eb-8cb7-81c0f477135a.png)

![image](https://user-images.githubusercontent.com/1857799/109428243-172b1500-79ab-11eb-94a3-fbe37988c0fd.png)



However, now a fresh install using the Azure Wizard doesn’t work ☹

A)	In the Wizard I set the “Blazor Worker Size” to 1 and I think that helped make sure the source code was properly pulled from GitHub
B)	However, there is a DefaultConnection setting in the Configuration for the Azure App Service with the proper “Data Source” database settings (that were set in the Azure “Deploy To Azure” wizard) and the “Type” is set to: “SQLAzure”
C)	I can confirm that the source code was pulled in for the site, 
D)	But, the site won’t come up. It says: “This page isn’t working right nowoqtane-adefwebserver-test.azurewebsites.net can't currently handle this request. HTTP ERROR 500”. There is nothing in the Event Logs

**Comment by sbwalker** [comment] 2021-03-01 15:18
@ADefWebserver I appreciate all of your testing of 2.0.1 over the weekend... I am hoping it might be possible to clarify the current status...

1. Clean install of 2.0.1 from within Visual Studio works fine
2. Clean install locally using IIS works fine
3. Clean install on Azure using manual method works fine ( your original post indicated that it did not work however I am guessing it was because you were trying to re-use an existing app service that was not "clean"? )
4. Clean install on Azure using "Deploy to Azure" button not working. However you also had difficulty installing 2.0.0 using the "Deploy to Azure" button as you logged issue #1140 - so I am not sure if this has anything to do with Oqtane itself.

**Comment by ADefWebserver** [comment] 2021-03-01 16:47
> @ADefWebserver I appreciate all of your testing of 2.0.1 over the weekend... I am hoping it might be possible to clarify the current status...
> 
> 1. Clean install of 2.0.1 from within Visual Studio works fine
> 2. Clean install locally using IIS works fine
> 3. Clean install on Azure using manual method works fine ( your original post indicated that it did not work however I am guessing it was because you were trying to re-use an existing app service that was not "clean"? )
> 4. Clean install on Azure using "Deploy to Azure" button not working. However you also had difficulty installing 2.0.0 using the "Deploy to Azure" button as you logged issue #1140 - so I am not sure if this has anything to do with Oqtane itself.

@sbwalker I think that if anyone else can have the "**Deploy to Azure**" button work, this issue should be closed. 

If they cannot get the "**Deploy to Azure**" to work, I suspect that because the "**Deploy to Azure**" triggers the **https://github.com/oqtane/oqtane.framework/blob/dev/azuredeploy.json** script, and that script creates a **DefaultConnection** property in the **Configuration** settings for the **Azure App Service** ( via the line: _[resourceId('Microsoft.Web/Sites/config', parameters('BlazorWebsiteName'), 'connectionstrings')]_). That _may_ be what is causing the install to fail.

Also:

1. Yes (I have tried it myself)
2. Yes (but I have not tried it myself)
3. Yes (and Yes as to the reason it did not work before)
4. Yes (not working for me)

**Comment by pcancela** [comment] 2021-03-01 17:19
Guys, probably it has nothing to do with it but I remember last time I tried a blazor app on azure it took me a while to get it running because websockets feature was disabled being that the default behavior for an azure app service.

![image](https://user-images.githubusercontent.com/5494384/109533379-103afa00-7ab2-11eb-9b2b-c2544ff1aa7e.png)

**Comment by sbwalker** [comment] 2021-03-01 18:12
@pcancela that issue was resolved in #976

**Comment by ADefWebserver** [comment] 2021-03-01 18:12
@pcancela The should only cause the site to _run slow_, not prevent it from _running at all_. But, I could be wrong... 

Unfortunately I don't currently have a site created by the "Deploy To Azure" button to check that setting. I really hope someone will give it a try with the 2.0.1 version of Oqtane. All previous version of Oqtane worked for me.

**Comment by sbwalker** [comment] 2021-03-01 18:15
@ADefWebserver is there a reason why it should reference the dev branch ( https://github.com/oqtane/oqtane.framework/blob/dev/azuredeploy.json ) - I would think the master branch would be more appropriate

**Comment by ADefWebserver** [comment] 2021-03-01 18:32
> @ADefWebserver is there a reason why it should reference the dev branch ( https://github.com/oqtane/oqtane.framework/blob/dev/azuredeploy.json ) - I would think the master branch would be more appropriate

@sbwalker - Sorry that was me typing too fast. The "Branch" that the "Deploy To Azure" button pulls from is determined by this code in the **azuredeploy.json** file (that is triggered by the button):

```
          "properties": {
            "RepoUrl": "https://github.com/oqtane/oqtane.framework.git",
            "branch": "master",
            "IsManualIntegration": true
          }
```

**Comment by sbwalker** [comment] 2021-03-12 12:50
I changed the title of this issue because it may be alarming to some to think that Oqtane does not run on Azure - when that is clearly not the case. The only remaining issue that I am aware of is that the automated Deploy To Azure option is not working - and this option has always been flaky. I am also not sure it is an Oqtane framework issue - more likely it has something to do with the Azure deploy process.

**Comment by LeandroPT** [comment] 2021-07-20 03:20
Hello all,

Suffered this for a while but i can confirm that the only necessary step (as of today) is to simple remove the default connection string in the webapp configuration as reported by @ADefWebserver in comment https://github.com/oqtane/oqtane.framework/issues/1145#issuecomment-787491863 as step C)

**Closed** 2021-11-04 11:36 UTC
