### ISSUE TITLE
File Upload Failed after Theme changed

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#3656] opened 2024-01-18 15:07 UTC
![image](https://github.com/oqtane/oqtane.framework/assets/6874322/5d72f818-39d7-4805-8d90-61cd7805e5b1)

**Comment by thabaum** [comment] 2024-01-18 21:32
@lthoa do you have any additional details in the F12 Dev Console?

Also have you tested this with the community supported Oqtane Default theme? The "Blazor" theme is only included an example template which really isn't being supported by anyone in the community currenlty although it is included.

**Comment by W6HBR** [comment] 2024-01-18 23:35
I haven't spent the time to debug this, but I can add that I've been running into this issue as well.

**Comment by lthoa** [comment] 2024-01-19 01:21
@thabaum When switching back to Oqtane Default theme, the error still appears.

**Comment by W6HBR** [comment] 2024-01-19 01:28
I just did a test with a fresh install of 5.0.1 and the problem exists there - without changing themes.

**Comment by thabaum** [comment] 2024-01-19 02:10
I tested on my branch as well, very odd, maybe a browser update caused this because this was all working earlier and in the past.  I know it was working on the 5.0.1 release.  I did a file upload in few places many times such as site logo and profile image updates.  This latest release is what you all are testing with now currently correct?

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/220174dd-7538-49cd-b521-47c3e5cf63c7)

Interesting...

**Comment by thabaum** [comment] 2024-01-19 02:21
I did find something about a deprecated feature used relating to XMLHttpRequest

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/063a8db0-1881-4451-a7b5-d44d29d7ec53)

**Comment by thabaum** [comment] 2024-01-19 04:42
I may have found a clue to another issue, but I believe this one can be resolved by updating your Visual Studio application.  It resolved it for me and something I generally check first, had to run to the meetup meeting so didn't get a chance to really review this.

@lthoa and @W6HBR can you verify if updating resolves the issue or is this on a production website?

Thank you
Cheers!

**Comment by lthoa** [comment] 2024-01-19 05:01
I'm using VS 2022 (64-bit), version 17.8.5, is latest version.
This issues from Oqtane update Net8.0

**Comment by thabaum** [comment] 2024-01-19 05:34
@lthoa Can you hit F12 and look for any errors in the developer tools and report back any errors relating?  I was working with latest dev branch download when I tested.

**Comment by lthoa** [comment] 2024-01-19 06:59
@thabaum With the latest dev branch download, there is no difference between the two uploads, the first time was successful when using the default theme when installing, the second time the upload failed after changing the theme.

![1](https://github.com/oqtane/oqtane.framework/assets/6874322/f1a90134-9cb5-4ad7-ba86-956effbddef0)

![2](https://github.com/oqtane/oqtane.framework/assets/6874322/17cd88ce-abe5-4d05-ba43-91a62ee2aade)

**Comment by thabaum** [comment] 2024-01-19 16:30
@lthoa With default Oqtane Theme, I was able to upload many times, as soon as I switched to Blazor theme I did get an error to verify some issue does exist here.
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/a3b676d7-98e2-4096-a5b5-c86bc9e0654d)

```
XML Parsing Error: no root element found
Location: http://localhost:44357/api/file/upload
Line Number 1, Column 1: upload:1:1
```

I get this also with the Maui App even if I add CORS support to the framework.

I have ran into some warnings about needing to use response header for `Cache-Control` so I will review these areas, and look for differences between theme logic for clues.

**Comment by thabaum** [comment] 2024-01-19 19:12
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/fa76b773-ad93-4df8-b9a3-013f18f0bbe2)
I also notice the User Profile Image I was able to upload at first prior to switching themes is no longer found.

**Comment by W6HBR** [comment] 2024-01-19 21:03
@thabaum I just did another test with a fresh install.  Like you, uploads worked fine with the default Oqtane theme, but as soon as I changed the theme to the Blazor theme, the upload broke.  Even after changing it back to the Oqtane theme the upload error persists.  I restarted the application as well as forcing browser refreshes on the pages and the problem persists.

**Comment by thabaum** [comment] 2024-01-19 21:18
@W6HBR You are correct.  I even tried the RocketFuel theme and same issue.  So it is not a "blazor theme" issue but relating to changing to any theme breaks the file controller.

**Comment by W6HBR** [comment] 2024-01-20 03:07
I've done a few more tests with fresh installs and can trigger the error without switching themes.  It seems just uploading a new site logo and saving it a couple of times will then result in generating the upload error.

**Comment by thabaum** [comment] 2024-01-20 04:08
I also verified uploading and saving a logo breaks it.

1. I uploaded a profile image.
2. went to file manager uploaded no problem 6 files to root and user folders.
3. I uploaded one file to make a logo, navigated to profile after saving and the profile image was an error.  
4. Something must be getting saved in the database wrong.  If I delete the connection string and create a fresh installation everything works as described above.

I also found another glitch where if you keep hitting the user profile user name to review your profile... it keeps adding returnurls which I think I can doctor up quickly.
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/3fff0a67-113a-49e5-82ad-b097cf5232a0)

I appreciate your testing as I think this leads us down the right path.

Something being saved when a logo is uploaded.  I have not tried uploading, and then not saving to see if things still work allowing an upload until you save a site.

Something with saving site settings is bugging it out, as if you change theme, site settings is saved, You upload logo, site settings gets saved.

**Comment by thabaum** [comment] 2024-01-20 04:13
@sbwalker This is a verified, dont even need to upload a file.  Just save site settings once changing the name of the site and file manager is bugged out from there on.  Something is glitching the file controller.

I will review this further tomorrow but found two issues here ready to be handled when a solution can be generated by whomever ;) toss your PR's in the hat.  I will probably have one tomorrow for this if not resolved yet now that I know what to look into to close this issue.

Cheers!

**Comment by sbwalker** [comment] 2024-01-20 13:41
It would be very helpful to know if this is only occurring in the Dev branch or if the issue also exists in the last official release. If it is only occurring in the Dev branch then it would be related to recent changes and it may be easier to identify the source of the issue. Also it would be helpful to know the hosting model, database type being used. All of these details are really helpful in isolating and reproducing issues.

**Comment by sbwalker** [comment] 2024-01-20 13:51
My initial thought on this issue is that when certain Site Settings are changed, the browser needs to do a full server reload of the page so that the changes are reflected in the DOM (ie. style sheets, meta tags, etc...). This may be causing issues with the antiforgery token which is used during file upload (as it is a POST operation which is subject to antiforgery validation for security reasons)

**Comment by W6HBR** [comment] 2024-01-20 17:06
I've been testing exclusively in the last official release 5.0.1.  

I've done several tests with fresh installs by clearing the db connection string and creating a new SQLite db.  I've mostly tested by uploading a new site logo as that seems to be the easiest way to reproduce the issue.

Test method:  Upload a site logo, then click save.  Navigate away from the page and come back and you are unable to upload any additional files.  This problem persists through an application restart or even a recompile and restart.

It appears something is getting changed when performing the save on site settings that could be triggering this issue.

**Comment by thabaum** [comment] 2024-01-20 17:37
There is no need to upload a logo, just save site settings.

**Comment by thabaum** [comment] 2024-01-20 19:54
- [HTML encode notifications sent by non-admins to prevent HTML injection](https://github.com/oqtane/oqtane.framework/commit/6621983a9c85ced09973462931e2332fe1f44795)
ISSUE STILL EXISTS (Above Commits)


- [modify](https://github.com/oqtane/oqtane.framework/commit/b979203e12abbfd05140248b0526538ed07ab527) https://github.com/oqtane/oqtane.framework/pull/3528 [so that it only saves the ImagesFiles and UploadableFiles if they are different than the default - otherwise it sets them to blank. This provides forward compatibility if the default v…](https://github.com/oqtane/oqtane.framework/commit/b979203e12abbfd05140248b0526538ed07ab527)

I narrowed it down to this area of commits merged.

The first one the issue exists.
The second commit shown I cannot get past the file extension issue to see if it starts here since it wont allow uploading period.

One thing I noticed is the comma separated list (if I recall) looks like this:  .jpg,.png,.docx... with a period prior to extension.

This should be set and read like every other program that allows setting this type of setting:

`jpg,png,gif,pdf,docx` as the extra period makes it look harder to set these and read them.  We should sanitize this and use just the entered value shown in this example to set these.  Maybe I am wrong but I will take a quick look again to be sure and edit this with a screenshot of what is expected and how it looks currently.

Expected:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/28529623-d28b-404d-b8da-f42b711a1641)

I tried both ways on the second commit with no luck...

**Comment by lthoa** [comment] 2024-01-21 14:15
In database, SettingValue is empty after Site Setting page saved so upload is not allowed.
![image](https://github.com/oqtane/oqtane.framework/assets/6874322/5d5bab41-fc14-4906-8376-74da548a490f)

After add value into SettingValue by manual then upload succeed
![image](https://github.com/oqtane/oqtane.framework/assets/6874322/0c5d701e-749c-4341-bafc-f1f45839f388)

**Comment by eahughes3** [comment] 2024-01-21 14:20
Great troubleshooting! I was having the same issue and thought I was going crazy!

**Comment by sbwalker** [comment] 2024-01-21 14:44
@lthoa thank you for isolating the issue. The expected behavior is that the SiteSetting is supposed to be blank if you have not overridden the default constant value in the framework. However the upload method must not be handling the fallback properly when the SiteSetting is blank.

**Comment by sbwalker** [comment] 2024-01-21 16:25
The problem is with this line of code in FileController.cs:

```
            var _UploadableFiles = (_settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "UploadableFiles")?.SettingValue ?? Constants.UploadableFiles) ?? Constants.UploadableFiles;
```

The GetSetting() method will only return null if the setting was never set previously.... however after saving the Site Settings, the UploadableFiles setting does exist and contains a value of "" - so this logic will not fallback to using the Constants.UploadableFiles value (as it is only checking for null - not "").

**Comment by thabaum** [comment] 2024-01-21 18:00
So when you start a fresh site, you have 0 site settings, so it defaults OK and works as expected.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/69b2e7f6-cbb8-4a8b-956f-a288a3ac369a)

As soon as you save site settings is when it does not save the value inside that field shown, which I believe it should and it will catch all instances up to speed.  Lets say you want to lock down file uploads period, Oqtane should if it can and blank should do this.  If no setting is saved for this then it defaults to the constants.


![image](https://github.com/oqtane/oqtane.framework/assets/13577556/8c84f8a6-b7f1-4002-b1b4-c8561b78f4a0)

If this setting saved the defaults shown, it would be problem fixed as these would not be populated when any site setting is saved with the value shown to the user.

This would then work too fixing this issue.  Grab that default value shown below and be sure it is updated in site settings when saved.

I would like to have blank, and not allow any uploads too.  This is a powerful Host security feature I believe is maybe being overlooked?

So for a desired behavior:

- If No Site Setting Saved, Use Constants.
- If Site Setting Saved work with whatever a user sets, and if it is blank, no uploads are allowed.

Just catching up here to see what would be the best solution to drive towards.

**Comment by sbwalker** [comment] 2024-01-21 20:32
@thabaum the expected behavior of the file extensions has been documented previously and was explained at the previous Developer Meeting...

The only scenario where the SiteSetting should have a value is if an administrator modified the default framework setting (ie. they customized it). In all other cases it will either be null or empty string. 

This provides future compatibility in the case that  the framework adjusts the default value in the future - as long as a site has not specified their own custom value, it will inherit the latest default framework value. 

The only fix required is the logic identified above in the FileContoller.

**Comment by thabaum** [comment] 2024-01-21 20:52
@sbwalker there is some meat in there to chew on, review the parts about the media extension as well.  Should I put that part up in another issue?

**Comment by thabaum** [comment] 2024-01-21 23:02
I resolved the issue changing 2 lines of code in the Site\Index.razor file
```

                        // file extensions
                        // settings = SettingService.SetSetting(settings, "ImageFiles", (_ImageFiles != Constants.ImageFiles) ? _ImageFiles.Replace(" ", "") : "", false);
                        // settings = SettingService.SetSetting(settings, "UploadableFiles", (_UploadableFiles != Constants.UploadableFiles) ? _UploadableFiles.Replace(" ", "") : "", false);

                        // Check if _ImageFiles is null or empty, then use the constant
                        settings = SettingService.SetSetting(settings, "ImageFiles",
                            string.IsNullOrWhiteSpace(_ImageFiles) ? Constants.ImageFiles : _ImageFiles.Replace(" ", ""), false);

                        // Check if _UploadableFiles is null or empty, then use the constant
                        settings = SettingService.SetSetting(settings, "UploadableFiles",
                            string.IsNullOrWhiteSpace(_UploadableFiles) ? Constants.UploadableFiles : _UploadableFiles.Replace(" ", ""), false);

```

Resolves all issues relating and provides constants.cs support.  Shall I submit a pull request?

**Comment by sbwalker** [comment] 2024-01-22 00:19
@thabaum this is not the correct fix. I already explained the expected behavior and the line of code which needs to be modified to address this issue.

**Comment by thabaum** [comment] 2024-01-22 01:52
@sbwalker I did re-evaluate what you said and did come up with a solution editing the following that may help fine tune this a little quicker.  I will close my other PR.

Line 291
```
           var _UploadableFiles = (_settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "UploadableFiles")?.SettingValue ?? Constants.UploadableFiles) ?? Constants.UploadableFiles;

changed to: 

           var uploadableFilesSettingValue = _settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "UploadableFiles")?.SettingValue;
           var _UploadableFiles = !string.IsNullOrEmpty(uploadableFilesSettingValue) ? uploadableFilesSettingValue : Constants.UploadableFiles;

```
Line About 369
```
            // Get the UploadableFiles extensions
            string uploadfilesSetting = _settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "UploadableFiles")?.SettingValue;
            string _UploadableFiles = uploadfilesSetting ?? Constants.UploadableFiles;

Changed to:

            // Get the UploadableFiles extensions
            string uploadableFilesSettingValue = _settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "UploadableFiles")?.SettingValue;
            string _UploadableFiles = !string.IsNullOrEmpty(uploadableFilesSettingValue) ? uploadableFilesSettingValue : Constants.UploadableFiles;
```
Line About 617
```
            var _ImageFiles = (_settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "ImageFiles")?.SettingValue ?? Constants.ImageFiles) ?? Constants.ImageFiles;

changed to:

            // Get the ImageFiles extensions
            string imageFilesSettingValue = _settingRepository.GetSetting(EntityNames.Site, _alias.SiteId, "ImageFiles")?.SettingValue;
            string _ImageFiles = !string.IsNullOrEmpty(imageFilesSettingValue) ? imageFilesSettingValue : Constants.ImageFiles;

```

I believe this would of been accepted... my apologies on the confusion.

**Closed** 2024-01-22 13:24 UTC
