### ISSUE TITLE
Bug: Exception throw when close admin dashboard

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#3909] opened 2024-02-27 14:00 UTC
Reproduce Steps:
1. build the latest code (up to commit #f017b6b92fd2ab841465f9f5a4f15c9f719c7f73) and install a new instance.
2. login as super user, open admin dashboard.
3. click the X button to close the dashboard.

Expected Result:
the dashboard should be closed.

Actually Result:
Exception thrown:
![2024-02-27_215756](https://github.com/oqtane/oqtane.framework/assets/3364448/b2ec9317-a508-4fb0-b52f-ed550232887b)

**Comment by sbwalker** [comment] 2024-02-27 14:14
@zyhfish this is a known problem and is caused by Blazor in Static rendering. The recommendation from Microsoft is to configure Visual Studio to not break on this type of exception. See this issue: https://github.com/dotnet/aspnetcore/issues/53996

**Comment by sbwalker** [comment] 2024-02-27 17:38
@zyhfish so the problem is that even if you catch the exception in code, the NavigationManager will fail to redirect to the desired Url:

```
using Microsoft.AspNetCore.Components;

namespace Oqtane.Extensions
{
    public static class NavigationManagerExtensions
    {
        public static void NavigateToIgnoreException(this NavigationManager navigationManager, string uri, bool forceLoad = false, bool replace = false)
        {
            try
            {
                navigationManager.NavigateTo(uri, forceLoad, replace);
            }
            catch
            {
                // ignore exception thrown in static rendering within debugger
            }
        }
    }
}
```

and you change the AdminContainer.razor

```
	private void CloseModal()
	{
		NavigationManager.NavigateToIgnoreException((!string.IsNullOrEmpty(PageState.ReturnUrl)) ? PageState.ReturnUrl : NavigateUrl());
    }
```

You will not be redirected to the desired location. It seems that the only way to deal with this currently is to suppress the error in Visual Studio and then it will work as expected.

**Comment by sbwalker** [comment] 2024-02-27 17:47
Closing as there is no solution in .NET 8

**Closed by sbwalker** 2024-02-27 17:47 UTC
