### ISSUE TITLE
Creating sub site[BUG] 

### ISSUE THREAD

**Issue by rollsr1** [oqtane/oqtane.framework#4463] opened 2024-07-24 08:10 UTC
### Oqtane Info

Version -5.1.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Clean new install of database and Oqtane latest code. No problem.
Add a new site which I want for admin with a different theme pipsqweek.oqtane.me/admin which builds okay

When i go into the site settings of the subsite i get an error on save.
![sitesaveerror](https://github.com/user-attachments/assets/b14015d7-340a-4f2e-90fa-08953f915dd7)

**Comment by sbwalker** [comment] 2024-07-24 12:13
@rollsr1 I am unable to reproduce this issue in the Dev branch (5.2.0). This could mean it has already been resolved... or it could mean that you have not provided the exact series of steps to reproduce the problem. When you navigated to Site Settings in Site2, what fields did you modify before clicking Save?

**Comment by rollsr1** [comment] 2024-07-24 12:32
Where can i download (5.2.0) I only have access to 5.1.2
When i navigate to site settings, I am changing the theme to a bootswatch cereluan  from the standard Oqtane and saving.
________________________________

**Comment by sbwalker** [comment] 2024-07-24 12:34
5.2.0 has not been released yet - the code is in the Dev branch in the GitHub repo. I will try to change the theme in the sub-site to determine if I can reproduce the problem.

**Comment by sbwalker** [comment] 2024-07-26 19:25
@rollsr1 please verify if this is resolved in the 5.2.0 release, as I cannot reproduce

**Comment by rollsr1** [comment] 2024-07-27 04:26
Installed  5.2.0 and the bug is fixed. Thank you. 🙂
________________________________

**Closed** 2024-07-27 13:42 UTC
