### ISSUE TITLE
using oqtane with 3party components Syncfusion

### ISSUE THREAD

**Issue by mundl21** [oqtane/oqtane.framework#372] opened 2020-04-14 19:26 UTC
Just installed latest oqtane realease from today and latest Syncfusion Blazor release 18.1.44 from today. Following exactly getting started instructions. Oqtane starts, but strange behaviour. Login and Logout impossible, Content only partly visible. Controlpanel could not be  opened.
No Syncfusion Control is used….

In VS Studio 2019 preview 16.6. Shows following error message:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.ThemeService.GetThemesAsync() in C:\Users\rhopp\Documents\Visual Studio 2019\preview_16\oqtane.framework-master_ori\oqtane.framework-master\Oqtane.Client\Services\ThemeService.cs:line 33
   at Oqtane.Themes.Controls.ControlPanel.OnParametersSetAsync() in C:\Users\rhopp\Documents\Visual Studio 2019\preview_16\oqtane.framework-master_ori\oqtane.framework-master\Oqtane.Client\Themes\Controls\ControlPanel.razor:line 282
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

Strange. In older releases it worked without any restriction.
Can you please help?
Thanks

**Comment by sbwalker** [comment] 2020-04-14 20:37
when you say "installed latest Oqtane release" are you saying that you pulled that latest source code from the repo, or downloaded a release package?

**Comment by sbwalker** [comment] 2020-04-14 20:51
Based on the error message you posted, it is throwing a 401 Unauthorized when it is calling the Get method on the ThemeController. The security requirements when making this call are that the user must be authenticated and also be in the Registered Users role. I am not sure how Oqtane could be attempting to make this call as it should never occur unless the user is already logged in. Have you done any customizations to the installation?

**Comment by mikecasas** [comment] 2020-04-14 21:40
One suggestion, try clearing your browser cookies/passwords for localhost. This looks similar to an issue I had where I had installed oqtane many times and used different passwords for the host user. The browser had cached an old password and was throwing the 401's.

**Comment by mundl21** [comment] 2020-04-15 09:01
Hi Shawn,
i have downloaded here. See screenshot.
![image](https://user-images.githubusercontent.com/7481435/79319208-50c86e00-7f08-11ea-919b-9730d1438815.png)

**Comment by mundl21** [comment] 2020-04-15 09:16
no customizations. Running as server project)

added only (following Synfusion getting started instructions)

in startup.cs (Server)

public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddNewtonsoftJson();
            services.AddServerSideBlazor();
            **services.AddSyncfusionBlazor();**

in host.cshtml
 <link rel="stylesheet" href="https://cdn.syncfusion.com/blazor/18.1.44/styles/bootstrap4.css" />

**Comment by mundl21** [comment] 2020-04-15 09:17
<link rel="stylesheet" href="https://cdn.syncfusion.com/blazor/18.1.44/styles/bootstrap4.css" />

**Comment by mundl21** [comment] 2020-04-15 09:17
link rel="stylesheet" href="https://cdn.syncfusion.com/blazor/18.1.44/styles/bootstrap4.css"

**Comment by mundl21** [comment] 2020-04-15 09:30
cleared browser cookies/passwords for localhost…
Not successfull...

**Comment by sbwalker** [comment] 2020-04-15 16:57
@mundl21 I would suggest putting a breakpoint in Oqtane.Client\UI\SiteRouter.razor at the top of the Refresh() method and step through line by line to see what is happening.

**Comment by mundl21** [comment] 2020-04-16 11:53
hi shawn
done that. By the way. We're happy with oqtane, hoping this issue can solved. Thx in Advance.

result:
a) not registered user (without login) all works as expected.

b) Trying to log in with user "host" (no other user is added)

- Call the Usercontroller with above data is working
- the next action to use the ControlPanel (row 264)
            var themes = await ThemeService.GetThemesAsync();
- ThemeService tries to call ThemeController. This call results in error:

Ausnahme ausgelöst: "System.Net.Http.HttpRequestException" in System.Private.CoreLib.dll
"iisexpress.exe" (CoreCLR: clrhost): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Diagnostics.StackTrace.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"iisexpress.exe" (CoreCLR: clrhost): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Reflection.Metadata.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"iisexpress.exe" (CoreCLR: clrhost): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.IO.MemoryMappedFiles.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Response status code does not indicate success: 401 (Unauthorized).

System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.ThemeService.GetThemesAsync() in C:\oqtane\Oqtane.Client\Services\ThemeService.cs:line 33
   at Oqtane.Themes.Controls.ControlPanel.OnParametersSetAsync() in C:\oqtane\Oqtane.Client\Themes\Controls\ControlPanel.razor:line 264
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'g38hWqaiL-o8aGar-vJxCZujjYqxNAO2cwmpY9t2Vls'.

System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.ThemeService.GetThemesAsync() in C:\oqtane\Oqtane.Client\Services\ThemeService.cs:line 33
   at Oqtane.Themes.Controls.ControlPanel.OnParametersSetAsync() in C:\oqtane\Oqtane.Client\Themes\Controls\ControlPanel.razor:line 264
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)


![Screenshot (16)](https://user-images.githubusercontent.com/7481435/79453233-afb1e400-7fe9-11ea-96a7-cec82faba9c6.png)

**Comment by chlupac** [comment] 2020-04-16 13:27
Is this bug related to syncfusion ? I'm not able to reproduce it.

**Comment by sbwalker** [comment] 2020-04-16 13:41
Yes, it definitely seems to be related to SyncFusion as that is the only difference in @mundl21's environment. @mundl21 if you are getting a 401 unauthorized error from the API controller method then it either means the server does not think you are authenticated or your user account is not a member of the Host Role. I assume this is a clean install ( ie. you created a new database as part of your installation ). If so then you can check the Role table in your DB and looks for the Host Users role - and then check that the Host user is a member of the Host Role in your UserRole table.

**Comment by chlupac** [comment] 2020-04-16 13:49
I'm afraid if i'ts not a bug in last services refactoring.

**Comment by sbwalker** [comment] 2020-04-16 13:50
It was happening before the services refactoring was added to the repo

**Comment by mundl21** [comment] 2020-04-16 14:49
Thx.
your assumption is correct. New clean install. Roles and users checked. Ok. 
Is still strange. In older releases of both it worked without any restriction.
Will additionally contact syncfusion. Thx.

**Comment by sbwalker** [comment] 2020-04-16 14:51
@mundl21 are you running under Blazor Server or Blazor WebAssembly?

**Comment by mundl21** [comment] 2020-04-16 15:06
running under Blazor Server

**Comment by chlupac** [comment] 2020-04-16 15:55
I have working Syncfusion 18.1.44 under oqtane
https://blazor.syncfusion.com/documentation/getting-started/server-side-blazor/

**Comment by chlupac** [comment] 2020-04-16 15:58
![image](https://user-images.githubusercontent.com/7838468/79478410-ab96be00-800b-11ea-8dc5-bac8a0d1c777.png)

**Comment by chlupac** [comment] 2020-04-16 15:59
your error is not syncfusion related

**Comment by chlupac** [comment] 2020-04-16 16:40
![image](https://user-images.githubusercontent.com/7838468/79482889-c4a26d80-8011-11ea-8557-dd41d99e18cf.png)

**Comment by chlupac** [comment] 2020-04-16 16:45
https://github.com/chlupac/oqtane.framework/tree/Syncfusion
working example here, add weather module to page

**Comment by mundl21** [comment] 2020-04-16 18:23
thx. Will try and inform

**Comment by mundl21** [comment] 2020-04-16 19:41
Many, many thanks to you, especially to @chlupac !
Little change, with big impact.
Everything running now again. 
THX.
a happy Oqtane user..

**Comment by chlupac** [comment] 2020-04-16 19:46
where is problem ?

**Comment by sbwalker** [comment] 2020-04-16 21:38
I am going to close this issue but @mundl21 it would be very much appreciated if you could explain the cause of the issue

**Closed by sbwalker** 2020-04-16 21:38 UTC

**Comment by mundl21** [comment] 2020-04-17 08:40
i'm very happy to explain it. Maybe chlupac can deliver more detailed information.
I'm only changed in startup.cs the Position 
services.AddSyncfusionBlazor();
from line 48 to line 208.

This is the solution…
Again thx.
