### ISSUE TITLE
[BUG] RichTextEditor content is always empty and can't be saved for rich text mode

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4134] opened 2024-04-12 09:14 UTC
### Oqtane Info

Version - 5.1.0 (latest dev branch)
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

Rich Text Editor content is always empty after the new _initialize property was added to resolve https://github.com/oqtane/oqtane.blogs/issues/44 (error that I was also facing).

Here's a sample demo video in the latest dev branch where it can be seen that the content for Rich Text mode is empty, while the RawHtml is fine.

[richTextEmpty.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/2082f166-0de9-494e-8b2d-d6e387eedbcc)

I debugged RichTextEditor component and the branch inside the _initialized condition is never accessed, so ```await interop.LoadEditorContent(_editorElement, _richhtml);``` is never called and the content is empty.

```c#
if (_initialized)
{
    if (!_richfilemanager) // do not override the content when the file manager is displayed
    {
        await interop.LoadEditorContent(_editorElement, _richhtml);
    }

    if (string.IsNullOrEmpty(_originalrichhtml))
    {
        // preserve a copy of the rich text content (Quill sanitizes content so we need to retrieve it from the editor as it may have changed)
        _originalrichhtml = await interop.GetHtml(_editorElement);
    }
}
```

Also, new content is not saved (always empty) when in RichText mode but is saved when written in raw html. Here's another sample video:

[richTextNotSaved.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/6cea4238-5a64-4444-8b2d-dc57ed128057)

I believe I've traced it to this condition of the GetHtml method, where if the _originalrichhtml is empty because we are actually writing it for the first time, it immediately returns the _originalrichhtml, which is obviously empty. I've debugged it and richhtml did actually contain the desired value, but it returns the empty original one.
```c#
// rich text value will only be blank if AllowRichText is disabled or the JS Interop method failed
if (richhtml != _originalrichhtml && !string.IsNullOrEmpty(richhtml) && !string.IsNullOrEmpty(_originalrichhtml))
{
	return richhtml;
}
else
{
	// return original raw html content
	return _originalrawhtml;
}
```

Lastly, inserting images in rich mode is still displaying some weird behaviour even after fixing https://github.com/oqtane/oqtane.framework/issues/4108. In this case, the content is not lost when the image is inserted, it's lost when the FileManager is closed without inserting an image.

Here's a sample video:

[closingRichFileManager.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/6e7f88e5-a41b-472b-bbc1-c7525b760c38)

### Expected Behavior

RichText mode should load and save content properly.

### Steps To Reproduce

Test all the issues I reported in the latest dev branch with the Oqtane HtmlText modules in the home page.

**Comment by sbwalker** [comment] 2024-04-12 11:49
I will investigate. JS Interop is very challenging because it often behaves differently depending on the environment ie. race conditions are dependent on the speed of the environment

**Comment by mdmontesinos** [comment] 2024-04-12 17:03
I understand. I actually thought it was an issue in my custom component that uses a Rich Text Editor, but I tried that default Html/Text modules and got the same behaviour.

By the way, were you able to reproduce?

**Comment by sbwalker** [comment] 2024-04-12 17:13
@mdmontesinos yes I was able to reproduce. I have been fighting to try to get all of the known use cases to work properly for the past 3 hours :(

**Comment by sbwalker** [comment] 2024-04-12 17:30
@mdmontesinos please test #4137 to verify it resolves the issues (I did my own testing of various scenarios but since this component seems to exhibit different behavior in different environments I can never be 100% certain)

**Comment by sbwalker** [comment] 2024-04-12 18:34
@mdmontesinos there is still one more problem which I am working on.... if you have provided HTML content which the Quill editor does not support ie. ```<div>Test</div>``` and then open the editor and hit Save, the content will be removed because Quill has sanitized it.

**Comment by mdmontesinos** [comment] 2024-04-12 18:45
@sbwalker All the issues I reported previously seem to be fixed now and it's working just fine.

The only thing I noticed is that an empty rich text is converted into ```<p><br></p>``` when saved. Is that the expected behaviour? I was previously validating the output in a form by checking if it was null or empty and it worked fine (before the issues I reported). I can just validate checking for that specific string, but I want to be sure that is intended.

**Comment by sbwalker** [comment] 2024-04-12 18:49
@mdmontesinos that is a behavior of the QuillJS JavaScript editor - so yes, it is expected behavior. The QuillJS editor has a lot of other quirks as well ie. it does not support all HTML elements

**Comment by sbwalker** [comment] 2024-04-12 19:03
@mdmontesinos please test again with #4139 as it handles an additional scenario.

**Comment by sbwalker** [comment] 2024-04-12 19:12
@mdmontesinos you can test #4140 as well which converts Quill's empty content ```<p><br></p>``` to empty string. It seems to have no side effects to the other scenarios.

**Comment by mdmontesinos** [comment] 2024-04-13 16:40
@sbwalker I've tested it again and it seems to still be displaying some weird behaviour...

I have validation that verifies that the RichText is not empty but when trying to save it with empty content, it writes back the previous content I deleted. Validation is working fine and the message displays, so the GetHtml call is actually returning an empty string, but somewhere in the code it's writing again the previous content in the RichTextEditor, even for another RichTextEditor that was not empty but still modified.

Here's the code of the validation part:

```c#
string lead = await _leadRichTextEditor.GetHtml();
string content = await _contentRichTextEditor.GetHtml();
News.Lead = Utilities.FormatContent(lead, PageState.Alias, "save");
News.Content = Utilities.FormatContent(content, PageState.Alias, "save");

editContext.NotifyValidationStateChanged();

if (!editContext.Validate())
{
    AddModuleMessage("Please Provide All Required Information", MessageType.Warning);
    return;
}
```

Also, and I suppose it's related to this, in the video you can see for a few frames after successfully saving that the previous content appears on the RichTextEditors although the modified content is correctly saved.

Here's the sample video:

[screen-capture (1).webm](https://github.com/oqtane/oqtane.framework/assets/90258222/bf9a8d46-7927-4b08-9521-0e6875b6f02f)

**Comment by sbwalker** [comment] 2024-04-15 00:57
@mdmontesinos I am not sure if the RichTextEditor has ever supported the ability to have multiple component instances on the same page… as it does not set a unique id for each instance which the JS Interop methods could reference. I would need to investigate this further.

**Comment by leigh-pointer** [comment] 2024-04-15 01:24
My module Dynamic Form can have multiple RichTextEditors.

![RichTextEditors](https://github.com/oqtane/oqtane.framework/assets/9447612/502a61e5-f88f-4818-91c9-4c58c45f7cb0)

**Comment by mdmontesinos** [comment] 2024-04-15 07:44
@sbwalker Same behaviour is displayed with a single RichTextEditor

**Comment by mdmontesinos** [comment] 2024-04-15 13:08
@sbwalker Same behaviour as the one shown in the last video. I pulled the latest changes and rebuilt the whole Oqtane solution just in case.

**Comment by sbwalker** [comment] 2024-04-15 13:11
@mdmontesinos are you able to reproduce in the Html/Text module? I am having a hard time understanding why I cannot reproduce some of these behaviors in the Html/Text or Blog modules

**Comment by sbwalker** [comment] 2024-04-15 13:49
@mdmontesinos in order to reproduce your latest scenario it appears that I would need to create a custom module with 2 editor fields which are configured a specific way (ie. Raw HTML editor is disabled, etc...) and includes some sort of validation logic. It makes it next to impossible to track down issues when they are so specific and difficult to reproduce.

**Comment by mdmontesinos** [comment] 2024-04-15 14:04
@sbwalker I'm going to test the Html/Text module and also try to provide a minimal module that reproduces this behaviour so I can pack it and send it, if that's alright for you.

**Comment by mdmontesinos** [comment] 2024-04-15 15:18
@sbwalker I believe I've located where the issue is coming from.

The Content parameter of the RichTextEdit seems to not be updated when the editor changes (like two-way binding) but this goes unnoticed in the Html/Text module because execution of the Save method navigates back to the Index page unless an exception ocurrs. In my case, the execution of this method is interrupted by the validation, in which case the inner html of the RichTextEdit was changed but not the Content parameter. Therefore, it seems to rerender the UI with the value of the Content parameter which ends up displaying the previous text, whilst my model text is indeed updated. This is also why you can see a flash of the previous text when the form is correctly saved.

This is the SaveContent method in HtmlText module, in which you can see that _content is not updated, it creates a local content variable:

```c#
private async Task SaveContent()
{
	string content = await RichTextEditorHtml.GetHtml();
	content = Utilities.FormatContent(content, PageState.Alias, "save");

	try
	{
		var htmltext = new HtmlText();
		htmltext.ModuleId = ModuleState.ModuleId;
		htmltext.Content = content;
		await HtmlTextService.AddHtmlTextAsync(htmltext);

		await logger.LogInformation("Content Saved {HtmlText}", htmltext);
		NavigationManager.NavigateTo(NavigateUrl());
	}
	catch (Exception ex)
	{
		await logger.LogError(ex, "Error Saving Content {Error}", ex.Message);
		AddModuleMessage(Localizer["Error.Content.Save"], MessageType.Error);
	}
}
```

To "solve" this, I need to reset the Content parameter of both RichTextEditors (in this case _lead and _content) and also explicitly  call StateHasChanged so that it refreshes the UI.

This would be the new version in my module:

```c#
_lead = await _leadRichTextEditor.GetHtml();
_content = await _contentRichTextEditor.GetHtml();
News.Lead = Utilities.FormatContent(_lead, PageState.Alias, "save");
News.Content = Utilities.FormatContent(_content, PageState.Alias, "save");

editContext.NotifyValidationStateChanged();

StateHasChanged();

if (!editContext.Validate())
{
    AddModuleMessage("Please Provide All Required Information", MessageType.Warning);
    return;
}
```

And this was the previous version:
```c#
string lead = await _leadRichTextEditor.GetHtml();
string content = await _contentRichTextEditor.GetHtml();
News.Lead = Utilities.FormatContent(lead, PageState.Alias, "save");
News.Content = Utilities.FormatContent(content, PageState.Alias, "save");

editContext.NotifyValidationStateChanged();

if (!editContext.Validate())
{
    AddModuleMessage("Please Provide All Required Information", MessageType.Warning);
    return;
}
```

Still, this "solution" seems to be glitchy and the UI flashes a bit when trying to save. Perhaps there should be a way to update the Content parameter when calling GetHtml or similar methods inside the RIchTextEditor.

[screen-capture.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/f22e4799-52f3-434d-a2e7-d71cfcc9e7b6)

**Comment by sbwalker** [comment] 2024-04-15 20:53
I mentioned above that I am unable to reproduce the latest behavior as there is no use case within the framework which utilizes the component in the way your custom module uses it. I am going to close this issue as completed as I believe it resolves the original issue which was reported - and does not introduce any new regression issues in the various use cases described(ie. Html/Text module, Blog module, etc...)

**Closed by sbwalker** 2024-04-15 20:53 UTC

**Comment by mdmontesinos** [comment] 2024-04-17 11:03
@sbwalker I was finally able to replicate the issue in the Html/Text module. In the end, it had nothing to do with my validation. The issue occurs when you add a custom ToolbarContent to the RichTextEditor.

To replicate, simply replace the current RichTextEditor in the Html/Text module with:
```razor
<RichTextEditor Content="@_content" AllowFileManagement="@_allowfilemanagement" AllowRawHtml="@_allowrawhtml" @ref="@RichTextEditorHtml">
    <ToolbarContent>
        <select class="ql-header">
            <option selected=""></option>
            <option value="1"></option>
            <option value="2"></option>
            <option value="3"></option>
            <option value="4"></option>
            <option value="5"></option>
        </select>
        <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-italic"></button>
            <button class="ql-underline"></button>
            <button class="ql-strike"></button>
        </span>
        <span class="ql-formats">
            <select class="ql-color"></select>
            <select class="ql-background"></select>
        </span>
        <span class="ql-formats">
            <button class="ql-script" value="sub"></button>
            <button class="ql-script" value="super"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-header" value="1"></button>
            <button class="ql-header" value="2"></button>
            <button class="ql-blockquote"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
            <button class="ql-list" value="check"></button>
            <button class="ql-indent" value="-1"></button>
            <button class="ql-indent" value="+1"></button>
        </span>
        <span class="ql-formats">
            <button class="ql-link"></button>
            <button class="ql-clean"></button>
        </span>
    </ToolbarContent>
</RichTextEditor>
```

It basically adds some new other format options for the Quill toolbar, but they shouldn't require any extra configuration.

EDIT: Upon further testing, I realized that it doesn't matter what options you set in the toolbar. Just by specifying a custom toolbar the issue will occur.

You should see this behaviour, in which it's clearly seen that the content is written again to the editor when saving. In this case it seems just like a UI issue, but if the execution is stopped due to any error/validation before navigating back, you would stay with the previous content, like in the videos I reported before.

[screen-capture.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/af2ae2c0-efef-471a-80e0-52e24bd4d388)

If needed, I can provide a sample minimal module with validation, when the issue really shines.

**Comment by mdmontesinos** [comment] 2024-04-19 12:11
If possible, please reopen now that the issue is easily replicated in Html/Text module. Also, I can open a new issue if needed to separate it from the previous ones.

**Comment by sbwalker** [comment] 2024-04-19 16:56
@mdmontesinos I think it would be better to create a new issue related to the custom toolbar - as this is related to customizing the editor and not part of the default functionality.

**Comment by mdmontesinos** [comment] 2024-04-19 17:17
Issue opened at #4160.
