### ISSUE TITLE
[BUG] Changes in Hash of URL through JS Broken because of enhanced navigation

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4387] opened 2024-07-03 13:28 UTC
### Oqtane Info

Version - 5.1.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

We have an application showing a bootstrap accordion to open/close certain sections. 
The mechanism also adds a `#sectionName` to the url, so that anybody sharing the link would end up opening/closing the same section when they revisit the page. 

In Oqtane - at least SSR - this results in random behavior. This is what happens:

1. user clicks
2. section unfolds as expected
3. [probably] enhanced navigation detects a url change (even though it's behind the `#` which shouldn't concern it)
4. [almost certainly] enhanced navigation triggers a page visit (on the existing page)
5. browser does a fetch request
6. page gets reset to show the section collapsed again

Here's a gif-video showing the behavior:

![oqtane-issue-accordion](https://github.com/oqtane/oqtane.framework/assets/5321186/04aa023c-47a8-456f-8c95-0e96ccee2e63)

And here a print-screen of the fetch operation which shouldn't have happened:

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/53df10ca-72e8-46db-922e-f5a2e1938838)

1. was the original page F5
2. secret unwanted fetch
3. another unwanted fetch

### Expected Behavior

1. Any link which doesn't change the real url should not trigger the enhanced navigation - especially if it just modifies the `#` parameter. 
2. ...unless really wanted - e.g. if a script explicitly wants to reload the page (not sure how this is done, but it would be more than just a link)

### Steps To Reproduce

A bit tricky, but basically create a bootstrap accordion on a page and try to use it.

**Comment by sbwalker** [comment] 2024-07-03 14:22
@iJungleboy the "Frequently Asked Questions" on https://www.oqtane.org is using Bootstrap accordions - and they function just fine.

**Comment by iJungleboy** [comment] 2024-07-03 17:48
@sbwalker these don't "remember" the section that was opened. 

I just found an issue on Blazor which indicates this is fixed in 8.0.3 https://github.com/dotnet/aspnetcore/issues/52583

But that is strange, because it's till in Oqtane...?

**Comment by sbwalker** [comment] 2024-07-03 18:17
I have no idea... you would need to investigate further to try and identify the problem.

**Comment by iJungleboy** [comment] 2024-07-04 05:21
@sbwalker the area opens, but at the same time Oqtane / "enhanced navigation" performs a fetch and the server HTML returned doesn't know about `#` values in the url, so of course the server returns the "collapsed" html. 

So a moment later the opened accordion is replaced by enhanced navigation with the original HTML.

The problem is because enhanced navigation is reacting to plain `#` value changes in the URL which it should not, according to https://github.com/dotnet/aspnetcore/issues/52583. 

Is it possible that blazor fixed this, but that Oqtane is still including an older blazor-js file from a previous version of .net?

**Comment by iJungleboy** [comment] 2024-07-10 13:45
I did some more research to create a minimum viable bug.

1. Configure system to be SSR
2. Place an Oqtane HTML module on your page and add the text below in the pure-HTML mode

```html
<p>Demo links</p>
<p><br /></p>
<ul>
  <li><a href="/admin">/admin</a> - should work and soft-load ✅</li>
  <li><a href="#test">#test</a> - should not do any soft reload ✅</li>
  <li>
    <a href="javascript:window.location.hash='testJs'"
      >JS link going to #test</a
    >
    - should not trigger soft-reload 🚫
  </li>
</ul>
```

You should see this after saving: 

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/b922f096-d32b-46fd-b3d4-fdca5591b6fc)

After this, clicking on the simple js-link which sets the hash to `#testJs` completely destroys the page, connection, everything...even though by any standard it should just scroll down to the right place. You can also see that it tried to do a fetch (which it really shouldn't) and then terminated itself.

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/8b92223b-8f70-44ff-83e2-20f20a3d8075)

**Comment by iJungleboy** [comment] 2024-07-11 07:39
I'm leaving to Africa for our charity 2givelife.org for the next 4 weeks, so I cannot do this for a while. 

Would appreciate if anybody else in the community could tackle this.

**Comment by sbwalker** [comment] 2024-07-11 12:52
@iJungleboy your minimal repro has nothing to do with Bootstrap Accordions - it has to do with fragment/anchor processing on Urls - should I change the title of this issue to reflect the actual issue?

**Comment by sbwalker** [comment] 2024-07-11 13:13
@iJungleboy please note that when using Blazor Static Rendering in .NET 8 there are a variety of well documented problems related to browser scroll position as you navigate from page to page, which are caused by Enhanced Navigation. I believe Microsoft is targeting a fix for .NET 9 however I have not actually verified if it is fixed in any of the beta releases yet. 

For applications relying on .NET 8, developers had to come up with their own solutions. In Oqtane 5.1 a solution was included which injects a custom script into the page if a site is using static rendering - you can see it if you browse to https://www.oqtane.org and do a view source in the browser and scroll to the bottom:

```
<script>
    // Blazor Static Rendering Scroll Position
    window.interceptNavigation = () => {
        let currentUrl = window.location.href;
        Blazor.addEventListener('enhancedload', () => {
            let newUrl = window.location.href;
            if (currentUrl != newUrl) {
                window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
            }
            currentUrl = newUrl;
        });
    };
    document.onload += window.interceptNavigation();
</script>
```
This script does fix the scroll position behavior so that it is consistent with what users expect for standard web applications. However it is possible that it impacts Url fragment/anchor behavior. This is just an idea, but it might be worth investigating further.

**Comment by sbwalker** [comment] 2024-07-11 17:40
@iJungleboy also see #4312 related to anchor links on home page

**Comment by iJungleboy** [comment] 2024-07-11 20:12
Just fyi: I currently "fixed" it by disabling enhanced navigation using the 

```html
<div data-enhance-nav="false">
...
</div>
```

trick. So for me I guess it's not so important any more, but I think a lot of people will waste a lot of time on this.

Hope .net 9 gets this figured out, it wouldn't be hard to fix.

If you want to close this it's fine with me.

**Comment by zyhfish** [comment] 2024-08-15 11:29
Hi @iJungleboy ,
maybe this is the same issue as I mentioned in #4312, because the base url always set to the website root, the anchor links won't work and will trigger http requests to the server. you can remove the bass tag to verify whether it can avoid the issue.

unfortunately I don't have any nice solution for it, currently the workaround is append the full page url to the anchor link to make it work.

**Comment by sbwalker** [comment] 2024-08-26 23:57
@iJungleboy please try this in 5.2.1 as there was a change made to the scroll position logic so that it no longer resets the position to the top of the page when only the hash or querystring changes.

**Comment by sbwalker** [comment] 2024-09-18 12:40
@iJungleboy I verified that this does not work properly in Blazor - so it is not an Oqtane problem. I added the scenario to the Black Belt Blazor project: https://github.com/devessenceinc/BlackBeltBlazor

**Closed by sbwalker** 2024-09-18 12:40 UTC

**Comment by iJungleboy** [comment] 2024-09-18 14:36
@sbwalker thanks for following up on this

**Comment by sbwalker** [comment] 2025-01-15 19:07
@iJungleboy note that Microsoft just hosted a Community Standup for Blazor for .NET 10 this week and they mentioned that "hashed routing" is not in scope (same with "nested" routing which Oqtane already supports). I believe this feature was first requested for Blazor back in 2017... so at this point it seems like it never will be supported.
