### ISSUE TITLE
How to set-up after clone?

### ISSUE THREAD

**Issue by Bitexirtz** [oqtane/oqtane.framework#151] opened 2019-10-23 05:02 UTC
I tried the following:
1. clone this repo
2. open sln file (just open)
   default: Debug | Any CPU | Oqtane.Server
3. build
4. hit F5
http://localhost:44357/ is opened but nothing is displayed? (But title displayed is oqtane.)
What am I missing?

**Comment by ADefWebserver** [comment] 2019-10-23 11:46
Ensure you have installed:

- Microsoft Windows 7 Service Pac 1 (or higher) or Microsoft Widows Server 2012 R2 Service Pac 1 (or higher)
- Visual Studio 2019 Version 16.3 (or higher) (Free download from: https://visualstudio.microsoft.com/free-developer-offers/)
- .NET Core 3.0.0 SDK (or higher) (Free download from: https://dotnet.microsoft.com/download/dotnet-core/3.0)


See: [What is Blazor Oqtane?](http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4359/What-is-Blazor-Oqtane.aspx)  Start with the section: Getting Started With Oqtane. 

Ensure you are opening the project in Visual Studio 2019 (or higher).

**Comment by fileman** [comment] 2019-10-23 17:03
I think something was broken in last commit.
I can successfully install only if I comment out Authorize attribute in TenantController
```
 // GET: api/<controller>
 [HttpGet]
 //[Authorize(Roles = Constants.HostRole)]
 public IEnumerable<Tenant> Get()
 {
     return Tenants.GetTenants();
 }
```

**Comment by ADefWebserver** [comment] 2019-10-23 17:28
@fileman - Thanks! @sbwalker knows what the issue is here. This is related to another issue we discussed last night. He will fix it. @Bitexirtz we apologize for the inconvenience. We should have this fixed in the next day or so. In the future we will have "install packages" that would be tested.

**Comment by sbwalker** [comment] 2019-10-23 19:12
I rolled back the Authorize attribute change to allow the installer to work correctly.

**Closed by sbwalker** 2019-10-23 19:12 UTC

**Comment by Bitexirtz** [comment] 2019-10-23 22:59
I tried again same procedure as above. Sorry but same problem.

**Comment by ADefWebserver** [comment] 2019-10-23 23:43
> I tried again same procedure as above. Sorry but same problem.

@Bitexirtz - Please open startup.cs and change:

`services.AddServerSideBlazor();`

to:

`services.AddServerSideBlazor().AddCircuitOptions(options => { options.DetailedErrors = true; });`

Then use Google Chrome and hit the F12 button to open the Developer Console and please copy and paste everything that is in the console. Thank You

**Comment by Bitexirtz** [comment] 2019-10-24 01:18
Please see logs below.

blazor.server.js:1 [2019-10-24T01:15:13.214Z] Information: Normalizing '_blazor' to 'http://localhost:44357/_blazor'.
blazor.server.js:1 [2019-10-24T01:15:13.279Z] Information: WebSocket connected to ws://localhost:44357/_blazor?id=8m5T1pfV3tqhixfpfMw3_w.
blazor.server.js:15 [2019-10-24T01:15:15.402Z] Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.InstallationService.IsInstalled() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\Services\InstallationService.cs:line 31
   at Oqtane.Client.App.OnParametersSetAsync() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\App.razor:line 26
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
e.log @ blazor.server.js:15
blazor.server.js:1 [2019-10-24T01:15:15.403Z] Information: Connection disconnected.

**Comment by sbwalker** [comment] 2019-10-24 01:37
Can you please open the appsettings.json file in the root of the Oqtane.Server project and remove the connectionstring:

{
  "ConnectionStrings": {
    "DefaultConnection": ""
  }
}

Then make sure you have the latest code from the repo and rebuild it, and then run the application and you should see the installation page where you can specify your database details as well as the password and email to be used for your initial user account.

I think the previous issue you ran into related to the tenant service authorization bug ( which has now been resolved ) created a database but left your installation in a half-baked state.

**Comment by Bitexirtz** [comment] 2019-10-24 01:56
It is still error.
I tried the following:
[1st Try]
1. Fresh clone. (I deleted old cloned files.)
2. Hit F5
   -> Nothing is displayed in the browser.

[2nd Try]
1. Deleted "ConnectionStrings" in appsettings.json of Oqtane.Server project.
    Remain only {}
2. Hit F5
   -> Nothing is displayed in the browser.

See logs below:
[VS Debug log]
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Response status code does not indicate success: 503 (Service Unavailable).

System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.InstallationService.IsInstalled() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\Services\InstallationService.cs:line 31
   at Oqtane.Client.App.OnParametersSetAsync() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\App.razor:line 26
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'W5n-cxiMU7PI8_zTejYknIusT5ceKqIltlB4q7jl4vM'.

System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.InstallationService.IsInstalled() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\Services\InstallationService.cs:line 31
   at Oqtane.Client.App.OnParametersSetAsync() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\App.razor:line 26
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 1782.9102ms 101

[Chrome Console log]
blazor.server.js:1 [2019-10-24T01:15:13.214Z] Information: Normalizing '_blazor' to 'http://localhost:44357/_blazor'.
blazor.server.js:1 [2019-10-24T01:15:13.279Z] Information: WebSocket connected to ws://localhost:44357/_blazor?id=8m5T1pfV3tqhixfpfMw3_w.
blazor.server.js:15 [2019-10-24T01:15:15.402Z] Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at Oqtane.Services.InstallationService.IsInstalled() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\Services\InstallationService.cs:line 31
   at Oqtane.Client.App.OnParametersSetAsync() in D:\dev\study\blazor\oqtane\src\oqtane.framework\Oqtane.Client\App.razor:line 26
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
e.log @ blazor.server.js:15
blazor.server.js:1 [2019-10-24T01:15:15.403Z] Information: Connection disconnected.

**Comment by ADefWebserver** [comment] 2019-10-24 02:13
@sbwalker We need to re-open this. I just tried to set up Commit b1702f2c from scratch and got: 

> Can Not Create Database - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

![image](https://user-images.githubusercontent.com/1857799/67447544-11f4d380-f5c9-11e9-8722-d16fffaabad7.png)

**Comment by ADefWebserver** [comment] 2019-10-24 02:16
Nevermind I had my database connect wrong. Ok it works for me now.

**Comment by sbwalker** [comment] 2019-10-24 15:05
I think the problem is that you “Deleted "ConnectionStrings" in appsettings.json of Oqtane.Server project.
Remain only {}” - when I meant just to remove the DefaultConnection value ( you still need the ConnectionStrings section in the appsettings.config file )

**Comment by Bitexirtz** [comment] 2019-10-24 22:03
As mentioned above, I tried fresh clone.

**Comment by Bitexirtz** [comment] 2019-10-24 22:37
I tried to debug.
The error comes from this:
oqtane.framework\Oqtane.Client\Services\InstallationService.cs
line 31: return await http.GetJsonAsync<GenericResponse>(apiurl + "/installed");

I put breakpoint on below  method but it does not enter.
oqtane.framework\Oqtane.Server\Controllers\InstallationController.cs from line 178.
        // GET api/<controller>/installed
        [HttpGet("installed")]
        public GenericResponse IsInstalled()
        {

**Comment by ADefWebserver** [comment] 2019-10-24 23:14
@Bitexirtz - I was able to delete everything from my hard drive and cloned the project, then deleted my database and recreated it and everything ran. 

Can you try all those steps?

If it still doesn't work can you confirm that you can create a Blazor application from scratch and that it works? 

For example, that you could create the steps described here: [Creating A Step-By-Step End-To-End Database Server-Side Blazor Application](http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4318/Creating-A-Step-By-Step-End-To-End-Database-Server-Side-Blazor-Application.aspx)

**Comment by Bitexirtz** [comment] 2019-10-25 00:33
I tried both "blazorserver" and "blazorwasm" and executed successfully.

dotnet new blazorserver -o Blaze1
dotnet new blazorwasm -o Blaze2

About database, there is no database created yet so I have nothing to delete.

Since you cannot replicate, I will just debug this. If I know the problem, i will update here.

Thank you for your support.

**Comment by Bitexirtz** [comment] 2019-10-30 05:14
May I know if what .Net Core SDK version is necessary?
Mine installed is below. I executed "dotnet --info"

---------------------------------
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by fileman** [comment] 2019-10-30 07:09
Have you tried to repair 3.0? I read about a known issue that after 3.1 preview installation can broke it

**Comment by Bitexirtz** [comment] 2019-11-05 00:44
I tried to repair 3.0 but same error result.
Also, I installed the latest preview, and got the same error result.
        Microsoft.NETCore.App 3.1.0-preview2.19525.6

This is my latest investigation.
1. Status 503 is returned when calling the controller using GetJsonAsync()
     oqtane.framework\Oqtane.Client\Services\InstallationService.cs
     line 31: return await http.GetJsonAsync(apiurl + "/installed");
2. But I tried to paste the URL directly to Chrome and I've got a correct json result.
     url: http://localhost:44357/~/api/Installation/installed
          *This is the same url generated in line 31 of InstallationService.cs.

     json result:  {"success":false,"message":"Database Does Not Exist"}

**Comment by sbwalker** [comment] 2019-11-05 04:26
Do you have SQL Server installed on your system? If so, you can create a new empty database in SQL Server and then open the appsettings.json file and specify the connection string for the database you just created. Then when you run the application it should show the Install Wizard page and you should be able to click Install Now to complete the installation

**Comment by Bitexirtz** [comment] 2019-11-05 04:50
Still same error.
I create a empty DB in SQL Server named it oqtaneDb. I pasted the connection string to Oqtane.Server\appsettings.json and hit F5.

What I don't understand is I can the get the correct json result by directly pasting the url "http://localhost:44357/~/api/Installation/installed" to Chrome but the same url generates 503 status if called in InstallationService.cs as mentioned on my previous post.

**Comment by sbwalker** [comment] 2019-11-06 19:13
I assume you are using Visual Studio 2019. When you run the app in Visual Studio it should launch a browser and the first thing it does is check if the database has been installed. Can you open the \Oqtane.Server\Controllers\InstallationController.cs file and put a breakpoint on the method:

        // GET api/<controller>/installed
        [HttpGet("installed")]
        public GenericResponse IsInstalled()
        {

Use the debugger to step through the code to determine if an error is thrown.

**Comment by Bitexirtz** [comment] 2019-11-06 22:46
Yes, I am using Microsoft Visual Studio Enterprise 2019 Preview Version 16.4.0 Preview 4.0.

Breakpoint is not hit but when I paste the Installation url directly on Chrome, breakpoint is hit.

![browser](https://user-images.githubusercontent.com/7827862/68344518-2210c500-012a-11ea-8f05-92e37148ecc4.png)

The breakpoint is hit upon directly pasting the url "http://localhost:44357/~/api/Installation/installed" to Chrome.
![breakpoint](https://user-images.githubusercontent.com/7827862/68344566-440a4780-012a-11ea-8cf4-d4f3b3e6b419.png)

Is this problem not related to CORS?

**Comment by Bitexirtz** [comment] 2019-11-19 22:44
1. When configuration is set to "Wasm", I can display the installation page without error.
![confi](https://user-images.githubusercontent.com/7827862/69192851-68b9e280-0b60-11ea-8983-37801f3e537f.png)
![oqtane](https://user-images.githubusercontent.com/7827862/69192856-6b1c3c80-0b60-11ea-9530-ec3c4259b484.png)

2. But when configuration is either "Debug" or "Release", it is error. I am not sure if this is related to this issue: https://github.com/aspnet/AspNetCore/issues/15519.
![confi-error](https://user-images.githubusercontent.com/7827862/69193201-32309780-0b61-11ea-8b63-90d399bd38a0.png)

**Comment by ADefWebserver** [comment] 2019-11-19 22:48
These directions should work:
[What is Blazor Oqtane?](http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4359/What-is-Blazor-Oqtane.aspx)
Let us know what step stops you.

**Comment by Bitexirtz** [comment] 2019-11-19 22:54
"When Oqtane is deployed and running, it provides a dynamic web experience that can be run as client side Blazor or as server side Blazor."

I am trying the server side Blazor but it seems doesn't work.

**Comment by sbwalker** [comment] 2019-11-19 23:23
When you select the "Debug" configuration in Visual Studio 2019 and choose Build / Rebuild Solution does the Output window say:

========== Rebuild All: 4 succeeded, 0 failed, 0 skipped ==========

And then when you Debug / Start Debugging do you see any messages in the Output window which might explain the source of the problem on your system?

One thing to keep in mind is that Oqtane is currently being developed/tested against the official release version of Blazor ( 3.0.0 ) and it appears that you have a more recent Preview version installed on your system (  3.1.100 ). It is possible that you are running into incompatibilities but I would expect them to to be displayed in the Output window during build or debug. I am curious if you open your *.csproj files, if the .NET framework references have been modified. The references should be:

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview9.19465.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="3.0.0" />
  </ItemGroup>

**Comment by Bitexirtz** [comment] 2019-11-19 23:46
I will also check *.csproj files later.

Here are the screenshots of build and debug-output.
![Build Output](https://user-images.githubusercontent.com/7827862/69196568-d6b6d780-0b69-11ea-9cf8-d077608406aa.png)
![Output-Debug](https://user-images.githubusercontent.com/7827862/69196576-d9193180-0b69-11ea-871f-a17a2103fa29.png)

**Comment by Bitexirtz** [comment] 2019-11-19 23:51
Project settings are not modified.

![project](https://user-images.githubusercontent.com/7827862/69196819-8ee48000-0b6a-11ea-9ae5-fd94d3d5c27d.png)

**Comment by Bitexirtz** [comment] 2020-03-07 07:54
After a lot of trial and errors, I finally found then cause of the problem. I even posted question to stackoverflow. The problem is caused by Antivirus firewall.

https://stackoverflow.com/questions/60291777/asp-net-core-httpclient-from-console-returns-503-service-unavailable

**Comment by sbwalker** [comment] 2020-03-07 16:10
Thank you for following up on this issue. The good news is that it is not related to Oqtane... however it is unfortunate that it took so long for you to identify the root of the problem. Which antivirus were you using?

**Comment by Bitexirtz** [comment] 2020-03-08 22:44
We are using F-Secure Antivirus in our office. It was discovered after my local ftp server cannot be accessed from other PCs.
