### ISSUE TITLE
Issue:  Site Management - Green Checkmark, but error notificiation warning - Unable to see what field is errored easily.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3394] opened 2023-10-18 01:11 UTC
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/8bbb83f0-c4c3-4840-afae-3eb432ab5fb8)

This happens on I believe all of them, the green check mark appears like you did it successfully (dropdowns at least).

This should be a red X or Red Highlighted Border around the option not set properly to help identify the issue.  Green checkbox makes you feel like you did it right.

Also instead of "Select" it could be set to the actual "Default" setting for these inputs and would resolve most these issues instead of instructions to select.

**Comment by leigh-pointer** [comment] 2023-10-18 12:13
This guessing this is caused by the Dropdowns have a default value of "-" which would need to be space.empty.

**Comment by sbwalker** [comment] 2023-10-18 17:11
I agree that this UI should set the Site Template to the Default Site Template.

**Comment by thabaum** [comment] 2023-10-18 17:23
> I agree that this UI should set the Site Template to the Default Site Template.

It would be nice to be able to set the "Default" Theme/Container and Site Template in another area so that these are the defaults used when creating a site.  This way they are always set to your set "Site Defaults" when creating a new site to speed this process up.

There are two default themes... there should be only one and it should be selected.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/5d7f3a4d-782f-430d-8b6f-dd383bd1f5cd)

I will create another issue so this can be closed with fix #3398

**Comment by sbwalker** [comment] 2023-10-18 17:26
the Oqtane Theme is considered the default theme - the Blazor Theme is an alternate theme which is included only for testing purposes.

**Comment by sbwalker** [comment] 2023-11-10 20:08
Closing this issue - but another general issue could be logged for "Add Form Validation Support For Unselected Dropdowns"

**Closed by sbwalker** 2023-11-10 20:07 UTC
