### ISSUE TITLE
[BUG] Issues uploading nupkg modules

### ISSUE THREAD

**Issue by enfJoao** [oqtane/oqtane.framework#4884] opened 2024-11-29 19:04 UTC
### Oqtane Info

Version - 6.0
Render Mode - Either
Interactivity - Server
Database - SQL Server

### Describe the bug
Trying to upload a 13Mb nupkg in the Oqtane module admin.
The upload seems to stall and I get this after a while:
![image](https://github.com/user-attachments/assets/572676f7-5645-4334-8c13-75ddc6613e96)

I get this error on the e-mail message:
Log Message: File Upload Failed The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

And this message on log (not sure if related):
[2024-11-29 18:32:19+00:00] [Error] [Oqtane.Security.AutoValidateAntiforgeryTokenFilter] AutoValidateAntiforgeryTokenFilter Failure For https://oqtane.pt/api/file/upload 

These files are in the /Packages folder:
![image](https://github.com/user-attachments/assets/fc5dd546-7718-4be1-ac06-ac2c06400e49)

Oqtane seems to attempt to parse the file into 1MB part files, but fails.
The server resources never spike (3-4% CPU and disks at 0-1%). Network is more than capable of sending / receiving 13MB (It's a 900Mb/s network on both ends).
The number of parts generated seem random between attempts (1-7).

Sometimes Oqtane believes the upload was completed.
![image](https://github.com/user-attachments/assets/a0278819-e9b5-4015-a1e7-3360c3e30a3e)

Placing the nupkg file in the Packages folder and restarting the server does the trick.

**Comment by sbwalker** [comment] 2024-12-01 19:19
Is this only an issue when uploading a module or theme package - or can you also duplicate it when uploading through the File Manager?

**Comment by enfJoao** [comment] 2024-12-01 20:09
Same issue in file manager.

**Comment by sbwalker** [comment] 2024-12-02 02:32
Can you please provide more details about your environment. I am unable to reproduce this problem in my local development environment, or in a production environment (Microsoft Azure).

**Comment by enfJoao** [comment] 2024-12-02 10:39
Ok. This is weird.
I copied the files and database to a new pc with a fresh setup.
The only thing I did not migrate was the IIS configuration.
In the new server this issue does not happen. It uploads the file in less than 1s.
So it has to be some sort of IIS config messing with this, but what exactly?

**Comment by leigh-pointer** [comment] 2024-12-02 11:17
Since the problem doesn't occur on the fresh setup, it's almost certainly related to the IIS settings.  File upload size restrictions: Your old IIS configuration might have lower limits set for file uploads, causing slowdowns for larger files.

To Increasing the Maximum Upload File Size in IIS, you could.

1. Modify the maxAllowedContentLength setting in the web.config
You can increase the maximum file size by modify the [maxAllowedContentLength](http://msdn.microsoft.com/en-us/library/ms689462(v=vs.90).aspx) setting in the web.config file:

```
<system.webServer>
  <security>
    <requestFiltering>
      <requestLimits maxAllowedContentLength="2147483648" />
    </requestFiltering>
  </security>
</system.webServer>
```
With the above maxAllowedContentLength, users can upload files that are 2 GB in size. This setting will work right away without restart IIS services.

2.Edit the request filtering feature settings and the request limits using IIS manager

1. Open IIS Manager.
2. Select the website that you want to configure.
3. Make sure you are in Features View per the button at the bottom of the manager.
4. Select Requests Filtering and open it by double-clicking the icon. The Request Filtering pane displays:
![image](https://github.com/user-attachments/assets/4f062be5-577d-45ee-831b-11be76bf032c)
5. From the Actions pane on the right hand side of the screen click Edit Feature Settings... link. The Edit Request Filtering Settings window displays.
6. In the Request Limits section, enter the appropriate Maximum allowed content length (Bytes) and then click the OK button
 ![image](https://github.com/user-attachments/assets/4df8f6c4-9a4c-4669-b3c0-145098fd4975)
7. Restart IIS.

3. Manually edit the ApplicationHost.config file

1. Click Start. In the Start Search box, type Notepad. Right-click Notepad, and then click Run as administrator.
2. On the File menu, click Open. In the File name box, type %windir%\system32\inetsrv\config\applicationhost.config, and then click Open.
3. In the ApplicationHost.config file, locate the <requestLimits> node.
4. Remove the maxAllowedContentLength property. Or, add a value that matches the size of the Content-Length header that the client sends as part of the request. By default, the value of the maxAllowedContentLength property is 30000000. 

For example, modify the following configuration data inside the <requestFiltering> section.

`<requestLimits maxAllowedContentLength ="<length>" />`

5. Save the ApplicationHost.config file.

**Comment by sbwalker** [comment] 2024-12-02 13:13
Closing this issue as I am unable to reproduce - appears to be caused by an environment configuration

**Closed by sbwalker** 2024-12-02 13:14 UTC

**Comment by enfJoao** [comment] 2024-12-03 17:30
@sbwalker and @leigh-pointer 
Just some added info in case this issue bumps again or someone else has similar problems.

I tried three things to debug this issue in two servers. Windows has the same version ans features on both servers. IIS has the same default config for the server (just added the url rewrite and configured the url bindings).

1. Moving the current database and files to a new server => issue is solved => suggests it is a IIS/Windows issue;
2. Removing IIS and configurations from the current server and reinstalling everything (same files and database) => issue persists => suggests it is an oqtane issue (files and/or database);
3. Creating a new install of Oqtane 6.0 in the current server after the IIS config reset => Issue is solved => suggests it is a weird combination of both files/db and server.

I can easily continue using Oqtane in the new 6.0 install and migrate apps, but Oqtane sure has some evil intent towards me...
