### ISSUE TITLE
Horizontal Menu and submenu items

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1165] opened 2021-03-05 15:04 UTC
On a main /sub menu its not always desirable to have an menu item that is navigable but an item to host the child menu items.
Using the navigation option in the Page Management hides the page which is halfway there paired with a visible property the desired effect could be achieved.

sub-Submenus can not currently be  displayed on the Horizontal menu.

**Comment by hishamco** [comment] 2021-03-05 15:19
I didn't understand the issue, could you please ellaborate?

**Comment by leigh-pointer** [comment] 2021-03-05 15:32
So the menu item "Parent Page" should only be a menu option to hold the child items.  The Child items are only displayed when the "Parent Page" item is clicked which also navigates to that page.
![Capturem](https://user-images.githubusercontent.com/9447612/110136173-a97a5100-7dcf-11eb-8f2b-1317f50253a3.PNG)

Desired effect would be that the item is disabled and displayed the child item on mouse over/hoover

The Sub menu can not currently have a sub menu ie. 
Parent -> Child -> Childchild. which I am looking in to.

**Comment by hishamco** [comment] 2021-03-05 15:43
I expect that's your intend, I think this is already discussed [here](https://github.com/oqtane/oqtane.framework/discussions/1092)

**Comment by leigh-pointer** [comment] 2021-03-05 16:12
@hishamco yes that seem to be half of the issue the other half is that a sub > **sub** menu is not being displayed.

**Comment by hishamco** [comment] 2021-03-05 16:51
Please let me know if you interest to solve all or some of the issues or I will try to fix them

**Comment by sbwalker** [comment] 2021-03-11 16:27
This is a duplicate of #1092. The limitation of displaying only 2 levels of navigation is a totally separate issue.

**Closed by sbwalker** 2021-03-11 16:27 UTC
