### ISSUE TITLE
override List<Resource> Resources not getting called when creating ContainerSettings

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4257] opened 2024-05-13 19:07 UTC
### Oqtane Info

Version - 5.1.1
Render Mode - Interactive 
Interactivity - Server
Database - SQL Server

### Describe the bug
When loading the Theme ContainerSettings the public override List<Resource> Resources => new List<Resource>() is not called. 

### Expected Behavior
The method is called

### Steps To Reproduce
add to a containerSettings component
```
        public override List<Resource> Resources => new List<Resource>()
        {
              new Resource { ResourceType = ResourceType.Stylesheet, Url = "~/css/Theme.css" },
        };
```

**Comment by sbwalker** [comment] 2024-05-14 11:56
This is complicated. The framework Settings component dynamically loads 3 other components at run-time:

1. A component within a module which implements Oqtane.Interfaces.ISettingsControl
2. A component within a theme which has a ThemeSettingsType defined in its ThemeInfo
3. A component within a theme which has a ContainerSettingsType defined in its ThemeInfo

Dynamically loading components within a module does not conform to the standard patterns which means that the Resources are not discovered or loaded by the framework. Resources can currently be defined in 4 standard ways:

1. In a module component
2. In a module's ModuleInfo (IModule) class
3. In a theme component
4. In a theme's ThemeInfo (ITheme) class

Supporting these exception cases will require some investigation, as we do not want to add custom logic to handle them at the expense of degrading framework performance for the other scenarios (ie. reflection is expensive and would be required to get access to the Resources).

**Comment by leigh-pointer** [comment] 2024-05-21 06:34
@sbwalker should we not introduce  something like this ?

```
    public class ContainerSettingsBase: ModuleBase
    {
        private new List<Resource> Resources;
    }
```

**Comment by sbwalker** [comment] 2024-07-11 12:48
The problem is not that the Resources cannot be defined - as ContainerSettingsBase already inherits from ModuleBase which allows you to define Resources. The problem is that the framework needs to be able to explicitly discover those Resources at runtime when it composes the UI. Currently the router can only discover Resources which are defined in a theme or module component - the framework has no idea what components are being used within those components so it is has no way to access their Resources. This is described further in the following issue:

https://github.com/oqtane/oqtane.framework/issues/4358#issuecomment-2197005726

A PR was submitted which attempts to resolve this problem however it would impact overall performance of the framework as it imposed extra processing/reflection for every runtime scenario rather than targeting the specific scenario where discovery is needed - so it was not merged.

**Comment by sbwalker** [comment] 2024-07-27 14:14
The solution which was used in the QuillJSTextEditor in the 5.2.0 release (which had the same issue described in this issue related to stylesheets) was to use JS Interop:

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
		if (firstRender)
		{
            // include CSS theme
            var interop = new Interop(JSRuntime);
            await interop.IncludeLink("", "stylesheet", $"css/quill/quill.{_theme}.css", "text/css", "", "", "");
        }
```

This logic dynamically injects the link element into the page. This approach can be used an alternative to declaring the stylesheet in the Resources property.  Note that this approach will only work with Interactive components.

**Closed** 2024-09-18 19:23 UTC

**Comment by sbwalker** [comment] 2024-09-18 19:25
#4632 adds support for loading Resources for Container settings and Theme settings
