### ISSUE TITLE
Page Settings > Head Content:  Scripts are removed a </script> closing tag remains in the head section.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3235] opened 2023-09-08 03:15 UTC
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/c18ced8f-2166-4900-860c-ab00491f5429)

`RemoveScripts` function located in Head.razor leaves a '</script> closing tag when scripts are removed for page/site `headcontent`

I tested with scripts on top and on bottom and between other elements in the head section, all scripts get removed but no matter what if 1 or more scripts are in the Head Content of a page field there is always the last </script> tag rendered in source.

If Oqtane does not allow scripts in the head content should this be validated on save potentially letting an administrator know you should not load scripts in that section to help them understand why they are not appearing as desired?

Of coarse remove the scripts from the head content fields and this issue is not a problem.

However, the tooltip is misleading if Oqtane is going to remove scripts.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/ae63d31d-c286-4027-9976-eaa33d01535a)

So maybe this is a bit confusing here?!

Are scripts allowed in the head?! If so why are they removed?  If not the tooltip should let you know what is allowed (not allowed)

From research I have done the Site Settings works as expected allowing script tags to be included in head and body, however on in Page Settings you get this issue and #3236.

Since the logic for Site Settings works if Page Settings are supposed to result the same this needs a fix.

After further review I removed the "RemoveScripts()" function from the Header.razor

```
    private void PropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        switch (e.PropertyName)
        {
            case "PageTitle":
                var title = "\n\t<title>" + SiteState.Properties.PageTitle + "</title>";
                if (title != _title)
                {
                    _title = title;
                    StateHasChanged();
                }
                break;
            case "HeadContent":
                var content = "\t" + SiteState.Properties.HeadContent;
                if (content != _content)
                {
                    _content = content;
                    StateHasChanged();
                }
                break;
        }
    } 
```

Same result so I was in the wrong place trying to get the </script> to get removed, but then I noticed the tooltip allows them and setting them in Site Settings admin panel they would load up in that last blank line under the prerender comment which explains that blank line I was looking to remove a bit.
    
I imagine the other blank line also adds something but just isnt adding anything at this time while working with clean install.

So the scripts are trying to load, but they are being cut out when added to page settings.

  `var content = "\t" + RemoveScripts(SiteState.Properties.HeadContent);` function does not have any affect here so I must be in the wrong area to diagnose this.
  
  I know the _Host.cshtml file has a lot going on here I have reviewed a bit.
  
  I guess how I found this is I am trying to load different resources on different pages and potentially with different themes to see any potential breaking issues using Radzen/Syncfusion/Kendo UI/Blazorise and some other libraries in various types of components I have been creating to see which results I like best using with Oqtane.
  
  I was just fixing formatting issues with tabs and new lines... found these few more things to work out with the framework and I thought I would share them.  Unless fix comes overnight I will take a look more tomorrow.  
  
  @sbwalker sorry for the long set of issues here I don't think many people even use this feature yet for Page Settings > Page Content as it is probably mostly used in Site Settings Page Content.  Combing through the code today I will sleep on it see if I can help, but maybe you can go right to the problem.  Work on whatever you got cooking a for few days I will try to help if you can toss me a few clues I would appreciate it.  Now that I know it works OK with Site Settings I have more to go on tomorrow already.  Thank you.

**Comment by sbwalker** [comment] 2023-09-08 11:39
@thabaum Blazor does not support scripts being added directly to the page content using a Razor component - it must be added using JS Interop. So the RemoveScripts() function removes the scripts so that they can be added later in the OnAfterRenderAsync() event. If a < script /> closing tag is not being removed properly it would likely be related to formatting issues with how the script was specified in the Head Content field. You will need to provide an  example of the value you specified in Head Content in order to diagnose the problem.

**Comment by sbwalker** [comment] 2023-09-08 11:46
I am not able to reproduce this problem in my local testing (I tried many variations of script specifications and they are always fully removed). I believe it is  caused by PR #3232, as the extra tab characters you added would cause issues with the parsing logic.

**Comment by thabaum** [comment] 2023-09-08 14:02
I downloaded a fresh copy and had the issue.

I am adding the scripts to the Page Settings > Page Content of the home page default site running on server.

I have a clean install for this issue.

I did  add the fix later while troubleshooting the issue but I will test again today.

Again adding  to Site Settings > Page Content does not create the issue.

And if you add scripts to the body content they do not get included in a page.  At least I could not find them in source.

The issue is strictly with Page Settings.

**Comment by thabaum** [comment] 2023-09-08 14:03
correction **Page Settings > Page Content** is the issue.  When editing a page.  Sorry.

**Comment by thabaum** [comment] 2023-09-08 14:04
You can add scripts via Site Settings > Page Content and they show up.

**Comment by sbwalker** [comment] 2023-09-08 14:43
@thabaum please provide the exact value you specified for the Head Content which resulted in the reported issue with the < script /> closing tag. The exact value is needed so that I can reproduce the issue locally.

Please note that scripts CAN be included in the Head Content field - they will not appear when you do a view source on the page because Blazor requires JS Interop to manage JavaScript (which is why they are removed from the Head component). The scripts are injected dynamically and will only be visible through the browser dev tools.

**Comment by sbwalker** [comment] 2023-09-08 14:59
@thabaum I believe I found the cause of this issue - it is in AddHeadContent() in ThemeBuilder.razor.

**Comment by thabaum** [comment] 2023-09-08 14:59
OK, then two issues and I will send screenshots and a full how-to on a completely new installation I am preparing now.

Now there are two things to point out:

1.  Enter `<script src="js/custom.js"></script> ` in both BODY and HEAD they get loaded in both when you add to `SITE SETTINGS`

2.  Enter the same dont mater put both in the head and whatever in body of `PAGE SETTINGS`
RESULTS:  </script> closing tag in head and NO scripts loaded in body.

In fact I was trying to add radzen dialog components in all places as they need to be in the body of the theme.. but for testing around I wanted to add them to the page itself... no luck, then to site settings... no luck. <RadzenDialog /> would not get included.

I think it would be nice to be able to add a component to the Body, I will test this with Site Settings as I may have only tested with Page Settings and gave up.

If you put <RadzenDialog/> in the module component it is not displayed properly as it is put in a container that has styles shifting it over.

This is what got me working in this area... and I wanted to play with headcontent more for updating meta data for these component pages.

Of coarse Radzen uses Material vs Bootstrap but they have a new default theme and really the themes don't look bad going against bootstrap used by Oqtane Default theme.

**Closed** 2023-09-08 15:09 UTC

**Comment by sbwalker** [comment] 2023-09-08 15:11
@thabaum Please provide the exact value you specified for the Head Content which resulted in the reported issue with the < script /> closing tag. I would like to test with #3239

**Comment by thabaum** [comment] 2023-09-08 15:24
Page content:

```
<meta ref="dogs">
<meta ref="dogs2">
<meta ref="dogs3">
<script src="js/custom.js"></script>
```

Body Content:
```
<script src="~/custom.js" </script>
<script src="~/custom2.js" </script>
<RadzenDialog />
```

for example
