### ISSUE TITLE
Enh: ActionDialog support for Static mode

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4031] opened 2024-03-20 11:02 UTC
## Issue Description

ActionDialog is currently not supported in Static rendering modules.

## Steps to Reproduce

1. Create a new module using the default External template.
2. Change the render mode to static
3. Click on the Delete button and the dialog does not appear.

## Expected Behavior

I should be able to trigger the dialog and delete a module item in static mode.

## Actual Behavior

The button to trigger the dialog does not work because it relies on the onclick handler, and neither would work the internal confirm or cancel buttons for the same reason.

## Possible Solution

Similar to Pager module, ActionDialog should be constructed conditionally based on render mode to support form with submit instead of onclick

**Comment by sbwalker** [comment] 2024-03-20 17:46
@mdmontesinos I was hoping to be able to implement static rendering support without any requiring any changes to the consumer of the component - however this was not possible. 

I had to introduce a new Id parameter which is required when using static rendering on a page which contains multiple ActionDialog components (ie. a list of items). The Id parameter should contain a unique identifier for the item... usually a database identifier. This Id will be used to construct unique form names so that Blazor is able to submit user interactions to the correct form. Note that Blazor does not support dynamic form names - the name must be immutable across form submission events. Here is an example of the Id parameter:

```
<ActionDialog Header="Delete Page" Message="@string.Format(Localizer["Confirm.Page.Delete"], context.Name)" Action="Delete" Security="SecurityAccessLevel.Admin" Class="btn btn-danger" OnClick="@(async () => await DeletePage(context))" ResourceKey="DeletePage" Id="@context.PageId.ToString()" /><
```

Note that this enhancement is not fully functional. When the Confirm button is selected, the callback is being made to the method specified in the OnClick parameter, however a general error is being thrown:

"Cannot access a disposed object."

I have not been able to determine the root cause of the error yet.

**Comment by mdmontesinos** [comment] 2024-03-20 18:29
> @mdmontesinos I was hoping to be able to implement static rendering support without any requiring any changes to the consumer of the component - however this was not possible.

Perhaps adding an auto-generated Guid in the case that no Id is supplied as a parameter could work for "legacy" support? In this way, the parameter is truly optional and won't case issues for components already using it, but still offering the possibility of setting the custom Id for better practices.

> Note that this enhancement is not fully functional. You can display a modal dialog and Cancel it. However when the Confirm button is selected, the callback is being made to the method specified in the OnClick parameter, however a general error is being thrown after the operation completes:

> "Cannot access a disposed object."

I'll try the new version to test if I'm also getting the same error. I'll update as soon as I can.

And as always, thanks for the quick response.

**Comment by sbwalker** [comment] 2024-03-20 18:52
@mdmontesinos my comment "Note that Blazor does not support dynamic form names - the name must be immutable across form submission events" means that the component cannot generate its own Guid - this is what I tried initially and it does not work. This is because when the component is first initialized it generates a Guid and then when the form is submitted another Guid is gnerated and the Guids do not match so the form input cannot be matched to the component.

**Comment by thabaum** [comment] 2024-03-20 19:33
@attribute [StreamRendering] I believe fixes the issue in the module template... ;)

**Comment by sbwalker** [comment] 2024-03-20 19:39
@thabaum In order to test this you need to add the following code to the module template Index.razor:

    public override string RenderMode => RenderModes.Static;

and modify the markup to include the Id parameter:

                <td><ActionDialog Header="Delete Zyhfish" Message="Are You Sure You Wish To Delete This Zyhfish?" Action="Delete" Security="SecurityAccessLevel.Edit" Class="btn btn-danger" OnClick="@(async () => await Delete(context))" ResourceKey="Delete" Id="@context.[YourModuleName]Id"  /></td>

Build the module and make sure the Site is set to Static render mode.

**Comment by thabaum** [comment] 2024-03-20 19:48
@sbwalker sorry it was a quick reaction as I was not getting the module popup, but now I do, but the delete button does not work in the dialog.

I was using `@ModuleState.ModuleId.ToString()` to get the id, but again the dialog in not responsive to delete.

**Comment by sbwalker** [comment] 2024-03-20 19:51
ModuleId is not a unique identifier - as soon as you have 2 items in the module list the ID will be a duplicate which will result in Blazor failing to match the form submission (and possibly raising an exception).

**Comment by thabaum** [comment] 2024-03-20 19:56
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/110e79ae-e8c1-49bb-9d52-5c7eb029af58)

It looks like I am at the current issue.

**Comment by sbwalker** [comment] 2024-03-20 19:58
Yes, that is the issue that I reported above.

**Comment by thabaum** [comment] 2024-03-20 20:12
Well, it seems like it is deleted, disposed of, then calls this function.

Any reason this is a "Put" and not a "Delete", seems like the wrong action...

**Comment by sbwalker** [comment] 2024-03-20 20:14
It is a "soft delete" - which is an Update. Only the Recycle Bin allows for "hard" delete of pages.

**Comment by thabaum** [comment] 2024-03-20 20:22
My apologies, I meant post not put.

**Comment by thabaum** [comment] 2024-03-20 20:28
@sbwalker PostJsonAsync is called on a delete, the module object is already deleted when this is called.

**Comment by sbwalker** [comment] 2024-03-20 20:31
I have no idea what you are referring to. The ActionDialog does not call any HTTP methods. It simply calls whatever method was passed in on the OnClick parameter.

**Comment by sbwalker** [comment] 2024-03-20 20:33
@thabaum this is the way Static Blazor forms work - you must POST back to the component which invokes the method specified with the OnSubmit attribute.

**Comment by thabaum** [comment] 2024-03-20 20:34
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/bcd40627-b50b-41bc-8397-598e8bf9eb51)

This is from the post form method correct?

The "Confirm" button deletes the object, from what I can tell, I just get this error along the way.

**Comment by sbwalker** [comment] 2024-03-20 20:36
No, I think the PostJsonAsync is being invoked from your own module code as a side effect - basically an error is being thrown and caught by the exception handler and then it is trying Log the error - and it uses a Post to call the LogService. So I don;t think this is the cause.

**Comment by sbwalker** [comment] 2024-03-20 20:40
No. The logger is designed to log errors which occur in components. An error has occurred in the component so it is going to try to log it. Suppressing the error is not the solution.

**Comment by sbwalker** [comment] 2024-03-20 21:04
As soon as this line gets executed in the module component:

```
        await MyTestService.UpdateMyTestAsync(MyTestId, ModuleState.ModuleId);
```

An exception is thrown:

IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
SocketException: The I/O operation has been aborted because of either a thread exit or an application request.

Which results in the exception handler catching the error and calling the logger:

```
            await logger.LogError(ex, "Error Deleting MyTest {MyTest} {Error}", MyTest, ex.Message);
```

Which then results in the PostJsonAsync exception. So the actual error is the thread abort exception... not the logger.

**Comment by thabaum** [comment] 2024-03-20 21:08
Thanks for the clarification.  I was not saying to suppress the error, but log the error of the logger.


1. The dialog appears on delete. 
2. the confirm button will delete the entry, but bugs out with this current exception trying to be logged in the logger.
3. This potential logger error is occurring rendering the action dialog into a buggy state after OnClick() function is performed in `Confirm()` method.

```
    private void Confirm()
    {
        if (PageState.RenderMode == RenderModes.Interactive || ModuleState.RenderMode == RenderModes.Interactive)
        {
            DisplayModal();
        }
        OnClick();
    }
```

**Comment by sbwalker** [comment] 2024-03-20 22:24
@thabaum I think the problem is that the HttpClient service is being disposed. And I think it has something to do with the differences in scope between static components and interactive components. Maybe using HttpClientFactory would help... but only if it does not affect the run-time characteristics or performance of Interactive Blazor. And in general I really want to minimize conditional logic based on render mode as much as possible... or else it will become a nightmare to maintain.

**Comment by thabaum** [comment] 2024-03-20 23:56
@sbwalker HttpClientFactory seems to be the direction to go forward with and is designed to improve performance and scalability reusing existing and disposing of HttpClient instances to reduce overhead along with avoiding socket exhaustion.  I believe this is worth exploring.

**Comment by sbwalker** [comment] 2024-03-21 00:21
Yes it is worth exploring. I do find it ironic that there was so much criticism of Oqtane’s approach of having Interactive server components call server APIs - yet it allowed the framework to avoid so many complex process model problems by having an abstraction layer to manage these issues. Unfortunately Static rendering can’t seem to be solved in the same way :(

**Comment by thabaum** [comment] 2024-03-21 01:59
@sbwalker I believe what is very ironic... is by version 10 I think everything is API based but super efficient... like I said once I believe your far out in the future man.  We got to pull you back in time ;)
> I do find it ironic that there was so much criticism of Oqtane’s approach of having Interactive server components call server APIs

**Comment by mdmontesinos** [comment] 2024-03-21 08:53
Some updates now from my part.

In my use case, Static components will always be in this render mode, or perhaps Interactive Server, but never Interactive client. Therefore, I'm not using client-side services with HttpClient calls, but rather server-side services that directly use repositories.

In this situation, the ActionDialog works properly, the element is deleted, no exception is thrown and so pointing that the most probable cause is HttpClient.

Also, there's a bug that prevents the dialog from closing in Static mode after the OnClick action is executed (you probably haven't encountered it because an exception was thrown).

```c#
private void Confirm()
{
    if (PageState.RenderMode == RenderModes.Interactive || ModuleState.RenderMode == RenderModes.Interactive)
    {
        DisplayModal();
    }
    OnClick();
}
```

Should be replaced with:

```c#
private void Confirm()
{
    OnClick();
    DisplayModal();
}
```

The logic of closing the modal in Static/Interactive is already contained in DisplayModal, so it should always be used when confirming the action. Also, the action must be executed before because otherwise, the navigation in static mode cancels it.

**Comment by sbwalker** [comment] 2024-03-21 14:03
@thabaum I implemented HttpClientFactory locally but it does not resolve this issue. It still throws the same error:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/c7653ff7-0325-4fb6-a518-ad2e33a98e43)

(plus I had to hardcode the BaseAddress for the HttpClientFactory as it cannot resolve the NavigationManager from the container - which makes this a dead end)

**Comment by thabaum** [comment] 2024-03-21 14:16
@sbwalker thanks for the update.

**Comment by sbwalker** [comment] 2024-03-21 14:22
further to above... I found out that when running on Static Blazor, there is a different version of NavigationManager which is used on the server: "Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager". However when I try to get that service from the DI container I get:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/489afbfc-3483-457c-b724-a84a57065aed)

**Comment by sbwalker** [comment] 2024-03-21 14:47
I was able to figure out a workaround for the RemoteNavigationManager issue above... and I merged #4039 which adds HttpClientFactory support. In order to use it, you need to use a different constructor in your Service classes:

```
public PageService(IHttpClientFactory http, SiteState siteState) : base(http, siteState) { }
```

However, as I mentioned above, it does not resolve the "Cannot access a disposed object" issue which is the focus of this thread.

**Comment by thabaum** [comment] 2024-03-21 14:57
@sbwalker I believe this is a great enhancement using HttpClientFactory, nice work!  
`public PageService(IHttpClientFactory http, SiteState siteState) : base(http, siteState) { }`

I had like 25 or more of these I updated last night and changed back today to change directions :)

I am glad that still held water for an enhancement and was included in the framework, thank you.

I will have to roll out for a few now but back later full steam ahead by high noon my time or sooner.  I read up the servicebase.cs file relating logic which interested me.  I look forward to reviewing the code changes when I get back!

**Comment by sbwalker** [comment] 2024-03-21 15:31
@mdmontesinos I added your change above which switched the order of OnClick and DisplayModal. And thank you for confirming the error is only occurring when using HttpClient. Based on that, we could simply have guidance that if you are using Static rendering in your component then you should not use HttpClient - you should use direct data access instead. I plan to update the module template today to follow the "dual service" approach which would effectively resolve this problem. Perhaps we can close this issue as resolved, as it does accomplish the goal of enabling the ActionDialog in Static rendering.

**Comment by mdmontesinos** [comment] 2024-03-21 17:56
Glad to help! 

And about the module template, I recently wanted to create server-side services for my static modules and was a bit lost on where to start. I ended up taking HtmlTextService as a reference because it includes both client and server versions. Also, I believe it's really important to have well documented module templates with both versions so that developers understand the differences in render modes. Especially taking into account the improvements in performance when not using HttpClient....

As for me, you can close the issue. The desired enhancement is already implemented, the HttpClient could be logged as a new issue.

**Comment by sbwalker** [comment] 2024-03-21 18:08
@mdmontesinos I am working on the changes to the module template now and there are indeed a lot of changes if you want to use the dual service approach (which supports both Static and Interactive render modes). I was just testing the module using Static rendering and the ActionDialog still throws an exception related to a disposed object. However, I now suspect that the object which is disposed is actually the NavigationManager - not HttpClient. This is related to the same issue I already reported to Microsoft - and for which there is no workaround currently:

https://github.com/dotnet/aspnetcore/issues/53996

By deselecting "Break when this exception type is user-handled" the operation works as expected. So I suspect this error is related to NavigationManager and only occurs when running in the Visual Studio debugger. And it probably is related to the fact that there are actually 2 different version of NavigationManager - one for Interactive and one for Static render modes.

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/7e8574e7-9f0e-4dbb-893d-efd07c3a6673)

**Comment by sbwalker** [comment] 2024-03-21 18:57
@mdmontesinos #4042 contains all of the updates to the Module Template. I am going to close this issue.

**Closed by sbwalker** 2024-03-21 18:57 UTC
