### ISSUE TITLE
[ENH] ContainerBase Should Not Inherit From ThemeBase

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4886] opened 2024-11-30 10:55 UTC
### Oqtane Info

Version - 6.0

### Describe the enhancement

At the moment many Oqtane controls - including containers and themes - MUST inherit from an Oqtane-specific base class. 
This is because certain properties such as `Name` will only be known to Oqtane if the implementation inherits from these base classes.

This also adds a lot of baggage to each control and container. For example:

1. every inheriting component incl. container will run code to retrieve the (async) correct resources - whether it needs them or not
2. every inheriting component incl. container has a fairly large (and IMHO confusing) standard API which I would like to avoid. These are from `ThemeBase` and incl. loads of overloads of `NavigateUrl(...)` each with minor variations
3. Every such control also gets things injected and parameters passed in, which are often never used - not ideal for performance.

BUT: my understanding of good architecture prefers composition,
which is what I would like to encourage in various docs. But as of now, this is not possible.

My recommendation is that we promote **Composition**. This requires the following changes - for example for containers:

1. An interface like `IContainer` - or we could enhance the existing `IContainerControl`
2. This would require the really necessary parameters - such as `Name`

Note: ATM there is something similar on the `IThemeControl`, but this should _not be used_

* it has additional properties such as `PaneNames` which are simply not necessary on most components or even Containers. 
* it also has a `Resources` which again may not be relevant to the implementation of most controls, so allowing that on a separate optional interface like `IHasResources` or something would make much more sense.

### Anything else?

Would really appreciate if we could change this, to promote good practices and ensure long term stability of the API without cluttering the code. 
I would also contribute the change if it's approved.

**Comment by sbwalker** [comment] 2024-12-02 14:58
Oqtane already utilizes interfaces. For example, the IModuleControl interface defines the core properties which a module component can implement. However due to the fact that interfaces are immutable it is essential to create an abstraction so that third party developers do not take a direct dependency on an interface (as otherwise, anytime the interface changed it would result in a breaking change). The way this is accomplished is by including a base class (ie. ModuleBase) which implements the interface and acts as an abstraction layer. This way a module developer can take a dependency on ModuleBase and not need to worry if the interface changes. This is a well accepted architectural approach when creating a framework/platform (which is not common when building applications as you do not need to worry about compatibility). The base class also provides some common utility methods and events to provide standard, simplified methods for interacting with the framework.

**Comment by iJungleboy** [comment] 2024-12-02 15:22
I understand that and there is quite a lot going for this.

What I don't like is three things:

1. that simple things such as containers inherit from quite a heavy `ThemeBase` class which seems to have grown and has APIs which are actually not relevant at all - such as the `Panes` and also `Thumbnail` (though that could come in handy some day). It looks like the `ThemeBase` was developed for both the main Theme and used for components at the same time, resulting in some mixed APIs.
2. that it always does work such as resources processing, which is often not relevant (again because of inheriting the `ThemeBase` which feels wrong
3. that it - and many other controls - have a fairly random mix of "helper" APIs such as `NavigateUrl`, the overload signature of which can only be explained by history (gradually adding more variants). 

What I think would be more elegant is a "pure" base class which only does the necessary minimum and no overhead or additional APIs. 

Since you have the (absolutely justified) concern for the base class which may need to be enhanced by the platform itself, and the current `ContainerBase` already has the APIs (so it cannot be down-converted to a lightweight base class),
maybe we could find a middle ground for things such as containers, modules, theme-controls etc. 
An idea could be to also have bare-metal base classes, such as:

* ContainerBareMetalBase
* ContainerRawBase
* ...

Something like this - and equivalent raw/bare-metal components.

**Comment by iJungleboy** [comment] 2024-12-04 07:02
@sbwalker Creating a lightweight `Container` was my intent, but it fails.

I can implement the `IContainerControl`, but Oqtane will try to cast it to an `IThemeControl` when loading here: 
https://github.com/oqtane/oqtane.framework/blob/c81905882f1bf1d90c302e9fc086b52551e1b6f7/Oqtane.Server/Repository/ThemeRepository.cs#L304-L313

There it will ask for the `Name` (of IThemeControl) - without `null`-check, and `Thumbnail`.

I hesitate to implement `IThemeControl` even if I could get it to work, because IMHO implementing `IContainerControl` should be all it needs. 

I would suggest

1. Expand `IContainerControl` to have a `Name`, and possibly a `Thumbnail` if you want to implement a kind of preview some day.
2. Change the code to _not_ cast to `IThemeControl` when loading containers.

**Comment by sbwalker** [comment] 2024-12-04 13:52
I was reviewing this yesterday. The only IThemeControl interface property which is not applicable to container components is Panes... all of the other properties are applicable:

Name - provides "friendly" name for a container component
Thumbnail - intended to provide a url for displaying an image thumbnail for a container component (not implemented currently)
List<Resource> Resources - provides a collection of resources (CSS,JS) for a specific container component

If ContainerBase did not inherit from ThemeBase it would need to support all of the same default services, state objects, and helper methods which exist in ThemeBase - so basically the only difference is that it would not include ```public virtual string Panes { get; set; }```.

**Comment by iJungleboy** [comment] 2024-12-04 16:53
I guess this makes sense.

From my point of view I would prefer if `IContainerControl` would require these, and would allow anybody who implements the interface create clean containers.

ATM the interface is there, but it doesn't serve a purpose, since implementing it won't actually result in the container being loaded.

**Comment by sbwalker** [comment] 2024-12-19 19:55
This would require a fair amount of development effort and regression testing... just to achieve an end result of removing a single virtual property. The simpler solution at this time is to document the virtual property to clearly indicate that it only relates to Themes - not Containers. Maybe in the future there will be a wider divergence in the behaviors of themes and containers which would make this enhancement more worthwhile.  But for now I am going to close this issue.

**Closed by sbwalker** 2024-12-19 19:55 UTC
