### ISSUE TITLE
Recycle bin not showing Deleted Date

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2234] opened 2022-06-07 11:14 UTC
The recycle bin does not show the Deleted information.  The database is not holding the information therefore on Delete the data is not being saved to the database.

**Comment by sbwalker** [comment] 2022-06-13 12:27
@leigh-pointer can you please provide a more detailed explanation for this issue

**Comment by sbwalker** [comment] 2022-06-13 21:05
If you look in the database, the data is being populated in the actual tables. The problem is that the ModuleController Get() method is not returning the data:

                        module.CreatedBy = pagemodule.Module.CreatedBy;
                        module.CreatedOn = pagemodule.Module.CreatedOn;
                        module.ModifiedBy = pagemodule.Module.ModifiedBy;
                        module.ModifiedOn = pagemodule.Module.ModifiedOn;
                        module.IsDeleted = pagemodule.IsDeleted;

Note above that the code is not setting module.DeletedBy or module.DeletedOn properties. If you add this logic then the UI will show the Deleted By and Deleted On information. This appears to only be an issue for Modules - not Pages.

**Comment by sbwalker** [comment] 2022-06-14 18:28
merged in #2234 - thank you @leigh-pointer

**Closed by sbwalker** 2022-06-14 18:28 UTC
