### ISSUE TITLE
[ENH] Load Resources for Headless components

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4500] opened 2024-08-09 12:57 UTC
### Oqtane Info

Version - 5.2.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
I am currently working with a module that can be extended through control libraries. To facilitate this, I have configured the packages to run in a headless mode, which has been functioning as expected.

However, I’ve encountered a situation where a component that inherits from ModuleControlBase and overrides the List<Resource> Resources property does not load the resources as anticipated during runtime. While the property is successfully invoked, the resources specified are not being loaded.

**Comment by sbwalker** [comment] 2024-08-09 17:14
I believe this is a duplicate of #4257 ie. resource for components which are nested inside of a module or theme component are not currently processed by Oqtane

**Comment by sbwalker** [comment] 2024-08-13 15:48
@leigh-pointer could you please provide more information... the idea behind "headless" modules is that they do not have any razor components (ie. no UI) - which means that they should not inherit from ModuleControlBase.

**Comment by leigh-pointer** [comment] 2024-08-14 09:44
@sbwalker
**Extension of DynamicForm Module via Headless Method**
I concur with the approach, but I'd like to elaborate on my experience. I'm currently utilizing the Headless method to extend the DynamicForm module. This method has recently introduced its own SDK, which facilitates the creation of components that can enhance the Toolbox functionality.
**Observations and Challenges**
The implementation works exceptionally well, particularly for Resources. However, while the workaround is effective, it doesn't feel entirely seamless. This is understandable given the complexity of the system.
**Positive Outcomes**
The ability to extend the framework is undoubtedly a significant advantage. Moreover, the capacity to further extend an existing extension is particularly exciting and opens up new possibilities for customization and functionality.
**Future Considerations**
As we continue to work with this method, it may be beneficial to explore ways to make the workaround feel more integrated and fluid. This could potentially enhance the overall user experience and development process.

![image](https://github.com/user-attachments/assets/d1cbfae1-6b21-4051-8aef-446a2de42288)

**Closed** 2024-08-27 11:58 UTC
