### ISSUE TITLE
[BUG] Administration: File Management - Unable to save permissions set on a folder

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4590] opened 2024-09-05 20:39 UTC
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
Unable to save permissions set on a folder

### Expected Behavior
ability to set the permissions after saving them to a folder

### Steps To Reproduce
Create a folder without any modified permissions
Edit the folder to add/remove permissions
Type Private
Notice no permissions are saved when you revisit the folder permissions settings.

### Anything else?
![image](https://github.com/user-attachments/assets/e568642e-1f93-4e8c-a23d-4effc772a15f)

when setting type of folder it is not updated as in I set this when created to "Public" with permissions for all users to view/browse the folder but wasnt applied on save.

Maybe resolved in 5.2.2 already?

**Comment by zyhfish** [comment] 2024-09-06 12:44
I can reproduce this with 5.2.1 official release but can't reproduce from the latest code in dev branch, I think this is already fixed.

**Comment by sbwalker** [comment] 2024-09-06 12:46
@thabaum are you saying you changed the Type from Public to Private?

**Comment by sbwalker** [comment] 2024-09-06 12:54
@zyhfish there are no PRs in 5.2.2 which relate to saving permissions... so I am wondering if this is an environment issue? When you said you can reproduce with 5.2.1 official release - how exactly are you running it (ie. locally? remotely? on IIS?)

**Comment by sbwalker** [comment] 2024-09-06 12:55
@thabaum can you please describe the environment where you are running Oqtane 5.2.1?

**Comment by zyhfish** [comment] 2024-09-06 13:11
Hi @sbwalker , you're right, I just tried latest code with IIS and can reproduce the issue, it should be an environment issue, let me try to analyze more.

**Comment by sbwalker** [comment] 2024-09-06 13:17
@zyhfish @thabaum is it only happening when saving permissions, or is it happening on any Update operation?

**Comment by zyhfish** [comment] 2024-09-06 13:31
with my current analyze result, the permission grid won't update the "_permissions" value after click on any checkbox. but when I attached debug from visual studio and debug into the PermissionChanged method, the value will be updated correctly the issue is gone away.

**Comment by sbwalker** [comment] 2024-09-06 14:55
@zyhfish @thabaum I believe this PR #4507 which was submitted last month by @leigh-pointer  most likely caused this new issue. The PR simply moved the logic from OnInitialized() to OnParametersSet() however this can have the side effect of the state of a component being re-initialized when a button is clicked - which would result in any changes being overwritten.

**Comment by sbwalker** [comment] 2024-09-06 16:01
I reverted #4507 - @zyhfish please test again to determine if this resolves the issue. If so, then the #4503 will need to be resolved in a different manner so that it does not impact other scenarios.

**Comment by sbwalker** [comment] 2024-09-07 15:19
@zyhfish @thabaum let me know if you have a chance to test #4594 to determine if it resolves the issue with permissions not saving in IIS.

**Comment by thabaum** [comment] 2024-09-07 23:05
@sbwalker sorry I have been very busy, I will have time Monday to review.  Thanks!

**Comment by thabaum** [comment] 2024-09-09 02:13
I have been doing some other testing with the file upload, it seems it does not always complete and the progress bar flickers up and down as it goes not reading end of file correctly.  This was with an mp3 file if it matters.  I should have time tomorrow afternoon and all day Tuesday to work these issues out and test things as needed.

**Comment by sbwalker** [comment] 2024-09-09 12:33
@thabaum the reported issue is related to permissions not being saved properly - which is completely unrelated to file uploading. Since the permissions issue seems to have difference behavior in different environments, I was hoping to get some independent testing confirmation of #4594. I have since received feedback through other channels that it does indeed resolve the issue in all environments - so I will close this issue. Thank you for reporting the original problem - based on the fact that configuration of permissions is such as core functionality, I believe a 5.2.2 maintenance will need to be published as soon as possible.

**Closed by sbwalker** 2024-09-09 12:33 UTC

**Comment by sbwalker** [comment] 2024-09-09 13:24
#4507 resolves the earlier issue #4503 is a more predictable manner. Basically, both #4503 and #4590 are a result of race conditions which can happen in different environments due to latency. When running locally in Visual Studio or even using a browser on the same IIS server where the app is hosted, there is minimal latency - so the component can collect all of its initial state and load properly. However if you are interacting with the app using a browser connected to a remote server the network latency is much higher and the component may get rendered before all of the initial state is fully loaded. In these scenarios you need to ensure that ALL state is loaded before allowing the UI to render. This can be done by introducing a simple boolean within OnInitialized to ensure all of the logic executes before rendering the UI.

**Comment by thabaum** [comment] 2024-09-09 15:15
@sbwalker thank you!  I will report the file management upload issue separately as it is indeed another issue I just didnt have time to create the issue.  I will do this today if not already created.
