### ISSUE TITLE
Two pages in one theme causing an error 

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#3926] opened 2024-03-01 00:37 UTC
I have a Theme with two Pages as follow 

1. Default 
2. Hero

Default does not have Hero Pane 
Hero contains a Hero Pane

I have the flowing setup 

The theme set in Site Settings is `Default`
The Home Page has the theme `Hero Page`
The Membership page has the theme `Default`

when I navigate from Home Page to Membership page I get the following error

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/ca5d8389-4d16-4db3-862b-dbbdff608f34)

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/291b9a16-cf2f-41bd-8e79-ce39dae6200a)

My understanding was that a Theme can have multiple pages??

**Comment by thabaum** [comment] 2024-03-01 03:04
@vnetonline which version are you using of Oqtane?  Multiple themes technically is not supported as the bootstrap may have issues with different versions, however in 5.1 we worked hard to resolve this issue recently.  I am hoping not many issues switching between themes anymore... but I am sure they can load or not load things if they are fighting for priority so to speak.

**Comment by vnetonline** [comment] 2024-03-01 03:58
I am not using multiple theme I have the one theme with two pages default and hero both under the same theme 

I am using 5.0.2

**Comment by leigh-pointer** [comment] 2024-03-01 07:40
@vnetonline you are correct, you can have multiple themes pages inside a theme.  This will not cause an issues as the stylesheets are loaded.
Back to the issue.  When you changed the Theme design in your page settings, make sure that the contain is selected.  This is my first thing to look at.
HTH

**Comment by vnetonline** [comment] 2024-03-01 07:44
The container is selected @leigh-pointer this worked in 5.0.0 but no longer working

**Comment by sbwalker** [comment] 2024-03-04 13:26
@vnetonline I believe this is working in 5.1.0

**Comment by sbwalker** [comment] 2024-04-02 20:21
@vnetonline should I close this issue as I cannot reproduce... or is there some more context to recreate the problem?

**Comment by vnetonline** [comment] 2024-04-02 20:23
Yup this is fixed in 5.1 @sbwalker

**Closed** 2024-04-02 20:24 UTC
