### ISSUE TITLE
[BUG] Can't edit site settings of other site, if the Url is not accessible

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4386] opened 2024-07-03 11:44 UTC
### Oqtane Info

Version - 5.1.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

I copied a Oqtane solution for testing the upgrade.
This solution has a main site and a sub-site.
The when copying the site it must run on another domain to test everything.
We adjusted the main sites URL during the copy process in the DB, but assumed we could adjust the sub-site domains later on in the UI: 

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/36dd6d40-97ac-4378-92ab-3cc562ec6bcb)

But this fails.
Basically the edit-button tries to go to the domain which is currently set on that site, so it's impossible to edit it if the domain doesn't work. 

### Expected Behavior

I should be able to edit site settings of a site which currently cannot be accessed - for any reason. Other reasons this could be needed:

1. The theme or container of the site could be corrupt - so I should be able to manage the site without "entering" the site.
2. The domain can't be accessed because it has an invalid name...
3. ...or because a firewall etc. was configured differently, so that exact name isn't available
4. Or the domain doesn't exist any more (could also be a sub-domain)

### Anything else?

I assume this is tricky to implement, because the site-admin probably always assumes "the current site is the site I'm working on" - so implementing this will probably take a bit more effort 😟

**Comment by sbwalker** [comment] 2024-07-09 12:38
@iJungleboy the API in Oqtane does not support cross-domain calls. If you are on www.site1.com which maps to SiteID=1 and you try to make an API  call to retrieve or save data for SiteID=2 you will get a 403 - Forbidden. For security reasons, the client application can only make API calls to its own SiteID. This is why when you click the Edit button in the Site Management UI it redirects you to the Url for the Site you wish to manage. This is by design - so I will close this issue.

**Closed by sbwalker** 2024-07-09 12:38 UTC
