### ISSUE TITLE
File/Folder management needs improvement

### ISSUE THREAD

**Issue by selvinfehric** [oqtane/oqtane.framework#1276] opened 2021-04-23 20:51 UTC
Most of the controllers are just simply calling repositories directly and doing CRUD operations. The issue with File/FolderController is that you can't easily extend file management functionality from the framework as controllers are doing too much logic. Service pattern could come in handy here, or if it is overkill for other controllers (and we want to keep code consistent in all controllers) then implementing FileManager in Infrastructure would be a good solution as we already have a few manager classes there.

The idea came from the fact that we are trying to integrate SyncFusion FileManager and would like to wire it up with Oqtane File/Folder management, access permissions, tenants, etc. If we would be able to call FileManager/FileService from our module, we would be able to reuse logic that is currently in File/Folder controllers including all private methods there.

I would like to know what is the plan for this part and if there isn't any I would create a PR with a proposed solution for this. 

Calling File/FolderService from Oqtane.Client is not possible as we have custom logic in our module in the server assembly. Using controllers directly from the module server-side doesn't sound like a good idea either.

**Comment by sbwalker** [comment] 2021-04-24 17:50
Oqtane is designed to be extensible so that the core framework does not need to be modified in order for you to accomplish yur goals. If you do not like the default File Manager implementation you are free to create your own custom file manager which suits your specific needs ( ie. if you want to use a third party component such as Syncfusion ). The framework makes it very simple to replace a default module with your own custom module. In your own module you have the full freedom to create your own APIs, repository, etc...

**Comment by selvinfehric** [comment] 2021-04-25 07:45
I understand, and that is exactly what we are doing. But I am not sure why would not you make framework more extendable. As it is now, whole file management logic in oqtane is placed in controllers and you cannot extend it in your own module. We would like to use framework feature but we can't find a point of integration. That is why I suggested this file management code from controllers to be moved to some kind of service layer so custom modules can reuse it. I would be glad to contribute if that fits into framework philosophy.  If not, then I am sorry for bothering you and this issue can be closed.

**Comment by sbwalker** [comment] 2021-04-25 18:21
Just for clarification, are you talking about the File Management module in the Admin Dashboard or the FileManager shared component which is used in a variety of the core modules such as Site Settings, User Profile, etc... ?

Either way, Oqtane uses a standard client/server architecture where there is a client application and server application and they communicate via HTTP services. It is architected this way to enable the framework to run on Blazor Server or Blazor WebAssembly. For this reason the business logic resides in the Web API controllers, as that is the public API for UI component integration. UI components should never interact with backend resources such as the database directly as that would break the client/server boundary and would not run on Blazor WebAssembly.

**Comment by selvinfehric** [comment] 2021-04-26 11:09
I am talking about business logic in Web API controllers. I am suggesting to move that logic one layer behind controllers, so it goes something like: Web API controllers (File/FolderController) -> services (File/FolderServices or FileManager) -> repositories (File/FolderRepository) and its interfaces (everything placed in Oqtane.Server). In this way, anyone could use File/FolderService (FileManager) in its own custom module (e.g. from MyFileManagementModule.Server I could extend File/FolderService or FileManager class or just use it there from my own controllers). Extending current File/FolderControllers where the business logic currently resides is impossible. 

I am not talking about the UI part and Blazor components, etc. I just want my own UI for FileManager, but to use framework capability of storing files/folders and access permissions without needing to copy them and sync them when Oqtane gets updates. And I think that would be helpful generally for other users and other modules. I don't see a point in keeping business logic in controllers, especially not in private methods.

**Comment by sbwalker** [comment] 2021-04-26 12:40
Could you please answer my earlier question - are you talking about the File Management module in the Admin Dashboard or the FileManager.razor shared component which is used in a variety of the core modules such as Site Settings, User Profile, etc... ?

**Comment by selvinfehric** [comment] 2021-04-26 12:55
I am talking about File Management module in the Admin. But not sure what difference does it make as they are both using File/Folder client services that access Web API controllers that I am suggesting to be refactored?

**Comment by sbwalker** [comment] 2021-04-27 12:54
I just wanted to make sure I was on the same page in terms of the specific framework feature you were referring to as different features have different extensibility options. So just to be clear, you would like to create your own File Management module which could replace the default File Management module in your own installation. Your File Management module would utilize a third party component ( ie. Syncfusion ) for the UI. Your module would adhere to the client/server architecture and would only allow the front-end to interact with the back-end using HTTP services ( ie. Web API ). However the current Oqtane File/Folder API does not satisfy your needs ( it would be helpful to understand why), so you would like to be able to create your own custom File/Folder API. However you would like to be able to re-use the logic which is currently embedded in the Oqtane File/Folder API within your own custom File/Folder API so you are suggesting moving this logic to another layer. In order to avoid breaking changes in the Oqtane File/Folder API it would have to retain the exact same contract and functionality that it has currently. But your custom File/Folder API may have additional requirements so there may be a need for new methods/logic. However it is unclear how the core framework would actually be able to regression test these new methods/logic in subsequent releases as it would not use the code itself. So I guess my question is why it would not be possible for your File Management module to use the Oqtane File/Folder API for the methods which are applicable to your use case, and use your custom File/Folder API for anything which is not supported by the core framework?

**Comment by selvinfehric** [comment] 2021-04-27 18:05
Yes, your understanding is correct. The reason why we need custom API is not because oqtane File API is not enough, but because Syncfusion File Manager UI component has specific requirements for the API endpoint it access. So in our custom Syncfusion File Management module we would provide Syncfusion API and use core framework features. Idea of calling oqtane File API from custom API does not sound like the best option as we need to make controller to controller calls. On the other hand, we also might need to extend some core features in the future. I started preparing a PR so I can submit it in the next few days for you just to quickly review if that is the way you want to go forward.

**Comment by sbwalker** [comment] 2021-04-27 21:23
I realize you are not going to be pleased with this response, but I would prefer to not refactor the File/Folder API logic into another layer. The reason for this is because one of the general philosophies in Oqtane is to ensure backward compatibility. It attempts to achieve this goal by only including specific aspects of the framework as part of the public API. This includes the UI component interfaces, models, and API controllers. It does not include the repository layer ( which is why we advise people from writing  code which interacts with the repository directly ). Abstracting the File/Folder logic from the Controller into another  layer is essentially creating another public API which would need to be supported from a backward compatibility perspective. And this is not an approach I would endorse at this stage. So I would recommend you implement your own custom File/Folder API for your custom File Management UI - even if it means replicating some of the logic from the core File/Folder API.

**Closed** 2021-04-28 23:35 UTC
