### ISSUE TITLE
Issue: User Profile > Profile Tab - Input Fields are all TextArea Fields

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3412] opened 2023-10-20 16:05 UTC
As you can see below all the input fields show up as textarea fields.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/cd751066-826d-406e-ad66-d1125cf1813b)

**Comment by sbwalker** [comment] 2023-10-20 16:45
@thabaum please explain the steps to reproduce as there are multiple user profile components in the framework. I am unable to reproduce in a clean install or upgrade of 4.0.6.

**Comment by thabaum** [comment] 2023-10-20 22:18
I downloaded version 4.0.6 and opened the solution in VIsual Studio, run the program, created host user on install, selected HOST for viewing Host profile information, Selected User Profile > Profile tab.

**Comment by thabaum** [comment] 2023-10-21 00:26
@sbwalker Here is the issue as I thought, I just needed to create/view a profile configuration setting:

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/ff71287b-898f-480f-8c47-8fd1fff32734)

Rows are defaulted to "0"

Which I think making them all "1" makes sense and "0" can be used for another purpose unless intended now to be one.  But if set to 0 it does not equal 1 so this is why my PR fixes it, for all installations.

Or rows are going to need to be updated to 1 , and 1 should be default.

0 could be used for something else but my submitted PR ensures anything 1 or less is a normal input field.

Oqtane would need to check on upgrades if any fields have rows 0 and set them to 1 otherwise to fix this issue.

**Comment by thabaum** [comment] 2023-10-21 01:58
@sbwalker I am using MSSQLLocalDB if that makes any difference.  I have attempted working with the migration script 4000601_AddProfileRows passing all 4 params but still no luck.  So not saying it doesnt work in your environment if it relates to the issue possibly.

**Comment by thabaum** [comment] 2023-10-21 02:31
@sbwalker fixed with PR #3421 

Only way I was able to make this work properly with new sites and creating sites was to set the default "Rows" value in the "Profile" model class.

**Comment by sbwalker** [comment] 2023-10-21 13:53
@thabaum you are correct that this is a problem in 4.0.6. It only occurs on new installations - not on upgrades. The upgrade migration has logic to initialize the new Rows field to "1". However for new installations, the site template logic does not explicitly set the value for Rows - so because it is an int, it is assigned a value of "0". And because the User Profile is using conditional logic of Rows == 1 it results in the UI displaying textarea fields rather than standard input fields. This results in the UI rendering you reported, but it does not affect the actual behavior of the User Profile - the values are still saved properly so there is no risk of data loss. This does need to be fixed however it can also be resolved in a 4.0.6 installation by setting the Rows value for each Profile to "1". So this is not a show stopper issue.

**Comment by thabaum** [comment] 2023-10-21 15:44
@sbwalker I targeted net8 branch with the fixed up PR and you are right this is not a showstopper, easy to fix if an issue for an admin until next release updates.  Very cool enhancement I had not tested yet to allow textarea elements to be included into profiles.  Thank you!

**Comment by thabaum** [comment] 2023-10-21 15:59
@sbwalker sorry I just read up on the PR.  I can work on a pull request today for this issue as discussed in the PR.  Although my approach does work, the info you provided gets to the root of site creation which is the logic I was digging around for.

**Comment by sbwalker** [comment] 2023-10-23 16:19
resolved in #3423

**Closed by sbwalker** 2023-10-23 16:19 UTC
