### ISSUE TITLE
Bug: Uninstalling A Module While Used On A Page Causes Errors in Visual Studio 2022 - 5.1.0

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3945] opened 2024-03-04 18:06 UTC
### Description

Not sure if uninstalling modules was supported before but after trying to uninstall a couple vendor modules from the marketplace Oqtane.Server Visual Studio project ends on errors and wont startup again with errors.

### Steps to reproduce
1. Install a module from the marketplace or...
2. Place the module on a page.
3. Navigate to the Administration Dashboard.
4. Select Module Management.
5. Uninstall the module that is still being used on a page.
6. Notice the step through errors in Visual Studio.

###  Additional Context
So far we have added to this discussion some logs and test results from both the Oqtane.Blog and 2sic modules with I believe similar results.  If not on a page , installed then uninstalled, all works as expected. I have not tested deleting a module after deleting all module instances manually.  I will update this if I do.

### Screenshots

After installing then uninstalling 2sic module for one of the error examples and then trying to start the Oqtane.Server project:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/6c129175-09f9-4136-9bc0-f4d58bf7bc2e)

**Comment by sbwalker** [comment] 2024-03-05 17:05
@thabaum it appears that the 2SXC module is not cleaning up all of its references. Please find the 2SXC log file in the Oqtane.Server\Packages folder and post its contents in this thread. It will include the manifest of files which were installed as part of the nuget package. This is how Oqtane determines which files need to be removed.

**Comment by thabaum** [comment] 2024-03-05 17:53
@sbwalker it looks like this maybe resolved in latest release and I tested with the Oqtane Labs modules available and no issues uninstalling on todays current branch, closing issue.

**Comment by thabaum** [comment] 2024-03-05 17:59
@sbwalker I am going to reopen this with further inspection, I generated a similar issue with the blog module.  It happens when there is still a module on a page being used.  Otherwise I think it works ok?

**Comment by sbwalker** [comment] 2024-03-05 18:12
This will require some more investigation. The ModuleDefinitionController Delete method contains the following logic to delete the Module/PageModule instances which may exist:

```
                // remove PageModule and Module
                List<Models.Module> modulesToRemove =  _modules.GetModules(moduledefinition.SiteId).Where(m => m.ModuleDefinitionName == moduledefinition.ModuleDefinitionName).ToList();
                foreach (Models.Module moduleToRemove in modulesToRemove)
                {
                    // Get the PageModule items associated with the Module item to be removed
                    List<PageModule> pageModulesToRemove = _pagemodules.GetPageModules(moduledefinition.SiteId).Where(pm => pm.ModuleId == moduleToRemove.ModuleId).ToList();

                    foreach(PageModule pageModule in pageModulesToRemove)
                    {
                        // Remove the PageModule item
                        _pagemodules.DeletePageModule(pageModule.PageModuleId);
                    }

                    // Remove Permissions
                    _permissions.DeletePermissions(moduledefinition.SiteId, EntityNames.Module, moduleToRemove.ModuleId);

                    // Remove the Module item
                    _modules.DeleteModule(moduleToRemove.ModuleId);
                }
```

However this is not going to work properly in a multi-tenant environment where site information could be stored in different isolated databases. In fact, the "In Use" column in the main display is also not 100% accurate as it only displays if the module is in use in the current Site - not if it is in use in any site in the entire installation. 

My initial reaction is that a module should be able to be uninstalled... and if that module is in use on any site in the installation, the framework will need to include defensive logic to catch the condition where the module may not actually exist - and display a friendly error message.

**Comment by mdmontesinos** [comment] 2024-03-11 11:19
Also facing this issue when trying to unistall 2sic modules when they were included in a page.

**Comment by sbwalker** [comment] 2024-03-11 16:38
duplicate of #3947

**Closed by sbwalker** 2024-03-11 16:38 UTC
