### ISSUE TITLE
JavaScript file function called before the Custom Module loads the file

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#766] opened 2020-09-30 21:49 UTC
When loading JavasScript file through Index Page on Custom Module the component seems to be loading before the JavaScript file function is called. Thus causing this error:

`Error: Microsoft.JSInterop.JSException: Could not find 'BlazorInputFile' in 'window'. Error: Could not find 'BlazorInputFile' in 'window'.`

`Error: Microsoft.JSInterop.JSException: Could not find 'ChartJsInterop' in 'window'. Error: Could not find 'ChartJsInterop' in 'window'.`

Code in my Index Page
```csharp
    public override List<Resource> Resources => new List<Resource>()
        {
            new Resource { ResourceType = ResourceType.Script, Url = ModulePath()+"BlazorInput/inputfile.js" },
            new Resource { ResourceType = ResourceType.Script, Bundle="ChartJs",  Url = ModulePath() +"ChartJsBlazor/moment-with-locales.min.js" },
            new Resource { ResourceType = ResourceType.Script,Bundle="ChartJs", Url = ModulePath() +"ChartJsBlazor/Chart.min.js" },
            new Resource { ResourceType = ResourceType.Script,Bundle="ChartJs", Url = ModulePath() +"ChartJsBlazor/ChartJsBlazorInterop.js" },
            new Resource { ResourceType = ResourceType.Stylesheet,  Url = ModulePath() +"ChartJsBlazor/ChartJSBlazor.css" }
        };
```

**Comment by sbwalker** [comment] 2020-10-01 15:14
Please share the ChartJsBlazorInterop.js file contents so it is possible to see how it is declared. Please also share how your code calls the JavaScript methods via JSInterop. Does your module component implement  the OnAfterRenderAsync(bool firstRender) event? If so, does it call the ModuleBase event which handles loading the JavaScript: await base.OnAfterRenderAsync(firstRender)

**Comment by hishamco** [comment] 2020-10-01 15:25
@PoisnFang could you please provide a minimal repo, so it's easier to reproduce the issue

**Comment by PoisnFang** [comment] 2020-10-01 15:31
@sbwalker I am using the ChartJsBlazorInterop.js file that is included with the nuget package. I do not call JSInterop, the nuget packages call JSInterop.

**Comment by PoisnFang** [comment] 2020-10-01 16:43
@hishamco Here is a small example repo https://github.com/PoisnFang/PoisnFang.ThirdParty

**Comment by hishamco** [comment] 2020-10-01 21:11
Hope to have a look soon, coz I have many localization stuff to do ;)

**Comment by sbwalker** [comment] 2020-10-08 13:46
Closing this item as it is explained in #764

**Closed by sbwalker** 2020-10-08 13:46 UTC

**Comment by PoisnFang** [comment] 2020-10-08 19:24
@sbwalker I guess I understand closing this issue, however its still not really resolved.

**Comment by sbwalker** [comment] 2020-10-08 21:40
There are currently 2 resolutions to your problem:

1. Rewrite your module to use chart.js directly exactly like DNF.Project. This works fine because the module takes responsibility for declaring its own JavaScript.
2. Use the third party component but use the IHostResources method for declaring the JavaScript. This is the only way to handle components which do not take responsibility for declaring their own JavaScript.

In .NET 5 there will also be an additional method available - however the author of the third party component will need to modify their component to use the new JavaScript registration method. Once they do this and the component takes responsibility for managing its own JavaScript then you will be able to consume it in your module and it should work fine.
