### ISSUE TITLE
Writing incorrect file paths (on linux)

### ISSUE THREAD

**Issue by SPSeanLong** [oqtane/oqtane.framework#383] opened 2020-04-16 21:19 UTC
OS: Ubuntu 19

File paths are being generated incorrectly, folders are being created with name "html\content\Tenants\2\Sites\1\Images" at the root level

![image](https://user-images.githubusercontent.com/32595348/79507485-d120c900-8005-11ea-81a8-e324876a76c8.png)

Expecting:
file path: /var/www/iotataukappa/html/Content/Tenants/2/Sites/1/Images/

Actual:
file path: /var/www/iotataukappa/html\Content\Tenants\2\Sites\1\Images\\/

Running debug localhost on windows issue does not occur

**Comment by sbwalker** [comment] 2020-04-16 21:37
I dont think anyone has attempted to run on Linux yet. I believe there will be quite a few file system path issues to resolve.

**Comment by SPSeanLong** [comment] 2020-04-17 01:36
I have started working on resolving this. Somehow broke images along the way. I plan to continue down the path of linux roadbumps

**Comment by SPSeanLong** [comment] 2020-04-17 20:32
I believe this is resolved and successful in for both OS platforms in my fork. Should I submit it here?

**Comment by sbwalker** [comment] 2020-04-18 15:11
Thank you for submitting the PR. I think supporting Linux is a valuable improvement. In reviewing the PR I can see that the changes are quite widespread and it was most likely not possible to regression test all scenarios. In particular I am concerned about areas where folder paths are stored in database fields. For example the Folder table has a Path field where the value is expected to be stored in a format such as "Users\1\". It appears that your PR is removing the path delimiter in some cases so I am not sure how this would work?

**Comment by SPSeanLong** [comment] 2020-04-18 16:19
I agree with your point regarding regression testing & due to that, the changes I thought were safe are certainly not worth the risk. I will reedit & ensure all the results are the same. Path.Combine(...," ").TrimEnd(' ') will provide the desired delimiters

**Comment by chlupac** [comment] 2020-04-18 17:34
@sbwalker Is leading \ in folder name necessary ? I do not like it, it's redundant

**Comment by sbwalker** [comment] 2020-04-18 17:48
The trailing slash could be removed as long as all of the use cases which rely on it are fixed and tested. The internal slashes within the path cannot be removed as they are used to define the hierarchy and we do not want to have to dynamically generate the full folder path. I assume the internal slashes can be replaced at runtime?

**Comment by jimspillane** [comment] 2020-04-18 17:56
For the internal slashes, you may want to consider using the forward slash (/) for path persistence since it works on both Windows and Linux.  I agree the trailing slash could be removed.

The _Remarks_ include some guidance on applications that run on multiple platforms.
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=netframework-4.8#remarks

**Comment by SPSeanLong** [comment] 2020-04-18 18:42
I think at runtime everything being combined should pass through a Path.Combine again which would add expected slashes where needed. However due to the amount of testing needed to ensure there wasn't any breaking changes I am altering the project to match the original. A more methodical removal or switch to forward slash might be worth an effort in the future

**Comment by hishamco** [comment] 2020-04-21 16:35
@sbwalker please enable CI/CD for the repo,  I can write a unit tests for this use case

**Comment by SPSeanLong** [comment] 2020-04-23 15:50
Anything I can do to have the PR #387 accepted ?

**Comment by sbwalker** [comment] 2020-04-23 16:15
Sorry @SPSeanLong  I was confused by your last comment about "altering the project to match the original" - I was not sure if you were satisfied with your own testing and that this PR was ready to be merged.

**Comment by SPSeanLong** [comment] 2020-04-23 22:32
Not sure how to properly squash the commits but I do feel the PR as it is now is complete. Any delimiters hardcoded are now OS independent. Any location delimiters have been used will remain unchanged. 

There is a new PathCombine function in utility that can be used to easily append an os independent delimiter & it also avoids possible issue of Path.Combine dropping segments (normally when multiple "root paths" only 1 is kept. Now they are joined).

**Comment by hishamco** [comment] 2020-04-23 22:42
> Not sure how to properly squash the commits

https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by SPSeanLong** [comment] 2020-04-24 02:35
Thank you @hishamco but that link includes me being upto date which the PR no longer is. I will rebase my code after accepted (if that is achieved)

**Closed** 2020-05-05 14:11 UTC
