### ISSUE TITLE
pages randomly display panes out of order and therefore modules are moved randomly on a page

### ISSUE THREAD

**Issue by rrourk12** [oqtane/oqtane.framework#4258] opened 2024-05-14 17:53 UTC
### Oqtane Info

Version - 5.1.1
Render Mode - Interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
on our home page  https://scpafl.org the page modules are as follows
1	91	HomePageQuickSearch	Top Full Width		1
1	60	ANNOUNCEMENTS		Right 50%		2
1	44	QuickLinks		Bottom Full Width	3
1	68	contact us		Center 50%		4
1	61	IMPORTANT DATES		Left 50%		5
1	49	PropertyStatistics	Bottom Full Width	9
1	117	Footer			Bottom Full Width	11

at random times the property statistics is at the top and the HomePageQuick search is below it or at the bottom,
a check of the database shows that they are still in their assigned pane and position yet they appear in random orders

### Expected Behavior
always render the panes in proper order

### Steps To Reproduce
use a page with unauthenticated users, it seems to happen more frequently in Edge vs Chrome-- at times I can have a Chrome window (logged in) and do a private browser in edge (new session) and 1 will be scrambled, one will not-- recycling the process doesn't fix it.  I must move a module around to a new location and back to fix it (yet the database will remain correct )

### Anything else?
This behavior did not occur in 4.0.6 -- we migrated to 5.1.1 and it started

**Comment by sbwalker** [comment] 2024-05-16 19:17
@rrourk12 thank you for reporting... however I am not sure how to reliably reproduce the problem you are reporting. I have been unable to get it to happen locally.

**Comment by sbwalker** [comment] 2024-05-19 13:32
@rrourk12 I am going to close this issue as I am unable to reproduce the problem. One unrelated item which I would suggest is that if you are building a website with public facing pages you should use the Static render mode (the default in Oqtane 5.1). Interactive render mode is best for internal facing web applications where the majority of users are authenticated. Note that this recommendation is not actually related to Oqtane - it is related to the run-time behavior of Blazor and is the reason Microsoft added the static rendering capability in .NET 8.

**Closed** 2024-05-20 12:55 UTC
