### ISSUE TITLE
Oqtane 4.0 - Submenus not rendering all the time.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2899] opened 2023-06-16 07:52 UTC
This is a hit and miss issue, sometime the submenus donot render, yet on source inspection the submenus markup is there. 

![Submenu](https://github.com/oqtane/oqtane.framework/assets/9447612/f6a4ee57-063d-48ab-953c-83283c95238f)

**Comment by sbwalker** [comment] 2023-06-19 14:27
thank you for submitting the issue... I am guessing this has something to do with the JavaScript event handler not being registered

**Comment by sbwalker** [comment] 2023-06-19 16:40
I am not able to reproduce... do you have more specific instructions?

**Comment by leigh-pointer** [comment] 2023-06-19 17:57
@sbwalker It seems to happens when you move between pages with different themes set per page.  I first saw it with RocketFuel so I created a standard external Theme using the templates.  I have reproduced on Edge and FireFox.

**Comment by sbwalker** [comment] 2023-06-21 21:22
This can happen if you are using multiple themes on your site, and the themes are not using "bootstrap.bundle.min.js" from the same exact source location (ie. src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"). Basically, multiple versions of "bootstrap.bundle.min.js" will be loaded into the page head because the primary way that the system is able to identify JavaScript libraries is based on their src="" location (which are different in this case. A secondary way that a JavaScript library can be identified is based on the Bundle property on a Resource object. For example, if all "bootstrap.bundle.min.js" registrations used a Bundle identifier of "Bootstrap" then the system would be able to determine that the reference is the same even if it comes from a different location. There is also a risk in using this approach as if one theme is using Bootstrap 4.x and another is using Bootstrap 5.x but they both specify a Bundle of "Bootstrap", the system will not realize they are different. The reality is that using using different themes in the same site is problematic and most likely the framework should do a full server refresh of a page when this scenario is encountered.

**Comment by sbwalker** [comment] 2023-06-22 18:38
this is resolved by #2921

**Closed by sbwalker** 2023-06-22 18:38 UTC
