### ISSUE TITLE
Module Custom CSS not loading when navigating via Module routes

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#665] opened 2020-07-24 20:08 UTC
When I am inside a module and navigating via links to locations inside the module my custom CSS files are not setup because the ProcessModule function is not called in the site router

**Comment by sbwalker** [comment] 2020-08-10 19:59
I believe this is because you are using a different method for module development. By default Oqtane relies on each distinct module UI to be its own razor component and based on this model it can rely on the standard razor component life cycle events. For the custom development approach you are attempting to follow I would suggest that you would need to identify ALL of your static resources in your single razor component. This will reduce the benefit of lazy loading static resources on demand but it is another of the tradeoffs of using this approach.

**Comment by PoisnFang** [comment] 2020-08-14 18:25
I have my own ModuleBase class that is inherited, I added this in to load my CSS.
```csharp
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            await base.OnAfterRenderAsync(firstRender);

            if (firstRender)
            {
                if (Resources != null && Resources.Exists(item => item.ResourceType == ResourceType.Stylesheet))
                {
                    var links = new List<object>();
                    foreach (Resource resource in Resources.Where(item => item.ResourceType == ResourceType.Stylesheet))
                    {
                        links.Add(new { rel = "stylesheet", href = resource.Url, type = "text/css", integrity = resource.Integrity ?? "", crossorigin = resource.CrossOrigin ?? "", key = "" });
                    }
                    var interop = new Interop(JSRuntime);
                    await interop.IncludeLinks(links.ToArray());
                }
            }
        }

```

**Comment by sbwalker** [comment] 2020-08-14 19:06
Basically you migrated the framework logic into your module, which is a perfectly good solution for your use case. The default development module for Oqtane abstracts these details from the developer to simplify the development effort - but since you are following your own development approach you need to do a bit of extra work ( but are still able to leverage the core framework services ). If you don't mind I am going to close this issue, as it is not really an "issue".

**Comment by PoisnFang** [comment] 2020-08-14 19:15
Correct its the same thing that the Module Base does to load the JS resources. Except I have to do it with CSS. I still think is an 'issue' but you can close it for now. I will be looking deeper into later to see how it can affect other developers that are not developing the same way I am. And to answers a few questions I have, like "Why not just load the CSS and JS the same way in the module?"

**Comment by sbwalker** [comment] 2020-08-14 19:46
Sorry... based on your comment above I took a closer look at your solution and there is a problem. There is an important reason why JS is treated differently than CSS. Once a JS library is loaded into a web page for a site it is never unloaded - even if you removed the reference to the JS library from the DOM it would still be loaded. As a result of this, it is not necessary to unload JS references. CSS references however need to be managed much more granularly - they need to be loaded and unloaded based on the needs of the web page or else there is potential they will clobber each other due to their cascading nature. The best example of this in Oqtane is themes... Oqtane relies on Bootstrap which defines a specific set of styles. You can apply the Oqtane theme to Page1 of your site and the Blazor theme to Page2 of your site. If Oqtane did not have logic to remove/add the CSS when you navigated from Page1 to Page2 and vice versa, you would end up with some very unexpected behavior as you would have 2 references to CSS files defining the same classes.

**Comment by PoisnFang** [comment] 2020-08-14 20:45
Right which is why I have to load my CSS the way I do, because my Module acts like it has its "own" pages.

**Comment by sbwalker** [comment] 2020-08-16 23:15
To clarify one aspect of my earlier explanation... the result of loading CSS using the code you posted above is that when you navigate to a page containing your module, a CSS reference will be added to the DOM - and that CSS reference will never be removed from the DOM, even if you navigate to a different page which does not contain your module. You may not notice any visible effect as a result of this; however if every module utilized this approach you can imagine how many CSS references would accumulate in the DOM over time as you interacted with a site - creating a higher likelihood of CSS clashes and causing performance issues. The default module loading behavior in Oqtane does not suffer from this issue - it takes care of the removal of unnecessary CSS references so that only the necessary CSS references are included for a specific page.

**Comment by PoisnFang** [comment] 2020-08-16 23:26
Hmmm, I will have to circle back to this in my code and map out the exact problem and proper solution. Thanksba lot for the feedback and explanation.

**Comment by sbwalker** [comment] 2020-08-28 15:48
Closing as this is not really an "issue"

**Closed by sbwalker** 2020-08-28 15:48 UTC
