### ISSUE TITLE
[BUG] Installation Issue on  Linux / nginx

### ISSUE THREAD

**Issue by michalss** [oqtane/oqtane.framework#4893] opened 2024-12-03 17:02 UTC
### Oqtane Info

Version - 6.0.0
Render Mode - Interactive
Interactivity - Server
Database - SQL Server

### Describe the bug
```
Request finished HTTP/1.1 GET https://domain.eu/_blazor?id=p6kNevxfqq0VV20n1FlkWg&_=1733245332119 - 200 29 application/octet-stream 23.2499ms
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
      System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
         at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
         at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at Oqtane.Services.ServiceBase.GetJsonAsync[T](String uri) in C:\Source\Projects\oqtane.framework\Oqtane.Client\Services\ServiceBase.cs:line 163
         at Oqtane.Services.DatabaseService.GetDatabasesAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\Services\DatabaseService.cs:line 20
         at Oqtane.Installer.Installer.OnInitializedAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\Installer\Installer.razor:line 171
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'X6CcdVtDlEj7Smp7xd2Mpg9wtgbZsnkUhmZeXPnvkEw'.
      System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
         at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
         at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at Oqtane.Services.ServiceBase.GetJsonAsync[T](String uri) in C:\Source\Projects\oqtane.framework\Oqtane.Client\Services\ServiceBase.cs:line 163
         at Oqtane.Services.DatabaseService.GetDatabasesAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\Services\DatabaseService.cs:line 20
         at Oqtane.Installer.Installer.OnInitializedAsync() in C:\Source\Projects\oqtane.framework\Oqtane.Client\Installer\Installer.razor:line 171
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'X6CcdVtDlEj7Smp7xd2Mpg9wtgbZsnkUhmZeXPnvkEw'.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
### Steps To Reproduce
just download it from release and try to install it

### Anything else?
nginx version: nginx/1.20.1
Rocky Linux 9
```
.NET SDK:
 Version:           9.0.100
 Commit:            a2bc464e40
 Workload version:  9.0.100-manifests.6bf02610
 MSBuild version:   17.12.7+a2bc464e4

Runtime Environment:
 OS Name:     rocky
 OS Version:  9.5
 OS Platform: Linux
 RID:         rocky.9-x64
 Base Path:   /usr/lib64/dotnet/sdk/9.0.100/

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       a2bc464e40

.NET SDKs installed:
  8.0.111 [/usr/lib64/dotnet/sdk]
  9.0.100 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.11 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
 ```

**Comment by sbwalker** [comment] 2024-12-03 17:27
@michalss you have not provided any details of the environment where you are trying to install the software. Did the follow the directions in the documentation: https://docs.oqtane.org/guides/installation/index.html

**Comment by leigh-pointer** [comment] 2024-12-03 17:35
@Shaun ***@***.***>the environment is linux

NGINX Rocky Linux 9
________________________________

**Comment by sbwalker** [comment] 2024-12-03 17:40
Thank you @leigh-pointer - I missed that. There are instructions for Linux here:  https://docs.oqtane.org/guides/installation/index.html

**Comment by thabaum** [comment] 2024-12-04 20:21
Hi @michalss, 

Thank you for reaching out! Please review the links below and let us know how they help or if there are any gaps we can address:  

1. **[GitHub Discussion #3695](https://github.com/oqtane/oqtane.framework/discussions/3695)**  
   This lengthy discussion documents the process of resolving Linux/Apache/Ubuntu setup issues and may provide insights for your scenario.

2. **[Oqtane Documentation: Linux-Ubuntu-Apache-MySQL Installation Guide](https://docs.oqtane.org/guides/installation/linux-ubuntu-apache-mysql.html)**  
   This guide was created based on the above discussion. It also includes links to additional resources, such as:  
   - [Microsoft's Guide on Deploying ASP.NET Core on Linux with Nginx](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-9.0&tabs=linux-ubuntu)

Unfortunately, a guide for deploying Oqtane on Linux with Nginx has not yet been created, as we haven’t had detailed discussions or contributions in this area.  

We encourage any contributions to improve our documentation, even if it’s just creating an issue to highlight steps or challenges you encountered. Every bit of information helps the community and makes future deployments smoother for everyone.

I’ve personally donated significant time and effort to document these guides and assist the Oqtane community. If you’d like further assistance or encounter specific issues, I’d be happy to help. Let me know how I can assist further!

Thank you

**Comment by thabaum** [comment] 2024-12-04 20:28
@michalss FYI:  I created an issue in our docs to help assist with creating future documentation here: https://github.com/oqtane/oqtane.docs/issues/100

Any help here I will try to generate a docs installation guide page for this unless you can contribute one ;)

**Comment by zyhfish** [comment] 2024-12-11 14:44
I tried to install on WSL with nginx/postgresql and it works fine:
![image](https://github.com/user-attachments/assets/9d0b2bdb-78ec-438c-afc5-70883b270672)

**Comment by sbwalker** [comment] 2024-12-19 20:27
Closing as this issues seems to be related to a very specific environment configuration which is very difficult to reproduce

**Closed by sbwalker** 2024-12-19 20:27 UTC
