### ISSUE TITLE
Error during Upgrade from 4.05 to 5.0.2

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#3980] opened 2024-03-12 07:00 UTC
I am having trouble trying to upgrade from version 4.0.5 to 5.0.2

First, I had a couple of files missing, namely being 

Microsoft.Extensions.Options
Microsoft.Extensions.Configuration.Binder

So I uploaded these. Now I am getting the following error in the log

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Server.Program.Main(String[] args)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Server.Program.Main(String[] args)

in the browser, I get the following 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/86836c22-9ace-4aef-88a3-fce17b26f707)

has anyone encountered this and what the fix is ?

**Comment by vnetonline** [comment] 2024-03-12 09:22
How do I identify which ones are framework assemblies ??

**Comment by leigh-pointer** [comment] 2024-03-12 09:30
@vnetonline The easiest thing to do is 

- zip up your current install.
- Delete **everything** in the folder except for your installed themes and modules and appsettings.config.
- Copy files from the 5.0.2 install package to the folder.

if you really want to know they compare folder contents. My suggested way worked for me.

**Comment by thabaum** [comment] 2024-03-12 14:25
Do we need to suggest an upgrade path in documentation that works?

**Comment by sbwalker** [comment] 2024-03-12 14:34
@thabaum this only seems to happen in major .NET version upgrades ie. .NET 7 to .NET 8. And it does not happen in all environments. For example, I have never experienced a problem in upgrading my Microsoft Azure environments.

**Comment by thabaum** [comment] 2024-03-12 14:36
@sbwalker I will try to reproduce it this week as I am curious, I could not have this an issue it would freak me out.  It can be a known potential issue in docs.

**Comment by sbwalker** [comment] 2024-03-12 15:19
@thabaum Oqtane does not clean up any legacy files as part of the uograde (as you are essentially just unzipping the contents of a ZIP package into a folder). The old files can sometimes cause issues - even if they are no longer used by the framework. Not sure why.

**Comment by thabaum** [comment] 2024-03-12 16:56
@sbwalker Should the files be checked if exist and delete any "obsolete" files during the Oqtane upgrade process?  We would need to review all files from v2 to last version that should not exist anymore and remove them?  5.1 may have issues like this since a lot of files are being moved is why I raise this concern.

A list of which files that may need manually deleted would help here in documentation for when these types of issues happen.

So comparing the 5.0.2 release to the files of Oqtane installation after upgrade should let us know now which files could be an issue.

**Comment by vnetonline** [comment] 2024-03-12 21:10
Okay @leigh-pointer I have done what you suggested, and now I am getting the below error. 

```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'Oqtane.Infrastructure.DatabaseManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Oqtane.Server.Program.Main(String[] args) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Program.cs:line 18
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'Oqtane.Infrastructure.DatabaseManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Oqtane.Server.Program.Main(String[] args) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Program.cs:line 18
```

**Comment by sbwalker** [comment] 2024-03-12 21:17
@vnetonline I am confused by your statement "First, I had a couple of files missing namely being Microsoft.Extensions.Options, Microsoft.Extensions.Configuration.Binder". How is it possible that you had "files missing"? Can you please provide the exact steps you used to perform the upgrade. And can you also share whether or not your version of Oqtane is customized, or if you may have custom modules or themes which are part of your installation.

**Comment by vnetonline** [comment] 2024-03-12 22:23
@sbwalker i have not customised I had 4.0.5 running following are the steps I follows

1. Stoped the site 
1. Downloded the  [Oqtane.Framework.5.0.2.Upgrade.zip](https://github.com/oqtane/oqtane.framework/releases/download/v5.0.2/Oqtane.Framework.5.0.2.Upgrade.zip)
2. Unziped it and extracted it in my website folder
3. Started the site 
4. Navigated to the site in the browser and got the following message

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/41a7c452-f596-406d-9fba-2a1821f3efb0)


5. looked at the output in the logs folder because I have the following web.config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Oqtane.Server.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="outofprocess" />
    </system.webServer>
  </location>
    <system.web>
        <customErrors mode="Off" />
    </system.web>
    <system.webServer>
        <httpErrors errorMode="Detailed" />
    </system.webServer>
</configuration>
```

Note: my hosting provider suggests torun Oqtane outofprocess which was fine and working on 4.0.5

6. Looked at ".\logs\stdout" and saw the following files missing with errors like below

Microsoft.Extensions.Options
Microsoft.Extensions.Configuration.Binder

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Binder, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Configuration.Binder, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure[TOptions](IServiceCollection services, String name, IConfiguration config)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c.<ConfigureLocalizationSettings>b__0_0(WebHostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Oqtane.Server.Program.BuildWebHost(String[] args)
   at Oqtane.Server.Program.Main(String[] args)
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Binder, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Configuration.Binder, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure[TOptions](IServiceCollection services, String name, IConfiguration config)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c.<ConfigureLocalizationSettings>b__0_0(WebHostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Oqtane.Server.Program.BuildWebHost(String[] args)
   at Oqtane.Server.Program.Main(String[] args)
```

8. Then I did what @leigh-pointer suggested deleted all framework assemblies and replaced them from the [Oqtane.Framework.5.0.2.Install.zip](https://github.com/oqtane/oqtane.framework/releases/download/v5.0.2/Oqtane.Framework.5.0.2.Install.zip), and now I have the following error occurring in the ".\logs\stdout"

```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'Oqtane.Infrastructure.DatabaseManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Oqtane.Server.Program.Main(String[] args) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Program.cs:line 18
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'Oqtane.Infrastructure.DatabaseManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Oqtane.Server.Program.Main(String[] args) in C:\Source\Projects\oqtane.framework\Oqtane.Server\Program.cs:line 18
```

**Comment by thabaum** [comment] 2024-03-12 23:30
ok so you extracted these files, I was almost not going to say anything.

Did you re-grant permissions to your folders after extracting, I generally have to do this with IIS sites or they lose the IIS AppPool permissions.

Have you tried to grant permissions to child objects after extracting the new files?

**Comment by vnetonline** [comment] 2024-03-12 23:37
Yes the permissions aren’t an issue … fortunately I didn’t have anything on the sites I have just now installed a fresh copy which has worked. 

But if I did have things on the site it would have been. Really bad situation

**Comment by sbwalker** [comment] 2024-03-12 23:39
@vnetonline please note that the Oqtane.Framework.5.0.2.Upgrade.zip has a bunch of sub-folders ie. /refs, /runtimes... all of these sub-folders contain DLLs which are required for the application to function correctly - not just the root /bin folder. I am saying this because the IMemoryCache error is related to a missing DLL - Microsoft.Extensions.Caching.Abstractions.dll - which is located in the /refs folder of the Upgrade.zip.

**Comment by vnetonline** [comment] 2024-03-12 23:41
@sbwalker i had made sure that all files in the root and subfolders were copied across

**Comment by sbwalker** [comment] 2024-03-12 23:44
> @sbwalker i had made sure that all files in the root and subfolders were copied across

@vnetonline I have no idea why it would have complained about IMemoryCache unless the DLL was missing

**Comment by vnetonline** [comment] 2024-03-12 23:53
Hopefully the next upgrade to 5.1.0 will go well

**Comment by thabaum** [comment] 2024-03-13 00:44
@vnetonline I just went through that process of all steps provided just to check and itand had no issues.  I stopped both the app pool and site when copying over and I used the extract all drop down option right clicking on the file to the IIS folder.

I just went through the steps to reproduce.

downloaded 4.0.5
extracted to a folder hosted using IIS
Installed Oqtane
Stopped the site and app pool service
Downloaded and extracted 5.0.2 upgrade zip
Used the extract all drop down option right clicking on the file to the IIS folder
fired up the app pool and site
Reloaded website page, oqtane 5.0.2 loads in system menu.

I was not sure this would work for different versions since there are migrations that need handled I figured this would only work if nothing in the schema changes.  Otherwise some EF updates need handled.

@sbwalker can you help us know now how to create an upgrade package from Oqtane dev branch next and check if it works?

Is it just copying over certain directories or do we need to run a command script if I recall?  Any blog on this?  I will include what I can in a documentation update.  We can try to get this into oqtane.docs documentation soon.

Sounds like this is resolved otherwise no way to reproduce?

Thank you, Cheers!

**Comment by vnetonline** [comment] 2024-03-13 04:28
May it be becuase I didn't stop the site/app-pool and files didn't get overwritten because they were in use 

@thabaum **try not stopping** the site and app-pool and see if you can reproduce the situation I had

**Comment by thabaum** [comment] 2024-03-13 13:59
@vnetonline you would have to stop the app pool, I had issues if I didn't

**Comment by sbwalker** [comment] 2024-03-13 21:36
@vnetonline you definitely need to stop the Oqtane application in order to replace the files. A lot of people use the System Update feature which is located in the Admin Dashboard. It has logic to stop the Oqtane application and spin up a new ProcessInfo which runs a console application and has the ability to unzip the Upgrade package over top of the existing files. It would be possible to enhance the console application to delete files as well - however the problem is that an Oqtane installation may have custom themes and modules installed which contain their own dependencies, so it makes it difficult to determine files which are no longer required and can be deleted.

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/026a7642-9470-4c3d-96a8-48b05e2423ea)

**Comment by sbwalker** [comment] 2024-03-13 22:12
closing as this issue seems to be respolved

**Closed by sbwalker** 2024-03-13 22:12 UTC
