### ISSUE TITLE
An issue has been found where WebSockets is not available when deploying a site

### ISSUE THREAD

**Issue by InfDev** [oqtane/oqtane.framework#2224] opened 2022-05-28 08:20 UTC
An issue has been found where WebSockets is not available when deploying a site.
If WebSockets is unavailable, the transition to the Long Polling exchange mechanism is performed and, at the same time, an exception occurs on the client side

```
blazor.server.js:1 [2022-05-28T06:40:27.379Z] Information: Normalizing '_blazor' to 'https://team.infdev.com.ua/_blazor'.
blazor.server.js:1 [2022-05-28T06:40:27.409Z] Warning: Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection. To troubleshoot this, visit https://aka.ms/blazor-server-using-fallback-long-polling.
log @ blazor.server.js:1
blazor.server.js:1 [2022-05-28T06:40:27.431Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.DependencyInjection.OqtaneServiceCollectionExtensions.<>c.<AddHttpClients>b__10_1(IServiceProvider s) in E:\!AT\oqtane.framework\Oqtane.Server\Extensions\OqtaneServiceCollectionExtensions.cs:line 211
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.AddRootComponent(Type componentType, String domElementSelector)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass35_0.<<InitializeAsync>b__0>d.MoveNext()
log @ blazor.server.js:1
blazor.server.js:1 [2022-05-28T06:40:27.443Z] Information: Connection disconnected.
team.infdev.com.ua/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
team.infdev.com.ua/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
```

**Comment by sbwalker** [comment] 2022-05-28 13:40
It is impossible to investigate an issue unless you also provide the detailed context for what you were doing when the error occurred.

**Comment by InfDev** [comment] 2022-05-28 17:09
The effect remains the same

**Comment by sbwalker** [comment] 2022-05-30 00:28
The error message you posted says that blazor.server.js is being executed and throwing an error. If you look at _host.cshtml the only way that blazor.server.js can be injected into the page is if the Runtime is set to Server. If you set the configuration setting in appsettings.json to WebAssembly and attempt a new installation (ie. the DefaultConnectionion is "") then the Install Wizard will be displayed. If you view the page source using the tools in the browser you should see a reference to blazor.webassembly.js rather than a reference to blazor.server.js. If you are still getting the same error message related to blazor.server.js I do not understand how that could be possible.

**Comment by InfDev** [comment] 2022-05-30 07:42
I made a mistake when changing the hosting model. On an already installed site, I changed the settings in appsettings.json, but I had to change it in the database for the site in the Site table.
The site, when accessing pages that contain only basic configuration modules, worked fine with Rutime = WebAssembly and RenderMode = WebAssemblyPrerendered

**Comment by sbwalker** [comment] 2022-05-31 02:16
@InfDev I am confused... your original problem seemed to indicate that you were trying to install Oqtane in an environment that did not have web sockets enabled? However your post above indicates that Oqtane was already installed? How is this possible if web sockets were not enabled and you had not modified the appsettings.json? It is very challenging to provide assistance when an issue only contains an error message and no context or steps to reproduce. It is still not clear to me if there is an actual issue, or if this issue can be closed?

**Comment by InfDev** [comment] 2022-05-31 07:36
If there is no support for WebSockets on the server, then
- in Runtime = WebAssembly and RenderMode = WebAssemblyPrerendered everything works well
- in Runtime = Server and RenderMode = ServerPrerendered problem still exists

**Comment by sbwalker** [comment] 2022-05-31 11:08
Runtime = Server indicates that you want to run the framework on Blazor Server which relies on SignalR (web sockets) for all interaction. So this is by design. I will close this issue now.

**Closed by sbwalker** 2022-05-31 11:08 UTC
