### ISSUE TITLE
Uploads in Brave browser causes Server to quit

### ISSUE THREAD

**Issue by GregStevenson** [oqtane/oqtane.framework#3560] opened 2023-12-15 19:44 UTC
This is a behavior I first noticed in 4.x and since it still exists in 5.0, I thought I should mention it. If one is running the server in debug mode from Visual studio and tries to upload a file in the Brave browser, the server quits with no errors thrown. Doing the same thing in Chrome or Edge works fine as expected. Wondering if anyone else can repeat this issue?

**Comment by thabaum** [comment] 2023-12-15 20:58
I tested with brave successfully uploading a file using server project and and it worked OK without restarting anything or making an error, however I opened a brave browser using after launching it with default browser and using `http://localhost:44357/` after downloading the current dev branch.

I was uploading to the "public" folder an image.  I will test other folderI think we may need more details on what maybe causing this error since this works OK.  I did have to build the database solution projects first.  Not sure if I had to but I got an error first time trying to install a fresh copy from latest dev branch which felt like another issue that is being discussed and worked on.

Are you using the **Release** or **Dev** branch in Visual Studio?  
Check the Visual Studio environment is fully updated as far as the application and .NET runtime hosting packages go.  Sometimes this works out kinks with Visual Studio.

Another thing to check is if there are any settings in the Brave browser you may have set on your installation to create this issue.  I was using default new fresh installation of Brave browser to see if this was an issue for me as requested.  I notice Brave has other privacy and security options that other browsers do not offer.  I wonder if any of these are on I may not have set in my environment to test.

I can't repeat this issue after testing otherwise.

I hope this helps.

Cheers!

**Comment by leigh-pointer** [comment] 2023-12-16 09:17
I use  Brave, so i will look into it.

**Comment by GregStevenson** [comment] 2023-12-28 20:46
@thabaum, Thanks for checking things out for me. I was waiting for some additional feedback from @leigh-pointer, but since its been a while I'll respond now. I'm using the dev branch in visual studio and am current on everything, but I saw this back in 4.x as well. with .Net 7. So I don't think it is related to version mismatches. Most of my brave settings are default. Whatever is happening on the browser side, It should not cause Oqtane to crash.

Here is [video ](https://drive.google.com/file/d/1g5iW8f2ojnLUILAp1YjLKZNul1jrl4JQ/view?usp=sharing)showing the issue. I demonstrated the full upload working in chrome and then repeated in brave right after file is selected (before upload) Oqtane crashes. Browser keeps retrying a call unsuccessfully because server has gone away, but I'm not sure what the request is.

**Comment by leigh-pointer** [comment] 2023-12-28 21:27
@GregStevenson using Brave v1.61.109 (Dec 21, 2023) I had no adverse effects uploading.
![AnimationBraveSave](https://github.com/oqtane/oqtane.framework/assets/9447612/15a64673-2f7b-48f5-86f1-8b8736264bc8)

**Would suggest resetting the Brave browser.** 
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/00740202-2803-42e5-a3c5-b2c01c585a98)
![image](https://github.com/oqtane/oqtane.framework/assets/9447612/0c29272e-6522-4fde-8068-861dcd5be508)

**Comment by GregStevenson** [comment] 2023-12-29 14:46
@leigh-pointer  I'm also using the latest version.
![image](https://github.com/oqtane/oqtane.framework/assets/10802205/636ba367-dd17-4759-869f-0957d13da91b)

I can try resetting, but my bigger concern is how a browser issue can cause the server to abort.

**Comment by thabaum** [comment] 2023-12-29 17:26
@GregStevenson I am not going to say these relate but I am investigating another issue with uploads using Windows App Oqtane.Maui which generates an odd error reported in issue #3580. I am kinda focusing on the UploadFiles() method and the interop.js uploadFiles function currently.  I believe there is different javascript file code in Server and Maui projects.  I was wondering if we can get away from the interop.js if possible now in .NET 8 maybe rework this area if possible for handling the uploads which I am investigating now.  Once I get my production environment to test I will verify it is not a VS issue.  I am not having as smooth a time setting up this environment however using the release download and following directions in blog for some odd reason.  Once I conquer this in my IDE I will have more ways to test issues.  I had it running before many times, I am having a tough time all sudden with the 5.0.1 release not sure why yet.

**Comment by GregStevenson** [comment] 2023-12-29 19:41
@thabaum I think it would be good for me to keep my Brave instance as is for now as it seems to be the only case where we an replicate the issue consistently. I'm also open to trying to track this down, but I will need some help in where to look. I'll start with putting  breakpoints in the UploadFiles() method. I'm also open to other places to look as I'm not yet familiar with Oqtane internals. As with many issues, it makes no sense until you find the cause. Then it makes sense and you fix it.

**Comment by thabaum** [comment] 2023-12-29 22:10
From reviewing this issue and another relating to file uploads and .NET Maui I have been doing some investigating into this area myself recently.

From my findings here are some files of interest:

Oqtane.Server\wwwroot\js\interop.js
Oqtane.Maui\wwwroot\js\interop.js
Oqtane.Client\Modules\Controls\UI\FileManager.razor
Oqtane.Client\Services\FileService.cs
Oqtane.Server\Controllers\FileController.cs
Oqtane.Server\Repository\FileRepository.cs

And these docs and articles are ones relating Blazor file uploads and .NET 8 updates.

[JavaScript Interoperability (JS Interop) - Microsoft Docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0)
[Upload files in ASP.NET Core - Microsoft Docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0)

Plus some blogs relating to .NET 8 System.Text.Json and the current JS Interop enhancements.  Maybe there is a better way to handle uploads now that is more bulletproof in Blazor using ASP.NET Core.

**Comment by GregStevenson** [comment] 2023-12-31 20:45
@thabaum Thanks for the links and suggestions. I'll investigate this upcoming week.

**Comment by thabaum** [comment] 2024-01-13 00:32
@GregStevenson does the browser do the same when you visit www.oqtane.org, have you tested against latest dev repository?

**Comment by thabaum** [comment] 2024-01-21 22:14
@GregStevenson Issue #3656 sure seems to be maybe related?!  Maybe you had saved site settings and this now causes the Brave bug?

**Comment by thabaum** [comment] 2024-01-23 22:48
@GregStevenson Any luck testing the latest repo in dev branch here?

If you want to try a quick test for the save site settings bug, you can add or remove an extension from the file extensions and should resolve as it will save to database, blank will not work is the issue and after saving a site setting it creates this setting empty.

Again just try changing up the allowed extensions to anything but default, then try uploading in your Brave browser.

**Comment by thabaum** [comment] 2024-01-24 23:48
@GregStevenson After our discussions earlier, I would like to recommend trying a couple things.

1. Test with Visual Studio Community (not preview) just so we know the preview edition is not causing your issue.  Preview edition issues are not as supported by Oqtane community generally.  I found it best to just keep the community edition up to date to avoid preview bugs.
2. Save Site Settings after adding or removing a file extension in the comma separated list so it is saved to database (or download and build a new Oqtane database instance)
3. If you are connecting to the same database instance (not a new site fresh install on your database) let us know as it maybe a data entry the database itself generating the behavior you are experiencing.

**Comment by GregStevenson** [comment] 2024-01-25 01:23
@thabaum,

1) Happens in non-preview version as well.
2) Happens with latest dev branch. Saving settings after alteration does not help. File extension changes are saved however.
3) Same thing happens on fresh db instance.
--Nothing is written to Content\Logs folder when this happens.
--Browser networking has https://localhost:44300/_blazor/negotiate?negotiateVersion=1 but these appear (and continue) after server is down. No other errors noted in browser.
-- The only error that appears in the output console is: The program '[42032] iisexpress.exe' has exited with code 4294967295 (0xffffffff).

**Note:**  This always happens when attempting to exit the open file dialog after clicking choose file. Even closing the dialog or clicking cancel without doing anything else will cause the issue.

**Comment by GregStevenson** [comment] 2024-01-25 20:23
@thabaum ,

IIS Express Logs and TraceLogs folders are empty. 
I'm setting up a site SmarterASP.net who I plan to use to host the deployed app, so I'll test there today or tomorrow. I'll also try to install IIS locally according to the blog.

Thanks for your support and suggestions in this matter.

--Greg

**Comment by GregStevenson** [comment] 2024-01-25 20:25
How do I install IIS on my local computer

**Comment by thabaum** [comment] 2024-01-25 21:11
System > Optional Features in Windows 11
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/5d9670df-f5fe-49ea-8314-57d3fe7619e1)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/36c3db40-6077-46c8-a083-5c0203c52240)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/577a5028-381a-4ea5-8001-89a13662ab87)

**Comment by thabaum** [comment] 2024-01-25 22:05
@GregStevenson I was sleeping last night... and eureka moment possibly here as I felt this seemed familiar.  I maybe not correct, but are you using a folder inside your my documents folder for example to host the VS project?

If you are, please try moving it to a folder like C:\Dev\Oqtane\Release\ Extract here... and see if the shorter name helps it stay firing?!  Sometimes if a name of a file is too long in Windows operating systems, your app will fail.  I noticed this with Oqtane while I was developing and a note we should include in docs.

**Comment by GregStevenson** [comment] 2024-01-25 22:25
@thabaum ,
Thanks for the additional info. The comment about how to install IIS was actually intended for chatGPT. Got every thing installed according to the Blog instructions, updating versions as needed. It is located here:
C:\!!!Octane\Oqtane.Framework.5.0.2.Install
And IIS finds it just fine.
![image](https://github.com/oqtane/oqtane.framework/assets/10802205/9c1f8b31-d605-4ca4-ac77-9ef8564818fc)
I also created a self signed cert for oqtane.dev and put it in the trusted certs.
However, I get a 401 when trying to bring up the page. I tried Chrome, Brave, and Edge with same result. The install wizard fails to come up. Is there something else I might be missing?

Regards,

**Comment by thabaum** [comment] 2024-01-25 22:37
@GregStevenson did you install all the packages IIS Url Rewrite, Hosting Bundle and Windows Update?  

Last be sure your permissions are set for the IIS AppPool\YourAppPoolName has modify rights minimum on the directory folder and files.

**Comment by thabaum** [comment] 2024-01-25 22:51
@GregStevenson I would suggest test the installation page via HTTP First.  I remember was troubleshooting SSL in Signed Certs and I can't recall if it works OK or not in IIS Express now after helping work on the other issues over the past weeks.  It works great in production.  I will investigate more when I can and let you know.

**Comment by GregStevenson** [comment] 2024-01-25 23:39
@thabaum,

Tried HTTP, but browser security is not allowing that. However was able to get 5.02 up on hosting service and **brave uploads work** from there. I'd like to keep this issue open for another week to (1) see if it works with local IIS and (2) see if I can track. down the issue.

However, I think the rest of the team can focus on other issues for now. I have friends outside the Oqtane community that should be able to help with the local IIS issues.

Regards...

**Comment by thabaum** [comment] 2024-01-26 01:32
@GregStevenson Wish you the best in troubleshooting, let us know what you discover if you find out your issue.

I had one more suggestion or question which is are you running Visual Studio with SSL enabled?
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/3813459b-0e0f-49c2-8676-f4bbc1902a1f)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/fc238780-dc2d-4ff4-af88-81e350812039)

You may try checking that box to utilize Oqtane using SSL in Visual Studio which I believe works for me.  Your browser maybe fighting with SSL issues?!

**Comment by thabaum** [comment] 2024-02-28 04:22
@GregStevenson A couple ideas for your issue:
1. find the hidden .vs folder inside the project folder and delete it or try downloading Oqtane to a new folder.
2. Control + F5 generally clears browser cache if your willing to try this

**Comment by sbwalker** [comment] 2024-03-04 14:48
I am going to close this issue as it can not be reliably reproduced

**Closed by sbwalker** 2024-03-04 14:48 UTC
