### ISSUE TITLE
Module Management bug

### ISSUE THREAD

**Issue by markagama** [oqtane/oqtane.framework#3597] opened 2023-12-29 02:07 UTC
Trying to create a new module. Can't get a name that follows the schema Agama.Oqtane.Module.Mymodule

And this error appeared and won't go away - it looks like a cache problem or bug. I've restarted the CMS and VS2022

<img width="971" alt="Screenshot 2023-12-29 130446" src="https://github.com/oqtane/oqtane.framework/assets/91863103/df39ef8b-2925-46d5-9f77-c079908851d3">

**Comment by thabaum** [comment] 2023-12-29 18:16
@markagama  I can reproduce this issue and will try to investigate this some myself today for any clues as to why.

The error message has the X to dismiss and make it go away, but then never re-appears if you close it and hit create module again so you dont know the error is happening.  I believe this needs looked into for a solution as well as it happens all over the Oqtane admin UI.

This would make 2 issues here to resolve, but the main focus is the module management create module action validation.

**Comment by thabaum** [comment] 2023-12-29 18:17
@markagama The issue seems to be pinpointed to the Module Name.  Remove "Oqtane" from "OqtaneGIS" and only have "GIS" and the module is created.

**Comment by markagama** [comment] 2023-12-29 22:05
thank you for pin pointing the problem, as mentioned, I use a naming schema that it agama followed by the CMS name then the module name.

In this case the word Module appears to be hard coded into Oqtane - not sure why.

May I suggest the way forward is the use of a GUID to identify modules - then the name does not matter - and this will permit all sorts of problems to go away - as Microsoft found back in the 1990s.

**Comment by thabaum** [comment] 2023-12-29 23:24
@markagama I believe this check is to avoid namespace collisions within the framework where you can make a function with the same name in your module and it cause issues with other parts of the framework that rely on that function.  As in when creating the module it's namespace is Oqtane.Agama.GIS if named as Agama for the module owner and GIS for the module name.  I maybe wrong but I am pretty sure this is the reason behind this.  

The "Oqtane" word check can probably go away and things still work just fine for most cases.  This just happens to be currently the behavior of the framework and not currently explained to a user that it is which generates this confusion you had experienced.

We could use some help with documentation pull requests that help boost user support in areas like this.  I believe this should go in a [Module Management ](https://docs.oqtane.org/admin/host-administration/module-management.html)  add a Create Module documentation article.

It would be nice to get Oqtane Framework documentation fully updated for latest version with all features fully explained as they currently exist.  The images are outdated in some places now as well since last updated.  Community support is much needed in this area.

**Comment by sbwalker** [comment] 2023-12-30 13:34
@thabaum you are correct that the validation check is to prevent namespace collisions with the Oqtane Framework. This was added because of a past issue where the generated code would not compile because of a namespace conflict. Perhaps this validation is too broad, and instead of checking if the Organization or Module name contains the word "oqtane" it should validate if the Organization or Module name starts with "oqtane.". This would allow more flexibility - however it would need to be well tested to ensure the resulting code still compiles.

**Comment by thabaum** [comment] 2023-12-30 17:33
@sbwalker to avoid the namespace conflict I would think only the organization name needs to be checked for "oqtane" since that is the namespace the module name lives in correct?  So as long as the "Owner" is not the word "oqtane" as this can contain the word "oqtane" and not conflict as in it can be owner "OqtaneOwner" and should be in it's own space not conflicting with the "Oqtane" namespace.  Even if you name the module "oqtane" it still resides in it's own namespace "OqtaneOwner.Oqtane" which is different from namespace "Oqtane.*" and should not conflict if I am correct.  So I am not sure the module name needs this check does it since it is the owner namespace that is all that needs to be unique to avoid issues with the framework namespace.

I think we just need to check if Owner is not equal to oqtane to pass the check and an error message should be presented stating this owner name is not allowed when it does.

This should give as much flexibility as needed and fine tune the check to only stop the main "Oqtane" namespace code collision.

**Comment by sbwalker** [comment] 2023-12-30 18:09
You are incorrect. The reason why the validation check was added to both Organization and Module is because of conflicts.

**Comment by thabaum** [comment] 2023-12-30 19:13
In this example presented the name "OqtaneGIS" would still fail the check if just looking at the start but would give a little more flexibility as you mentioned.

So just the fact it starts with Oqtane in a namespace you get a conflict?  I would think as long as it is not "oqtane" should be enough as any other variation should be in its own space and not conflict.

**Comment by sbwalker** [comment] 2024-01-05 19:01
I did some testing on this item today... specifically I changed the validation to only restrict StartsWith("oqtane.") and allowed "." in the name. I then used an Organization Name of "Siliqon.Oqtane" and a Module Name of "Test". When I open the code in Visual Studio there are LOT of compilation errors. Most errors are related to the fact that .NET assumes the "Oqtane" type name is within the Siliqon namespace - and it cannot find the types:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/2fa08072-44c7-41df-a187-0c5602d9540d)

There is a solution to this problem... which is a bit of a "hack" and is not very widely used. It involves using the "global::" qualifier to the type names to indicate they are not nested but should be considered global:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/1c26fe75-a927-4260-af77-fb3190806df5)

There are a number of areas in the client and server projects where this "global::" qualifier needs to be added in order to get the code to compile successfully. In addition there is an issue with the syntax for the interop.js file generated:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/9d2ef4c0-e3a5-47b1-bf42-233da2de3e43)

which could be changed to:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/1bcc1b8c-addf-4a77-93f7-662958ccd0fa)

Regardless, this basically explains why the term "oqtane" was included in the validation criteria previously - and that .NET namespaces do not always behave as expected.

**Comment by sbwalker** [comment] 2024-01-05 20:45
A good reference for the "global::" qualifier:

https://stackoverflow.com/questions/15022441/what-is-global

**Comment by markagama** [comment] 2024-01-06 04:16
thank you @sbwalker - by not starting at the top and working down, dotnet provides a bit of a mess. I have read about global:: before, as there was a similar problem that a friend found whilst doing a contract job.

As you mentioned the namespace can be changed later - I'll do some reading on this. For now "Oqtane" has been removed from my namespace.

**Comment by thabaum** [comment] 2024-01-06 04:47
To resolve this issue I think a note letting a developer know not to use "oqtane" should be a good enough solution to close this.  

Only an Oqtane Developer would see this message anyhow and can be changed in the resource files.  

We could rethink the message delivery and/or put a link to the docs that cover this in full details in the message as well.  I think it would help anyone developing with their on boarding experience having links go to documentation pages with rich content and detailed information related to the module development creation for example.

Solution in PR #3598 would resolve this since allowing oqtane into namespaces creates too many conflicts and can cause too much odd framework behavior otherwise worth dealing with resolving.

@sbwalker if you want the wording differently you can close/edit my PR to put in a more acceptable solution.

@markagama Glad to hear things are working out in the end.  Wish you the best moving forward.

Cheers!

**Comment by sbwalker** [comment] 2024-01-06 13:41
Parking the validation logic change here until there is time to explore all of the changes required to the default module template to support it.

```
    private bool IsValid(string name)
    {
        // must contain letters, underscores and digits and first character must be letter or underscore
        return !string.IsNullOrEmpty(name) && name.ToLower() != "module" && !name.ToLower().StartsWith("oqtane.") && Regex.IsMatch(name, "^[A-Za-z_][A-Za-z0-9_.]*$");
    }
```

**Comment by thabaum** [comment] 2024-01-07 20:09
`// must contain letters, underscores and digits and first character must be letter or underscore`

This message should be updated with the notification message to reflect this change.  I can update the notification message PR #3598 to reflect this change if you are moving forward in this direction so it is ready to merge.

**Closed** 2024-01-19 20:18 UTC
