### ISSUE TITLE
Version 2.2.0. Apparently, I cannot assign the "Host Users" role to any user?

### ISSUE THREAD

**Issue by horacioj** [oqtane/oqtane.framework#1578] opened 2021-08-03 18:23 UTC
Apparently, I cannot assign the "Host Users" role to any user.
In addition, deleting an user doesn't remove it from the list unless I full reload the page.
Please see the attached video.

https://user-images.githubusercontent.com/984821/128066628-5f1080c6-8c33-4a0c-8011-aa905850afcd.mp4

**Comment by sbwalker** [comment] 2021-08-05 12:45
The inability to add the Host role to a user is a bug that was mistakenly introduced in the 2.2 release. The problem is that the API Controller is verifying that the SiteId for the Role in the model matches the SiteId for the current Alias for the request - and in the case of the Host role its SiteId is null by design as it applies to all sites. I will submit a PR for this item today.

**Comment by horacioj** [comment] 2021-08-05 14:12
You rock man! 
It would be also nice to solve refreshing the list after deleting an item to avoid end-users confusion.

**Comment by sbwalker** [comment] 2021-08-05 14:13
Yes, that issue will be resolved as well.

**Comment by horacioj** [comment] 2021-08-05 14:18
BTW, at some point I would like to be able to do fixes and submit PR myself, but I'm still far on the learning curve (new to Blazor and new to Oqtane).

**Comment by sbwalker** [comment] 2021-08-05 14:21
Reporting issues is just as valuable to the community as fixing issues

**Comment by sbwalker** [comment] 2021-08-06 16:56
Both issues are resolved in #1592

**Closed by sbwalker** 2021-08-06 16:56 UTC
